
import type { LanguageData } from './types';

const alphabet = [
    { letter: ['A', 'a'], exampleWord: 'Avion', exampleImage: 'https://picsum.photos/seed/avion/200/200' },
    { letter: ['B', 'b'], exampleWord: 'Bicikl', exampleImage: 'https://picsum.photos/seed/bicikl/200/200' },
    { letter: ['C', 'c'], exampleWord: 'Cipele', exampleImage: 'https://picsum.photos/seed/cipele/200/200' },
    { letter: ['Č', 'č'], exampleWord: 'Čaša', exampleImage: 'https://picsum.photos/seed/casa/200/200' },
    { letter: ['Ć', 'ć'], exampleWord: 'Ćevapi', exampleImage: 'https://picsum.photos/seed/cevapi/200/200' },
    { letter: ['D', 'd'], exampleWord: 'Drvo', exampleImage: 'https://picsum.photos/seed/drvo/200/200' },
    { letter: ['Dž', 'dž'], exampleWord: 'Džep', exampleImage: 'https://picsum.photos/seed/dzep/200/200' },
    { letter: ['Đ', 'đ'], exampleWord: 'Đak', exampleImage: 'https://picsum.photos/seed/dak/200/200' },
    { letter: ['E', 'e'], exampleWord: 'Ekran', exampleImage: 'https://picsum.photos/seed/ekran/200/200' },
    { letter: ['F', 'f'], exampleWord: 'Fudbal', exampleImage: 'https://picsum.photos/seed/fudbal/200/200' },
    { letter: ['G', 'g'], exampleWord: 'Gitara', exampleImage: 'https://picsum.photos/seed/gitara/200/200' },
    { letter: ['H', 'h'], exampleWord: 'Hljeb', exampleImage: 'https://picsum.photos/seed/hljeb/200/200' },
    { letter: ['I', 'i'], exampleWord: 'Igla', exampleImage: 'https://picsum.photos/seed/igla/200/200' },
    { letter: ['J', 'j'], exampleWord: 'Jabuka', exampleImage: 'https://picsum.photos/seed/jabuka/200/200' },
    { letter: ['K', 'k'], exampleWord: 'Knjiga', exampleImage: 'https://picsum.photos/seed/knjiga/200/200' },
    { letter: ['L', 'l'], exampleWord: 'Lopta', exampleImage: 'https://picsum.photos/seed/lopta/200/200' },
    { letter: ['Lj', 'lj'], exampleWord: 'Ljubav', exampleImage: 'https://picsum.photos/seed/ljubav/200/200' },
    { letter: ['M', 'm'], exampleWord: 'Mačka', exampleImage: 'https://picsum.photos/seed/macka/200/200' },
    { letter: ['N', 'n'], exampleWord: 'Noga', exampleImage: 'https://picsum.photos/seed/noga/200/200' },
    { letter: ['Nj', 'nj'], exampleWord: 'Njiva', exampleImage: 'https://picsum.photos/seed/njiva/200/200' },
    { letter: ['O', 'o'], exampleWord: 'Oblak', exampleImage: 'https://picsum.photos/seed/oblak/200/200' },
    { letter: ['P', 'p'], exampleWord: 'Pas', exampleImage: 'https://picsum.photos/seed/pas/200/200' },
    { letter: ['R', 'r'], exampleWord: 'Riba', exampleImage: 'https://picsum.photos/seed/riba/200/200' },
    { letter: ['S', 's'], exampleWord: 'Sunce', exampleImage: 'https://picsum.photos/seed/sunce/200/200' },
    { letter: ['Š', 'š'], exampleWord: 'Šuma', exampleImage: 'https://picsum.photos/seed/suma/200/200' },
    { letter: ['T', 't'], exampleWord: 'Trava', exampleImage: 'https://picsum.photos/seed/trava/200/200' },
    { letter: ['U', 'u'], exampleWord: 'Uho', exampleImage: 'https://picsum.photos/seed/uho/200/200' },
    { letter: ['V', 'v'], exampleWord: 'Voda', exampleImage: 'https://picsum.photos/seed/voda/200/200' },
    { letter: ['Z', 'z'], exampleWord: 'Zebra', exampleImage: 'https://picsum.photos/seed/zebra/200/200' },
    { letter: ['Ž', 'ž'], exampleWord: 'Žaba', exampleImage: 'https://picsum.photos/seed/zaba/200/200' },
];

const numbers = [
    { number: 0, word: "nula" },
    { number: 1, word: "jedan" },
    { number: 2, word: "dva" },
    { number: 3, word: "tri" },
    { number: 4, word: "četiri" },
    { number: 5, word: "pet" },
    { number: 6, word: "šest" },
    { number: 7, word: "sedam" },
    { number: 8, word: "osam" },
    { number: 9, word: "devet" },
    { number: 10, word: "deset" },
    { number: 11, word: "jedanaest" },
    { number: 12, word: "dvanaest" },
    { number: 13, word: "trinaest" },
    { number: 14, word: "četrnaest" },
    { number: 15, word: "petnaest" },
    { number: 16, word: "šesnaest" },
    { number: 17, word: "sedamnaest" },
    { number: 18, word: "osamnaest" },
    { number: 19, word: "devetnaest" },
    { number: 20, word: "dvadeset" },
    { number: 21, word: "dvadeset jedan" },
    { number: 22, word: "dvadeset dva" },
    { number: 23, word: "dvadeset tri" },
    { number: 24, word: "dvadeset četiri" },
    { number: 25, word: "dvadeset pet" },
    { number: 26, word: "dvadeset šest" },
    { number: 27, word: "dvadeset sedam" },
    { number: 28, word: "dvadeset osam" },
    { number: 29, word: "dvadeset devet" },
    { number: 30, word: "trideset" },
    { number: 40, word: "četrdeset" },
    { number: 50, word: "pedeset" },
    { number: 60, word: "šezdeset" },
    { number: 70, word: "sedamdeset" },
    { number: 80, word: "osamdeset" },
    { number: 90, word: "devedeset" },
    { number: 100, word: "sto" },
];

export const data: LanguageData = {
  bosnian: {
    '1-3': {
      alphabet: alphabet,
      numbers: numbers,
      vocabulary: [
        { id: 1, word: 'kafa', translation: 'kaffe' },
        { id: 21, word: 'Hljeb/kruh', translation: 'bröd' },
        { id: 2, word: 'škola', translation: 'skola' },
        { id: 3, word: 'kuća', translation: 'hus' },
        { id: 4, word: 'knjiga', translation: 'bok' },
        { id: 5, word: 'jabuka', translation: 'äpple' },
        { id: 6, word: 'auto', translation: 'bil' },
        { id: 7, word: 'mačka', translation: 'katt' },
        { id: 8, word: 'pas', translation: 'hund' },
        { id: 9, word: 'lopta', translation: 'boll' },
        { id: 10, word: 'sunce', translation: 'sol' },
        { id: 11, word: 'voda', translation: 'vatten' },
        { id: 12, word: 'stolica', translation: 'stol' },
        { id: 13, word: 'sat', translation: 'klocka' },
        { id: 14, word: 'most', translation: 'bro' },
        { id: 15, word: 'drvo', translation: 'träd' },
        { id: 16, word: 'cvijet', translation: 'blomma' },
        { id: 17, word: 'prozor', translation: 'fönster' },
        { id: 18, word: 'vrata', translation: 'dörr' },
        { id: 19, word: 'nebo', translation: 'himmel' },
        { id: 20, word: 'trava', translation: 'gräs' },
        { id: 22, word: 'mlijeko', translation: 'mjölk' },
        { id: 23, word: 'šećer', translation: 'socker' },
        { id: 24, word: 'so', translation: 'salt' },
        { id: 25, word: 'prijatelj', translation: 'vän' },
        { id: 26, word: 'avion', translation: 'flygplan' },
        { id: 27, word: 'bicikl', translation: 'cykel' },
        { id: 28, word: 'voz', translation: 'tåg' },
        { id: 29, word: 'brod', translation: 'båt' },
        { id: 30, word: 'krevet', translation: 'säng' },
        { id: 31, word: 'telefon', translation: 'telefon' },
        { id: 32, word: 'televizor', translation: 'TV' },
        { id: 33, word: 'kišobran', translation: 'paraply' },
        { id: 34, word: 'lopov', translation: 'tjuv' },
        { id: 35, word: 'policajac', translation: 'polis' },
        { id: 36, word: 'učitelj', translation: 'lärare' },
        { id: 37, word: 'učenik', translation: 'elev' },
        { id: 38, word: 'ljekar', translation: 'läkare' },
        { id: 39, word: 'bolnica', translation: 'sjukhus' },
        { id: 40, word: 'prodavnica', translation: 'affär' },
        { id: 41, word: 'novac', translation: 'pengar' },
        { id: 42, word: 'vrijeme', translation: 'tid' },
        { id: 43, word: 'pitanje', translation: 'fråga' },
        { id: 44, word: 'odgovor', translation: 'svar' },
        { id: 45, word: 'problem', translation: 'problem' },
        { id: 46, word: 'rječnik', translation: 'ordbok' },
        { id: 47, word: 'olovka', translation: 'penna' },
        { id: 48, word: 'sveska', translation: 'skrivbok' },
        { id: 49, word: 'sto', translation: 'bord' },
        { id: 50, word: 'oblak', translation: 'moln' },
        { id: 51, word: 'kiša', translation: 'regn' },
        { id: 52, word: 'snijeg', translation: 'snö' },
        { id: 53, word: 'prst', translation: 'finger' },
        { id: 54, word: 'glava', translation: 'huvud' },
        { id: 55, word: 'noga', translation: 'ben' }
      ],
      spelling: [
        { id: 1, sentence: 'Moja mama pije ___.', blank: 'kafu', options: ['stolicu', 'kafu', 'lopatom'] },
        { id: 2, sentence: 'Idem u ___.', blank: 'školu', options: ['školu', 'oblak', 'drvetom'] },
        { id: 3, sentence: 'Ovo je moja ___.', blank: 'kuća', options: ['nebo', 'sreća', 'kuća'] },
        { id: 4, sentence: 'Čitam ___.', blank: 'knjigu', options: ['knjigu', 'staklo', 'zidom'] },
        { id: 5, sentence: 'Jedem ___.', blank: 'jabuku', options: ['kamen', 'jabuku', 'cipelom'] },
        { id: 6, sentence: 'Učiteljica nosi ___.', blank: 'naočale', options: ['naočale', 'naočare', 'naoćale'] },
        { id: 7, sentence: 'Na tanjiru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
        { id: 8, sentence: 'Djed nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
        { id: 9, sentence: 'Idem u ___ spavati.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
        { id: 10, sentence: 'Imam novu ___.', blank: 'kuću', options: ['kuću', 'kuču', 'kucu'] },
        { id: 11, sentence: 'U bašči raste crveni ___.', blank: 'cvijet', options: ['cvijet', 'cvjet', 'cvit'] },
        { id: 12, sentence: 'To je moj najbolji ___.', blank: 'prijatelj', options: ['prijatelj', 'prijatel', 'priatelj'] },
        { id: 13, sentence: 'Djevojčica ima dugu ___.', blank: 'kosu', options: ['kosu', 'košu', 'koso'] },
        { id: 14, sentence: 'Baka pravi ukusan ___.', blank: 'kolač', options: ['kolač', 'kolać', 'kolac'] },
        { id: 15, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lishche', 'Lisce'] },
        { id: 16, sentence: '___ se igra s loptom.', blank: 'Dječak', options: ['Dječak', 'Dečak', 'Djećak'] },
        { id: 17, sentence: 'U ___ ima puno knjiga.', blank: 'biblioteci', options: ['biblioteci', 'knjižnici', 'knjižnjici'] },
        { id: 18, sentence: 'Danas je lijep dan u ___.', blank: 'Sarajevu', options: ['Sarajevu', 'Sarejevu', 'Sarajvu'] },
        { id: 19, sentence: 'U džezvi se pravi ___.', blank: 'kafa', options: ['kafa', 'ćevap', 'džem'] },
        { id: 20, sentence: 'Volim jesti pitu u ___.', blank: 'buregdžinici', options: ['buregdžinici', 'burekčinici', 'burekcinicu'] },
        { id: 21, sentence: 'Djevojčica sjedi u ___.', blank: 'sjenici', options: ['sjenici', 'śenici', 'sijenici'] },
        { id: 22, sentence: 'On je moj ___.', blank: 'đak', options: ['đak', 'djak', 'džak'] },
        { id: 23, sentence: 'Vani je prava ___.', blank: 'mećava', options: ['mećava', 'mečava', 'mećeva'] },
        { id: 24, sentence: 'Obukao je smeđi ___.', blank: 'džemper', options: ['džemper', 'đemper', 'demper'] },
        { id: 25, sentence: 'Ovo je ___ škola.', blank: 'dječja', options: ['dječja', 'diječja', 'dečja'] },
        { id: 26, sentence: 'U sobi je upaljena ___.', blank: 'svijeća', options: ['svijeća', 'sviječa', 'sveća'] },
        { id: 27, sentence: 'Boli me desno ___.', blank: 'rame', options: ['rame', 'ramje', 'ranje'] },
        { id: 28, sentence: 'Mačka prede u ___.', blank: 'krilu', options: ['krilu', 'krinju', 'krillu'] }
      ],
      sentences: [
        { id: 1, sentence: 'Dječak čita knjigu.' },
        { id: 2, sentence: 'Djevojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na tabli.' },
        { id: 7, sentence: 'Djeca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sija svaki dan.' },
        { id: 9, sentence: 'Ja volim jesti sladoled.' },
        { id: 10, sentence: 'Moj tata vozi auto.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Djed čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lijep dan.' },
        { id: 18, sentence: 'Snijeg pada zimi.' },
        { id: 19, sentence: 'Volim crtati cvijeće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' },
        { id: 21, sentence: 'Pijemo hladnu limunadu.' },
        { id: 22, sentence: 'Voz putuje brzo.' },
        { id: 23, sentence: 'On ima novu igračku.' },
        { id: 24, sentence: 'Ona pjeva lijepu pjesmu.' },
        { id: 25, sentence: 'Idemo na izlet sutra.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamjenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (veliki).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' }
      ],
      reading: [
        {
          id: 1,
          title: "Izlet u šumu",
          text: "Jednog sunčanog dana, Amina i njen brat Adnan su otišli na izlet u šumu sa roditeljima. Ponijeli su korpu punu hrane. U šumi su vidjeli mnogo drveća i čuli cvrkut ptica. Adnan je vidio vjevericu kako se penje uz drvo. Amina je brala šareno cvijeće. Nakon šetnje, sjeli su na deku i ručali. Bio je to divan dan.",
          questions: [
            { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Amina", "Amina i Adnan sa roditeljima", "Samo Adnan"], answer: "Amina i Adnan sa roditeljima" },
            { id: 2, question: "Šta je Adnan vidio u šumi?", options: ["Zeca", "Medvjeda", "Vjevericu"], answer: "Vjevericu" },
            { id: 3, question: "Šta je Amina radila?", options: ["Pela se na drvo", "Brala cvijeće", "Spavala"], answer: "Brala cvijeće" },
            { id: 4, question: "Kakav je bio dan?", options: ["Kišovit", "Divan", "Hladan"], answer: "Divan" }
          ]
        },
        {
          id: 2,
          title: "Pas Medo",
          text: "Dječak po imenu Amar ima psa koji se zove Medo. Medo je veliki žuti pas sa dugim repom. Svaki dan, Amar i Medo idu u park. Amar baca lopticu, a Medo je donosi nazad. Medo voli da se igra i da laje na mačke. Navečer, Medo spava u svojoj kućici u dvorištu. Amar mnogo voli svog psa.",
          questions: [
            { id: 1, question: "Kako se zove Amarov pas?", options: ["Žućo", "Lajko", "Medo"], answer: "Medo" },
            { id: 2, question: "Gdje se Amar i Medo igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
            { id: 3, question: "Šta Amar baca Medi?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
            { id: 4, question: "Gdje Medo spava?", options: ["U Amarovom krevetu", "U svojoj kućici", "Na drvetu"], answer: "U svojoj kućici" }
          ]
        }
      ],
      translations: [
        { id: 1, type: 'word', source: 'kaffe', target: 'kafa' },
        { id: 2, type: 'word', source: 'skola', target: 'škola' },
        { id: 3, type: 'word', source: 'hus', target: 'kuća' },
        { id: 4, type: 'word', source: 'bok', target: 'knjiga' },
        { id: 5, type: 'word', source: 'äpple', target: 'jabuka' },
        { id: 6, type: 'word', source: 'bil', target: 'auto' },
        { id: 7, type: 'word', source: 'katt', target: 'mačka' },
        { id: 8, type: 'word', source: 'hund', target: 'pas' },
        { id: 9, type: 'word', source: 'boll', target: 'lopta' },
        { id: 10, type: 'word', source: 'sol', target: 'sunce' },
        { id: 11, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
        { id: 12, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Djevojčica jede jabuku.' },
        { id: 13, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 14, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 15, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi auto.' },
      ]
    },
    '4-6': {
      alphabet: [],
      numbers: [],
      vocabulary: [
        { id: 101, word: 'rijeka', translation: 'flod' },
        { id: 102, word: 'planina', translation: 'berg' },
        { id: 103, word: 'more', translation: 'hav' },
        { id: 104, word: 'grad', translation: 'stad' },
        { id: 105, word: 'selo', translation: 'by' },
        { id: 106, word: 'država', translation: 'land' },
        { id: 107, word: 'jezik', translation: 'språk' },
        { id: 108, word: 'historija', translation: 'historia' },
        { id: 109, word: 'geografija', translation: 'geografi' },
        { id: 110, word: 'matematika', translation: 'matematik' },
        { id: 111, word: 'računar', translation: 'dator' },
        { id: 112, word: 'internet', translation: 'internet' },
        { id: 113, word: 'film', translation: 'film' },
        { id: 114, word: 'muzika', translation: 'musik' },
        { id: 115, word: 'umjetnost', translation: 'konst' },
        { id: 116, word: 'sport', translation: 'sport' },
        { id: 117, word: 'zdravlje', translation: 'hälsa' },
        { id: 118, word: 'hrana', translation: 'mat' },
        { id: 119, word: 'piće', translation: 'dryck' },
        { id: 120, word: 'porodica', translation: 'familj' },
        { id: 121, word: 'prijateljstvo', translation: 'vänskap' },
        { id: 122, word: 'ljubav', translation: 'kärlek' },
        { id: 123, word: 'sreća', translation: 'lycka' },
        { id: 124, word: 'tuga', translation: 'sorg' },
        { id: 125, word: 'znanje', translation: 'kunskap' },
        { id: 126, word: 'budućnost', translation: 'framtid' },
        { id: 127, word: 'prošlost', translation: 'dåtid' },
        { id: 128, word: 'sadašnjost', translation: 'nutid' },
        { id: 129, word: 'svijet', translation: 'värld' },
        { id: 130, word: 'svemir', translation: 'universum' }
      ],
      spelling: [],
      sentences: [],
      grammar: [],
      reading: [],
      translations: []
    },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [], alphabet: [], numbers: [] },
  },
  croatian: {
    '1-3': {
      alphabet: alphabet,
      numbers: numbers,
      vocabulary: [
        { id: 1, word: 'kava', translation: 'kaffe' },
        { id: 2, word: 'kruh', translation: 'bröd' },
        { id: 3, word: 'škola', translation: 'skola' },
        { id: 4, word: 'kuća', translation: 'hus' },
        { id: 5, word: 'knjiga', translation: 'bok' },
        { id: 6, word: 'jabuka', translation: 'äpple' },
        { id: 7, word: 'automobil', translation: 'bil' },
        { id: 8, word: 'mačka', translation: 'katt' },
        { id: 9, word: 'pas', translation: 'hund' },
        { id: 10, word: 'lopta', translation: 'boll' },
        { id: 11, word: 'sunce', translation: 'sol' },
        { id: 12, word: 'voda', translation: 'vatten' },
        { id: 13, word: 'stolica', translation: 'stol' },
        { id: 14, word: 'sat', translation: 'klocka' },
        { id: 15, word: 'most', translation: 'bro' },
        { id: 16, word: 'stablo', translation: 'träd' },
        { id: 17, word: 'cvijet', translation: 'blomma' },
        { id: 18, word: 'prozor', translation: 'fönster' },
        { id: 19, word: 'vrata', translation: 'dörr' },
        { id: 20, word: 'nebo', translation: 'himmel' },
        { id: 21, word: 'trava', translation: 'gräs' },
        { id: 22, word: 'mlijeko', translation: 'mjölk' },
        { id: 23, word: 'šećer', translation: 'socker' },
        { id: 24, word: 'sol', translation: 'salt' },
        { id: 25, word: 'prijatelj', translation: 'vän' },
        { id: 26, word: 'zrakoplov', translation: 'flygplan' },
        { id: 27, word: 'bicikl', translation: 'cykel' },
        { id: 28, word: 'vlak', translation: 'tåg' },
        { id: 29, word: 'brod', translation: 'båt' },
        { id: 30, word: 'krevet', translation: 'säng' },
        { id: 31, word: 'telefon', translation: 'telefon' },
        { id: 32, word: 'televizor', translation: 'TV' },
        { id: 33, word: 'kišobran', translation: 'paraply' },
        { id: 34, word: 'lopov', translation: 'tjuv' },
        { id: 35, word: 'policajac', translation: 'polis' },
        { id: 36, word: 'učitelj', translation: 'lärare' },
        { id: 37, word: 'učenik', translation: 'elev' },
        { id: 38, word: 'liječnik', translation: 'läkare' },
        { id: 39, word: 'bolnica', translation: 'sjukhus' },
        { id: 40, word: 'trgovina', translation: 'affär' },
        { id: 41, word: 'novac', translation: 'pengar' },
        { id: 42, word: 'vrijeme', translation: 'tid' },
        { id: 43, word: 'pitanje', translation: 'fråga' },
        { id: 44, word: 'odgovor', translation: 'svar' },
        { id: 45, word: 'problem', translation: 'problem' }
      ],
      spelling: [
        { id: 1, sentence: 'Učiteljica nosi ___.', blank: 'naočale', options: ['naočale', 'naočare', 'naoćale'] },
        { id: 2, sentence: 'Na tanjuru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
        { id: 3, sentence: 'Djed nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
        { id: 4, sentence: 'U moru pliva velika ___.', blank: 'riba', options: ['riba', 'ripa', 'ribla'] },
        { id: 5, sentence: 'Idem u ___ spavati.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
        { id: 6, sentence: 'Imam novu ___.', blank: 'kuću', options: ['kuću', 'kuču', 'kucu'] },
        { id: 7, sentence: 'U vrtu raste crveni ___.', blank: 'cvijet', options: ['cvijet', 'cvjet', 'cvit'] },
        { id: 8, sentence: 'To je moj najbolji ___.', blank: 'prijatelj', options: ['prijatelj', 'prijatel', 'priatelj'] },
        { id: 9, sentence: 'Djevojčica ima dugu ___.', blank: 'kosu', options: ['kosu', 'košu', 'koso'] },
        { id: 10, sentence: 'Slon ima veliku ___.', blank: 'surlu', options: ['surlu', 'šurlu', 'survu'] },
        { id: 11, sentence: '___ ima osam nogu.', blank: 'Pauk', options: ['Pauk', 'Paukć', 'Ćpauk'] },
        { id: 12, sentence: 'Baka peče ukusan ___.', blank: 'kolač', options: ['kolač', 'kolać', 'kolac'] },
        { id: 13, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lishche', 'Lisce'] },
        { id: 14, sentence: '___ se igra s loptom.', blank: 'Dječak', options: ['Dječak', 'Dečak', 'Djećak'] },
        { id: 15, sentence: 'U ___ ima puno knjiga.', blank: 'knjižnici', options: ['biblioteci', 'knjižnici', 'knjižara'] },
        { id: 16, sentence: 'Djevojčica se igra u ___.', blank: 'pješčaniku', options: ['pješčaniku', 'pjesčaniku', 'pjesčaniku'] },
        { id: 17, sentence: 'On je moj ___.', blank: 'učenik', options: ['učenik', 'ućitelj', 'učenjak'] },
        { id: 18, sentence: 'Vani je prava ___.', blank: 'mećava', options: ['mećava', 'mečava', 'mećeva'] },
        { id: 19, sentence: 'Obukao je smeđi ___.', blank: 'džemper', options: ['džemper', 'đemper', 'demper'] },
        { id: 20, sentence: 'Ovo je ___ škola.', blank: 'dječja', options: ['dječja', 'diječja', 'dečja'] },
        { id: 21, sentence: 'U sobi je upaljena ___.', blank: 'svijeća', options: ['svijeća', 'sviječa', 'sveća'] },
        { id: 22, sentence: 'Boli me desno ___.', blank: 'rame', options: ['rame', 'ramje', 'ranje'] },
        { id: 23, sentence: 'Mačka prede u ___.', blank: 'krilu', options: ['krilu', 'krinju', 'krillu'] },
        { id: 24, sentence: 'U ___ se kuha kava.', blank: 'džezvi', options: ['džezvi', 'đezvi', 'djezvi'] }
      ],
      sentences: [
        { id: 1, sentence: 'Dječak čita knjigu.' },
        { id: 2, sentence: 'Djevojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na ploči.' },
        { id: 7, sentence: 'Djeca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sja svaki dan.' },
        { id: 9, sentence: 'Ja volim jesti sladoled.' },
        { id: 10, sentence: 'Moj tata vozi automobil.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Djed čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lijep dan.' },
        { id: 18, sentence: 'Snijeg pada zimi.' },
        { id: 19, sentence: 'Volim crtati cvijeće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' },
        { id: 21, sentence: 'Pijemo hladnu limunadu.' },
        { id: 22, sentence: 'Vlak putuje brzo.' },
        { id: 23, sentence: 'On ima novu igračku.' },
        { id: 24, sentence: 'Ona pjeva lijepu pjesmu.' },
        { id: 25, sentence: 'Idemo sutra na izlet.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa posvojna zamjenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'velik', options: ['velik', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (velik).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' }
      ],
      reading: [
        {
          id: 1,
          title: "Izlet u šumu",
          text: "Jednog sunčanog dana, Ana i njezin brat Luka su otišli na izlet u šumu s roditeljima. Ponijeli su košaru punu hrane. U šumi su vidjeli mnogo stabala i čuli cvrkut ptica. Luka je vidio vjevericu kako se penje uz stablo. Ana je brala šareno cvijeće. Nakon šetnje, sjeli su na deku i ručali. Bio je to divan dan.",
          questions: [
            { id: 1, question: "Tko je otišao na izlet?", options: ["Samo Ana", "Ana i Luka s roditeljima", "Samo Luka"], answer: "Ana i Luka s roditeljima" },
            { id: 2, question: "Što je Luka vidio u šumi?", options: ["Zeca", "Medvjeda", "Vjevericu"], answer: "Vjevericu" },
            { id: 3, question: "Što je Ana radila?", options: ["Pela se na stablo", "Brala cvijeće", "Spavala"], answer: "Brala cvijeće" },
            { id: 4, question: "Kakav je bio dan?", options: ["Kišovit", "Divan", "Hladan"], answer: "Divan" }
          ]
        },
        {
          id: 2,
          title: "Pas Piko",
          text: "Dječak po imenu Ivan ima psa koji se zove Piko. Piko je veliki žuti pas s dugim repom. Svaki dan, Ivan i Piko idu u park. Ivan baca lopticu, a Piko je donosi natrag. Piko voli se igrati i lajati na mačke. Navečer, Piko spava u svojoj kućici u dvorištu. Ivan mnogo voli svog psa.",
          questions: [
            { id: 1, question: "Kako se zove Ivanov pas?", options: ["Žućo", "Lajko", "Piko"], answer: "Piko" },
            { id: 2, question: "Gdje se Ivan i Piko igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
            { id: 3, question: "Što Ivan baca Piku?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
            { id: 4, question: "Gdje Piko spava?", options: ["U Ivanovom krevetu", "U svojoj kućici", "Na stablu"], answer: "U svojoj kućici" }
          ]
        }
      ],
      translations: [
        { id: 1, type: 'word', source: 'kaffe', target: 'kava' },
        { id: 2, type: 'word', source: 'bröd', target: 'kruh' },
        { id: 3, type: 'word', source: 'skola', target: 'škola' },
        { id: 4, type: 'word', source: 'hus', target: 'kuća' },
        { id: 5, type: 'word', source: 'bok', target: 'knjiga' },
        { id: 6, type: 'word', source: 'äpple', target: 'jabuka' },
        { id: 7, type: 'word', source: 'bil', target: 'automobil' },
        { id: 8, type: 'word', source: 'katt', target: 'mačka' },
        { id: 9, type: 'word', source: 'hund', target: 'pas' },
        { id: 10, type: 'word', source: 'boll', target: 'lopta' },
        { id: 11, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
        { id: 12, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Djevojčica jede jabuku.' },
        { id: 13, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 14, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 15, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi automobil.' },
      ]
    },
    '4-6': {
      alphabet: [],
      numbers: [],
      vocabulary: [
        { id: 201, word: 'zrakoplov', translation: 'flygplan' },
        { id: 202, word: 'tisuća', translation: 'tusen' },
        { id: 203, word: 'kruh', translation: 'bröd' },
        { id: 204, word: 'nogomet', translation: 'fotboll' },
        { id: 205, word: 'kolodvor', translation: 'tågstation' },
        { id: 206, word: 'povijest', translation: 'historia' },
        { id: 207, word: 'zemljopis', translation: 'geografi' },
        { id: 208, word: 'trg', translation: 'torg' },
        { id: 209, word: 'otok', translation: 'ö' },
        { id: 210, word: 'more', translation: 'hav' },
        { id: 211, word: 'planina', translation: 'berg' },
        { id: 212, word: 'juha', translation: 'soppa' },
        { id: 213, word: 'rajčica', translation: 'tomat' },
        { id: 214, word: 'hladnjak', translation: 'kylskåp' },
        { id: 215, word: 'računalo', translation: 'dator' },
        { id: 216, word: 'glačalo', translation: 'strykjärn' },
        { id: 217, word: 'kazalište', translation: 'teater' },
        { id: 218, word: 'glazba', translation: 'musik' },
        { id: 219, word: 'sport', translation: 'sport' },
        { id: 220, word: 'zdravlje', translation: 'hälsa' },
        { id: 221, word: 'obitelj', translation: 'familj' },
        { id: 222, word: 'prijateljstvo', translation: 'vänskap' },
        { id: 223, word: 'ljubav', translation: 'kärlek' },
        { id: 224, word: 'sreća', translation: 'lycka' },
        { id: 225, word: 'tuga', translation: 'sorg' },
        { id: 226, word: 'znanost', translation: 'vetenskap' },
        { id: 227, word: 'budućnost', translation: 'framtid' },
        { id: 228, word: 'prošlost', translation: 'dåtid' },
        { id: 229, word: 'sadašnjost', translation: 'nutid' },
        { id: 230, word: 'svijet', translation: 'värld' }
      ],
      spelling: [],
      sentences: [],
      grammar: [],
      reading: [],
      translations: []
    },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [], alphabet: [], numbers: [] },
  },
  serbian: {
    '1-3': {
      alphabet: alphabet,
      numbers: [
        { number: 0, word: "nula" },
        { number: 1, word: "jedan" },
        { number: 2, word: "dva" },
        { number: 3, word: "tri" },
        { number: 4, word: "četiri" },
        { number: 5, word: "pet" },
        { number: 6, word: "šest" },
        { number: 7, word: "sedam" },
        { number: 8, word: "osam" },
        { number: 9, word: "devet" },
        { number: 10, word: "deset" },
        { number: 11, word: "jedanaest" },
        { number: 12, word: "dvanaest" },
        { number: 13, word: "trinaest" },
        { number: 14, word: "četrnaest" },
        { number: 15, word: "petnaest" },
        { number: 16, word: "šesnaest" },
        { number: 17, word: "sedamnaest" },
        { number: 18, word: "osamnaest" },
        { number: 19, word: "devetnaest" },
        { number: 20, word: "dvadeset" },
        { number: 21, word: "dvadeset jedan" },
        { number: 22, word: "dvadeset dva" },
        { number: 23, word: "dvadeset tri" },
        { number: 24, word: "dvadeset četiri" },
        { number: 25, word: "dvadeset pet" },
        { number: 26, word: "dvadeset šest" },
        { number: 27, word: "dvadeset sedam" },
        { number: 28, word: "dvadeset osam" },
        { number: 29, word: "dvadeset devet" },
        { number: 30, word: "trideset" },
        { number: 40, word: "četrdeset" },
        { number: 50, word: "pedeset" },
        { number: 60, word: "šezdeset" },
        { number: 70, word: "sedamdeset" },
        { number: 80, word: "osamdeset" },
        { number: 90, word: "devedeset" },
        { number: 100, word: "sto" },
      ],
      vocabulary: [
        { id: 1, word: 'kafa', translation: 'kaffe' },
        { id: 2, word: 'hleb', translation: 'bröd' },
        { id: 3, word: 'škola', translation: 'skola' },
        { id: 4, word: 'kuća', translation: 'hus' },
        { id: 5, word: 'knjiga', translation: 'bok' },
        { id: 6, word: 'jabuka', translation: 'äpple' },
        { id: 7, word: 'auto', translation: 'bil' },
        { id: 8, word: 'mačka', translation: 'katt' },
        { id: 9, word: 'pas', translation: 'hund' },
        { id: 10, word: 'lopta', translation: 'boll' },
        { id: 11, word: 'sunce', translation: 'sol' },
        { id: 12, word: 'voda', translation: 'vatten' },
        { id: 13, word: 'stolica', translation: 'stol' },
        { id: 14, word: 'sat', translation: 'klocka' },
        { id: 15, word: 'most', translation: 'bro' },
        { id: 16, word: 'drvo', translation: 'träd' },
        { id: 17, word: 'cvet', translation: 'blomma' },
        { id: 18, word: 'prozor', translation: 'fönster' },
        { id: 19, word: 'vrata', translation: 'dörr' },
        { id: 20, word: 'nebo', translation: 'himmel' },
        { id: 21, word: 'trava', translation: 'gräs' },
        { id: 22, word: 'mleko', translation: 'mjölk' },
        { id: 23, word: 'šećer', translation: 'socker' },
        { id: 24, word: 'so', translation: 'salt' },
        { id: 25, word: 'drug', translation: 'vän' },
        { id: 26, word: 'avion', translation: 'flygplan' },
        { id: 27, word: 'bicikl', translation: 'cykel' },
        { id: 28, word: 'voz', translation: 'tåg' },
        { id: 29, word: 'brod', translation: 'båt' },
        { id: 30, word: 'krevet', translation: 'säng' }
      ],
      spelling: [
        { id: 1, sentence: 'Učiteljica nosi ___.', blank: 'naočare', options: ['naočale', 'naočare', 'naoćare'] },
        { id: 2, sentence: 'Na tanjiru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
        { id: 3, sentence: 'Deda nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
        { id: 4, sentence: 'Idem u ___ da spavam.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
        { id: 5, sentence: 'Imam novu ___.', blank: 'kuću', options: ['kuću', 'kuču', 'kucu'] },
        { id: 6, sentence: 'U bašti raste crveni ___.', blank: 'cvet', options: ['cvijet', 'cvet', 'cvit'] },
        { id: 7, sentence: 'To je moj najbolji ___.', blank: 'drug', options: ['drug', 'drugar', 'prijatelj'] },
        { id: 8, sentence: 'Devojčica ima dugu ___.', blank: 'kosu', options: ['kosu', 'košu', 'koso'] },
        { id: 9, sentence: 'Baka pravi ukusan ___.', blank: 'kolač', options: ['kolač', 'kolać', 'kolac'] },
        { id: 10, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lišče', 'Lisce'] },
        { id: 11, sentence: '___ se igra loptom.', blank: 'Dečak', options: ['Dječak', 'Dečak', 'Djećak'] },
        { id: 12, sentence: 'U ___ ima puno knjiga.', blank: 'biblioteci', options: ['biblioteci', 'knjižnici', 'knjižari'] },
        { id: 13, sentence: 'Danas je lep dan u ___.', blank: 'Beogradu', options: ['Beogradu', 'Beograd', 'Beogradom'] },
        { id: 14, sentence: 'U ___ se kuva kafa.', blank: 'džezvi', options: ['džezvi', 'đezvi', 'djezvi'] },
        { id: 15, sentence: 'Volim da jedem ___.', blank: 'đevrek', options: ['đevrek', 'đevrek', 'gevrek'] },
        { id: 16, sentence: 'On je moj ___.', blank: 'đak', options: ['đak', 'djak', 'džak'] },
        { id: 17, sentence: 'Napolju je prava ___.', blank: 'vejavica', options: ['mećava', 'vejavica', 'mećeva'] },
        { id: 18, sentence: 'Obukao je smeđi ___.', blank: 'džemper', options: ['džemper', 'đemper', 'demper'] },
        { id: 19, sentence: 'Ovo je ___ škola.', blank: 'dečja', options: ['dječja', 'diječja', 'dečja'] },
        { id: 20, sentence: 'U sobi je upaljena ___.', blank: 'sveća', options: ['svijeća', 'sviječa', 'sveća'] }
      ],
      sentences: [
        { id: 1, sentence: 'Dečak čita knjigu.' },
        { id: 2, sentence: 'Devojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na tabli.' },
        { id: 7, sentence: 'Deca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sija svaki dan.' },
        { id: 9, sentence: 'Ja volim da jedem sladoled.' },
        { id: 10, sentence: 'Moj tata vozi auto.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Deda čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lep dan.' },
        { id: 18, sentence: 'Sneg pada zimi.' },
        { id: 19, sentence: 'Volim da crtam cveće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dečak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekat u jednini (dečak) zahteva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Devojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekat u množini (devojčice) zahteva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridev mora biti u muškom rodu (veliki).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridev "crven" ima oblik "crvenu".' }
      ],
      reading: [
        {
          id: 1,
          title: "Izlet u šumu",
          text: "Jednog sunčanog dana, Jovana i njen brat Milan su otišli na izlet u šumu sa roditeljima. Poneli su korpu punu hrane. U šumi su videli mnogo drveća i čuli cvrkut ptica. Milan je video vevericu kako se penje uz drvo. Jovana je brala šareno cveće. Posle šetnje, seli su na ćebe i ručali. Bio je to divan dan.",
          questions: [
            { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Jovana", "Jovana i Milan sa roditeljima", "Samo Milan"], answer: "Jovana i Milan sa roditeljima" },
            { id: 2, question: "Šta je Milan video u šumi?", options: ["Zeca", "Medveda", "Vevericu"], answer: "Vevericu" },
            { id: 3, question: "Šta je Jovana radila?", options: ["Pela se na drvo", "Brala cveće", "Spavala"], answer: "Brala cveće" },
            { id: 4, question: "Kakav je bio dan?", options: ["Kišovit", "Divan", "Hladan"], answer: "Divan" }
          ]
        },
        {
          id: 2,
          title: "Pas Žuća",
          text: "Dečak po imenu Nikola ima psa koji se zove Žuća. Žuća je veliki žuti pas sa dugim repom. Svaki dan, Nikola i Žuća idu u park. Nikola baca lopticu, a Žuća je donosi nazad. Žuća voli da se igra i da laje na mačke. Uveče, Žuća spava u svojoj kućici u dvorištu. Nikola mnogo voli svog psa.",
          questions: [
            { id: 1, question: "Kako se zove Nikolin pas?", options: ["Šarko", "Lajko", "Žuća"], answer: "Žuća" },
            { id: 2, question: "Gde se Nikola i Žuća igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
            { id: 3, question: "Šta Nikola baca Žući?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
            { id: 4, question: "Gde Žuća spava?", options: ["U Nikolinom krevetu", "U svojoj kućici", "Na drvetu"], answer: "U svojoj kućici" }
          ]
        }
      ],
      translations: [
        { id: 1, type: 'word', source: 'kaffe', target: 'kafa' },
        { id: 2, type: 'word', source: 'bröd', target: 'hleb' },
        { id: 3, type: 'word', source: 'skola', target: 'škola' },
        { id: 4, type: 'word', source: 'hus', target: 'kuća' },
        { id: 5, type: 'word', source: 'bok', target: 'knjiga' },
        { id: 6, type: 'word', source: 'äpple', target: 'jabuka' },
        { id: 7, type: 'word', source: 'bil', target: 'auto' },
        { id: 8, type: 'word', source: 'katt', target: 'mačka' },
        { id: 9, type: 'word', source: 'hund', target: 'pas' },
        { id: 10, type: 'word', source: 'boll', target: 'lopta' },
        { id: 11, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dečak čita knjigu.' },
        { id: 12, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Devojčica jede jabuku.' },
        { id: 13, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 14, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 15, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi auto.' }
      ]
    },
    '4-6': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [], alphabet: [], numbers: [] },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [], alphabet: [], numbers: [] },
  },
};

    
    
