import type { LanguageData } from './types';

export const data: LanguageData = {
  bosnian: {
    '1-3': {
      vocabulary: [
        { id: 1, word: 'kahva', translation: 'kaffe', image: 'https://picsum.photos/400/400?image=1060', audio: '', 'data-ai-hint': 'coffee cup' },
        { id: 2, word: 'škola', translation: 'skola', image: 'https://picsum.photos/400/400?image=211', audio: '', 'data-ai-hint': 'school building' },
        { id: 3, word: 'kuća', translation: 'hus', image: 'https://picsum.photos/400/400?image=1011', audio: '', 'data-ai-hint': 'house exterior' },
        { id: 4, word: 'knjiga', translation: 'bok', image: 'https://picsum.photos/400/400?image=24', audio: '', 'data-ai-hint': 'open book' },
        { id: 5, word: 'jabuka', translation: 'äpple', image: 'https://picsum.photos/400/400?image=1080', audio: '', 'data-ai-hint': 'red apple' },
        { id: 6, word: 'auto', translation: 'bil', image: 'https://picsum.photos/400/400?image=1074', audio: '', 'data-ai-hint': 'modern car' },
        { id: 7, word: 'mačka', translation: 'katt', image: 'https://picsum.photos/400/400?image=219', audio: '', 'data-ai-hint': 'cute cat' },
        { id: 8, word: 'pas', translation: 'hund', image: 'https://picsum.photos/400/400?image=233', audio: '', 'data-ai-hint': 'happy dog' },
        { id: 9, word: 'lopta', translation: 'boll', image: 'https://picsum.photos/400/400?image=433', audio: '', 'data-ai-hint': 'soccer ball' },
        { id: 10, word: 'sunce', translation: 'sol', image: 'https://picsum.photos/400/400?image=13', audio: '', 'data-ai-hint': 'bright sun' },
        { id: 11, word: 'voda', translation: 'vatten', image: 'https://picsum.photos/400/400?image=1015', audio: '', 'data-ai-hint': 'clear water' },
        { id: 12, word: 'stolica', translation: 'stol', image: 'https://picsum.photos/400/400?image=835', audio: '', 'data-ai-hint': 'wooden chair' },
        { id: 13, word: 'sat', translation: 'klocka', image: 'https://picsum.photos/400/400?image=20', audio: '', 'data-ai-hint': 'wall clock' },
        { id: 14, word: 'most', translation: 'bro', image: 'https://picsum.photos/400/400?image=1039', audio: '', 'data-ai-hint': 'old bridge' },
        { id: 15, word: 'drvo', translation: 'träd', image: 'https://picsum.photos/400/400?image=1041', audio: '', 'data-ai-hint': 'green tree' },
        { id: 16, word: 'cvijet', translation: 'blomma', image: 'https://picsum.photos/400/400?image=1084', audio: '', 'data-ai-hint': 'yellow flower' },
        { id: 17, word: 'prozor', translation: 'fönster', image: 'https://picsum.photos/400/400?image=1013', audio: '', 'data-ai-hint': 'window view' },
        { id: 18, word: 'vrata', translation: 'dörr', image: 'https://picsum.photos/400/400?image=1072', audio: '', 'data-ai-hint': 'wooden door' },
        { id: 19, word: 'nebo', translation: 'himmel', image: 'https://picsum.photos/400/400?image=1018', audio: '', 'data-ai-hint': 'blue sky' },
        { id: 20, word: 'trava', translation: 'gräs', image: 'https://picsum.photos/400/400?image=1053', audio: '', 'data-ai-hint': 'green grass' },
        { id: 21, word: 'hljeb', translation: 'bröd', image: 'https://picsum.photos/400/400?image=355', audio: '', 'data-ai-hint': 'loaf bread' },
        { id: 22, word: 'mlijeko', translation: 'mjölk', image: 'https://picsum.photos/400/400?image=789', audio: '', 'data-ai-hint': 'glass milk' },
        { id: 23, word: 'šećer', translation: 'socker', image: 'https://picsum.photos/400/400?image=606', audio: '', 'data-ai-hint': 'sugar cubes' },
        { id: 24, word: 'so', translation: 'salt', image: 'https://picsum.photos/400/400?image=292', audio: '', 'data-ai-hint': 'salt shaker' },
        { id: 25, word: 'prijatelj', translation: 'vän', image: 'https://picsum.photos/400/400?image=836', audio: '', 'data-ai-hint': 'two friends' },
      ],
      spelling: [
        { id: 1, sentence: 'Moja mama pije ___.', blank: 'kahvu', options: ['stolicu', 'kahvu', 'lopatom'] },
        { id: 2, sentence: 'Idem u ___.', blank: 'školu', options: ['školu', 'oblak', 'drvetom'] },
        { id: 3, sentence: 'Ovo je moja ___.', blank: 'kuća', options: ['nebo', 'sreća', 'kuća'] },
        { id: 4, sentence: 'Čitam ___.', blank: 'knjigu', options: ['knjigu', 'staklo', 'zidom'] },
        { id: 5, sentence: 'Jedem ___.', blank: 'jabuku', options: ['kamen', 'jabuku', 'cipelom'] },
      ],
      sentences: [
        { id: 1, sentence: 'Dječak čita knjigu.' },
        { id: 2, sentence: 'Djevojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na tabli.' },
        { id: 7, sentence: 'Djeca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sija svaki dan.' },
        { id: 9, sentence: 'Ja volim jesti sladoled.' },
        { id: 10, sentence: 'Moj tata vozi auto.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Djed čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lijep dan.' },
        { id: 18, sentence: 'Snijeg pada zimi.' },
        { id: 19, sentence: 'Volim crtati cvijeće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' },
        { id: 21, sentence: 'Pijemo hladnu limunadu.' },
        { id: 22, sentence: 'Voz putuje brzo.' },
        { id: 23, sentence: 'On ima novu igračku.' },
        { id: 24, sentence: 'Ona pjeva lijepu pjesmu.' },
        { id: 25, sentence: 'Idemo na izlet sutra.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamjenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (veliki).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' }
      ],
      reading: [
        {
          id: 1,
          title: "Izlet u šumu",
          text: "Jednog sunčanog dana, Ana i njen brat Marko su otišli na izlet u šumu sa roditeljima. Ponijeli su korpu punu hrane. U šumi su vidjeli mnogo drveća i čuli cvrkut ptica. Marko je vidio vjevericu kako se penje uz drvo. Ana je brala šareno cvijeće. Nakon šetnje, sjeli su na deku i ručali. Bio je to divan dan.",
          questions: [
            { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Ana", "Ana i Marko sa roditeljima", "Samo Marko"], answer: "Ana i Marko sa roditeljima" },
            { id: 2, question: "Šta je Marko vidio u šumi?", options: ["Zeca", "Medvjeda", "Vjevericu"], answer: "Vjevericu" },
            { id: 3, question: "Šta je Ana radila?", options: ["Pela se na drvo", "Brala cvijeće", "Spavala"], answer: "Brala cvijeće" },
            { id: 4, question: "Kakav je bio dan?", options: ["Kišovit", "Divan", "Hladan"], answer: "Divan" }
          ]
        },
        {
          id: 2,
          title: "Pas Medo",
          text: "Dječak po imenu Emir ima psa koji se zove Medo. Medo je veliki žuti pas sa dugim repom. Svaki dan, Emir i Medo idu u park. Emir baca lopticu, a Medo je donosi nazad. Medo voli da se igra i da laje na mačke. Navečer, Medo spava u svojoj kućici u dvorištu. Emir mnogo voli svog psa.",
          questions: [
            { id: 1, question: "Kako se zove Emirov pas?", options: ["Žućo", "Lajko", "Medo"], answer: "Medo" },
            { id: 2, question: "Gdje se Emir i Medo igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
            { id: 3, question: "Šta Emir baca Medi?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
            { id: 4, question: "Gdje Medo spava?", options: ["U Emirovom krevetu", "U svojoj kućici", "Na drvetu"], answer: "U svojoj kućici" }
          ]
        }
      ],
      translations: [
        { id: 1, type: 'word', source: 'kaffe', target: 'kahva' },
        { id: 2, type: 'word', source: 'skola', target: 'škola' },
        { id: 3, type: 'word', source: 'hus', target: 'kuća' },
        { id: 4, type: 'word', source: 'bok', target: 'knjiga' },
        { id: 5, type: 'word', source: 'äpple', target: 'jabuka' },
        { id: 6, type: 'word', source: 'bil', target: 'auto' },
        { id: 7, type: 'word', source: 'katt', target: 'mačka' },
        { id: 8, type: 'word', source: 'hund', target: 'pas' },
        { id: 9, type: 'word', source: 'boll', target: 'lopta' },
        { id: 10, type: 'word', source: 'sol', target: 'sunce' },
        { id: 11, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
        { id: 12, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Djevojčica jede jabuku.' },
        { id: 13, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 14, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 15, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi auto.' },
      ]
    },
    '4-6': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
  },
  croatian: {
    '1-3': {
      vocabulary: [
        { id: 1, word: 'kruh', translation: 'bröd', image: 'https://picsum.photos/400/400?image=355', audio: '', 'data-ai-hint': 'sliced bread' },
        { id: 2, word: 'tisuća', translation: 'tusen', image: 'https://picsum.photos/400/400?image=175', audio: '', 'data-ai-hint': 'stack money' },
        { id: 3, word: 'obitelj', translation: 'familj', image: 'https://picsum.photos/400/400?image=834', audio: '', 'data-ai-hint': 'happy family' },
        { id: 4, word: 'more', translation: 'hav', image: 'https://picsum.photos/400/400?image=1015', audio: '', 'data-ai-hint': 'ocean waves' },
        { id: 5, word: 'grad', translation: 'stad', image: 'https://picsum.photos/400/400?image=1075', audio: '', 'data-ai-hint': 'city skyline' },
        { id: 6, word: 'mačka', translation: 'katt', image: 'https://picsum.photos/400/400?image=219', audio: '', 'data-ai-hint': 'cute cat' },
        { id: 7, word: 'pas', translation: 'hund', image: 'https://picsum.photos/400/400?image=233', audio: '', 'data-ai-hint': 'happy dog' },
        { id: 8, word: 'knjiga', translation: 'bok', image: 'https://picsum.photos/400/400?image=24', audio: '', 'data-ai-hint': 'open book' },
        { id: 9, word: 'jabuka', translation: 'äpple', image: 'https://picsum.photos/400/400?image=1080', audio: '', 'data-ai-hint': 'red apple' },
        { id: 10, word: 'kuća', translation: 'hus', image: 'https://picsum.photos/400/400?image=1011', audio: '', 'data-ai-hint': 'house exterior' },
        { id: 11, word: 'stablo', translation: 'träd', image: 'https://picsum.photos/400/400?image=1041', audio: '', 'data-ai-hint': 'green tree' },
        { id: 12, word: 'cvijet', translation: 'blomma', image: 'https://picsum.photos/400/400?image=1084', audio: '', 'data-ai-hint': 'yellow flower' },
        { id: 13, word: 'prozor', translation: 'fönster', image: 'https://picsum.photos/400/400?image=1013', audio: '', 'data-ai-hint': 'window view' },
        { id: 14, word: 'vrata', translation: 'dörr', image: 'https://picsum.photos/400/400?image=1072', audio: '', 'data-ai-hint': 'wooden door' },
        { id: 15, word: 'nebo', translation: 'himmel', image: 'https://picsum.photos/400/400?image=1018', audio: '', 'data-ai-hint': 'blue sky' },
        { id: 16, word: 'trava', translation: 'gräs', image: 'https://picsum.photos/400/400?image=1053', audio: '', 'data-ai-hint': 'green grass' },
        { id: 17, word: 'mlijeko', translation: 'mjölk', image: 'https://picsum.photos/400/400?image=789', audio: '', 'data-ai-hint': 'glass milk' },
        { id: 18, word: 'šećer', translation: 'socker', image: 'https://picsum.photos/400/400?image=606', audio: '', 'data-ai-hint': 'sugar cubes' },
        { id: 19, word: 'sol', translation: 'salt', image: 'https://picsum.photos/400/400?image=292', audio: '', 'data-ai-hint': 'salt shaker' },
        { id: 20, word: 'prijatelj', translation: 'vän', image: 'https://picsum.photos/400/400?image=836', audio: '', 'data-ai-hint': 'two friends' },
      ],
      spelling: [
        { id: 1, sentence: 'Jedem svježi ___.', blank: 'kruh', options: ['jastuk', 'kruh', 'ključ'] },
        { id: 2, sentence: 'Brojimo do ___.', blank: 'tisuću', options: ['trava', 'tisuću', 'zvijezda'] },
      ],
      sentences: [
        { id: 1, sentence: 'Dječak čita knjigu.' },
        { id: 2, sentence: 'Djevojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na ploči.' },
        { id: 7, sentence: 'Djeca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sja svaki dan.' },
        { id: 9, sentence: 'Ja volim jesti sladoled.' },
        { id: 10, sentence: 'Moj tata vozi automobil.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Djed čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lijep dan.' },
        { id: 18, sentence: 'Snijeg pada zimi.' },
        { id: 19, sentence: 'Volim crtati cvijeće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' },
        { id: 21, sentence: 'Pijemo hladnu limunadu.' },
        { id: 22, sentence: 'Vlak putuje brzo.' },
        { id: 23, sentence: 'On ima novu igračku.' },
        { id: 24, sentence: 'Ona pjeva lijepu pjesmu.' },
        { id: 25, sentence: 'Idemo sutra na izlet.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa posvojna zamjenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'velik', options: ['velik', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (velik).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' }
      ],
      reading: [],
      translations: [
        { id: 1, type: 'word', source: 'bröd', target: 'kruh' },
        { id: 2, type: 'word', source: 'tusen', target: 'tisuća' },
        { id: 3, type: 'word', source: 'familj', target: 'obitelj' },
        { id: 4, type: 'word', source: 'hav', target: 'more' },
        { id: 5, type: 'word', source: 'stad', target: 'grad' },
        { id: 6, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
        { id: 7, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Djevojčica jede jabuku.' },
        { id: 8, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 9, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 10, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi automobil.' },
      ]
    },
    '4-6': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
  },
  serbian: {
    '1-3': {
      vocabulary: [
        { id: 1, word: 'hleb', translation: 'bröd', image: 'https://picsum.photos/400/400?image=355', audio: '', 'data-ai-hint': 'loaf bread' },
        { id: 2, word: 'hiljada', translation: 'tusen', image: 'https://picsum.photos/400/400?image=175', audio: '', 'data-ai-hint': 'counting money' },
        { id: 3, word: 'porodica', translation: 'familj', image: 'https://picsum.photos/400/400?image=834', audio: '', 'data-ai-hint': 'family portrait' },
        { id: 4, word: 'reka', translation: 'flod', image: 'https://picsum.photos/400/400?image=1016', audio: '', 'data-ai-hint': 'calm river' },
        { id: 5, word: 'selo', translation: 'by', image: 'https://picsum.photos/400/400?image=1028', audio: '', 'data-ai-hint': 'small village' },
        { id: 6, word: 'kafa', translation: 'kaffe', image: 'https://picsum.photos/400/400?image=1060', audio: '', 'data-ai-hint': 'coffee cup' },
        { id: 7, word: 'škola', translation: 'skola', image: 'https://picsum.photos/400/400?image=211', audio: '', 'data-ai-hint': 'school building' },
        { id: 8, word: 'kuća', translation: 'hus', image: 'https://picsum.photos/400/400?image=1011', audio: '', 'data-ai-hint': 'house exterior' },
        { id: 9, word: 'knjiga', translation: 'bok', image: 'https://picsum.photos/400/400?image=24', audio: '', 'data-ai-hint': 'open book' },
        { id: 10, word: 'jabuka', translation: 'äpple', image: 'https://picsum.photos/400/400?image=1080', audio: '', 'data-ai-hint': 'red apple' },
        { id: 11, word: 'voda', translation: 'vatten', image: 'https://picsum.photos/400/400?image=1015', audio: '', 'data-ai-hint': 'clear water' },
        { id: 12, word: 'stolica', translation: 'stol', image: 'https://picsum.photos/400/400?image=835', audio: '', 'data-ai-hint': 'wooden chair' },
        { id: 13, word: 'drvo', translation: 'träd', image: 'https://picsum.photos/400/400?image=1041', audio: '', 'data-ai-hint': 'green tree' },
        { id: 14, word: 'cvet', translation: 'blomma', image: 'https://picsum.photos/400/400?image=1084', audio: '', 'data-ai-hint': 'yellow flower' },
        { id: 15, word: 'prozor', translation: 'fönster', image: 'https://picsum.photos/400/400?image=1013', audio: '', 'data-ai-hint': 'window view' },
        { id: 16, word: 'vrata', translation: 'dörr', image: 'https://picsum.photos/400/400?image=1072', audio: '', 'data-ai-hint': 'wooden door' },
        { id: 17, word: 'nebo', translation: 'himmel', image: 'https://picsum.photos/400/400?image=1018', audio: '', 'data-ai-hint': 'blue sky' },
        { id: 18, word: 'trava', translation: 'gräs', image: 'https://picsum.photos/400/400?image=1053', audio: '', 'data-ai-hint': 'green grass' },
        { id: 19, word: 'mleko', translation: 'mjölk', image: 'https://picsum.photos/400/400?image=789', audio: '', 'data-ai-hint': 'glass milk' },
        { id: 20, word: 'šećer', translation: 'socker', image: 'https://picsum.photos/400/400?image=606', audio: '', 'data-ai-hint': 'sugar cubes' },
        { id: 21, word: 'so', translation: 'salt', image: 'https://picsum.photos/400/400?image=292', audio: '', 'data-ai-hint': 'salt shaker' },
        { id: 22, word: 'drug', translation: 'vän', image: 'https://picsum.photos/400/400?image=836', audio: '', 'data-ai-hint': 'two friends' },
      ],
      spelling: [
        { id: 1, sentence: 'Kupio sam ___.', blank: 'hleb', options: ['mesec', 'hleb', 'svesku'] },
        { id: 2, sentence: 'Imam ___ dinara.', blank: 'hiljadu', options: ['pesmu', 'hiljadu', 'olovku'] },
      ],
      sentences: [
        { id: 1, sentence: 'Dečak čita knjigu.' },
        { id: 2, sentence: 'Devojčica jede jabuku.' },
        { id: 3, sentence: 'Pas trči brzo.' },
        { id: 4, sentence: 'Mačka spava na suncu.' },
        { id: 5, sentence: 'Mi idemo u školu.' },
        { id: 6, sentence: 'Učiteljica piše na tabli.' },
        { id: 7, sentence: 'Deca se igraju u parku.' },
        { id: 8, sentence: 'Sunce sija svaki dan.' },
        { id: 9, sentence: 'Ja volim da jedem sladoled.' },
        { id: 10, sentence: 'Moj tata vozi auto.' },
        { id: 11, sentence: 'Moja sestra ima lutku.' },
        { id: 12, sentence: 'Oni gledaju crtani film.' },
        { id: 13, sentence: 'Baka plete topli džemper.' },
        { id: 14, sentence: 'Deda čita novine.' },
        { id: 15, sentence: 'Ptica leti visoko na nebu.' },
        { id: 16, sentence: 'Riba pliva u vodi.' },
        { id: 17, sentence: 'Danas je lep dan.' },
        { id: 18, sentence: 'Sneg pada zimi.' },
        { id: 19, sentence: 'Volim da crtam cveće.' },
        { id: 20, sentence: 'Moja lopta je crvena.' },
        { id: 21, sentence: 'Pijemo hladnu limunadu.' },
        { id: 22, sentence: 'Voz putuje brzo.' },
        { id: 23, sentence: 'On ima novu igračku.' },
        { id: 24, sentence: 'Ona peva lepu pesmu.' },
        { id: 25, sentence: 'Idemo sutra na izlet.' }
      ],
      grammar: [
        { id: 1, sentence: 'Dečak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekat u jednini (dečak) zahteva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Devojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekat u množini (devojčice) zahteva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridev mora biti u muškom rodu (veliki).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridev "crven" ima oblik "crvenu".' }
      ],
      reading: [
        {
          id: 1,
          title: "Izlet u šumu",
          text: "Jednog sunčanog dana, Ana i njen brat Marko su otišli na izlet u šumu sa roditeljima. Poneli su korpu punu hrane. U šumi su videli mnogo drveća i čuli cvrkut ptica. Marko je video vevericu kako se penje uz drvo. Ana je brala šareno cveće. Posle šetnje, seli su na ćebe i ručali. Bio je to divan dan.",
          questions: [
            { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Ana", "Ana i Marko sa roditeljima", "Samo Marko"], answer: "Ana i Marko sa roditeljima" },
            { id: 2, question: "Šta je Marko video u šumi?", options: ["Zeca", "Medveda", "Vevericu"], answer: "Vevericu" },
            { id: 3, question: "Šta je Ana radila?", options: ["Pela se na drvo", "Brala cveće", "Spavala"], answer: "Brala cveće" },
            { id: 4, question: "Kakav je bio dan?", options: ["Kišovit", "Divan", "Hladan"], answer: "Divan" }
          ]
        },
        {
          id: 2,
          title: "Pas Žuća",
          text: "Dečak po imenu Milan ima psa koji se zove Žuća. Žuća je veliki žuti pas sa dugim repom. Svaki dan, Milan i Žuća idu u park. Milan baca lopticu, a Žuća je donosi nazad. Žuća voli da se igra i da laje na mačke. Uveče, Žuća spava u svojoj kućici u dvorištu. Milan mnogo voli svog psa.",
          questions: [
            { id: 1, question: "Kako se zove Milanov pas?", options: ["Šare", "Lajko", "Žuća"], answer: "Žuća" },
            { id: 2, question: "Gde se Milan i Žuća igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
            { id: 3, question: "Šta Milan baca Žući?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
            { id: 4, question: "Gde Žuća spava?", options: ["U Milanovom krevetu", "U svojoj kućici", "Na drvetu"], answer: "U svojoj kućici" }
          ]
        }
      ],
      translations: [
        { id: 1, type: 'word', source: 'bröd', target: 'hleb' },
        { id: 2, type: 'word', source: 'tusen', target: 'hiljada' },
        { id: 3, type: 'word', source: 'familj', target: 'porodica' },
        { id: 4, type: 'word', source: 'flod', target: 'reka' },
        { id: 5, type: 'word', source: 'by', target: 'selo' },
        { id: 6, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dečak čita knjigu.' },
        { id: 7, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Devojčica jede jabuku.' },
        { id: 8, type: 'sentence', source: 'Hunden springer snabbt.', target: 'Pas trči brzo.' },
        { id: 9, type: 'sentence', source: 'Vi går till skolan.', target: 'Mi idemo u školu.' },
        { id: 10, type: 'sentence', source: 'Min pappa kör bilen.', target: 'Moj tata vozi auto.' },
      ]
    },
    '4-6': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
    '7-9': { vocabulary: [], spelling: [], sentences: [], grammar: [], reading: [], translations: [] },
  },
};
