
import type { LanguageData } from './types';

const bosnianAlphabet = [
    { letter: ['A', 'a'], exampleWord: 'Avion' },
    { letter: ['B', 'b'], exampleWord: 'Bicikl' },
    { letter: ['C', 'c'], exampleWord: 'Cipele' },
    { letter: ['Č', 'č'], exampleWord: 'Čaša' },
    { letter: ['Ć', 'ć'], exampleWord: 'Ćevapi' },
    { letter: ['D', 'd'], exampleWord: 'Drvo' },
    { letter: ['Dž', 'dž'], exampleWord: 'Džep' },
    { letter: ['Đ', 'đ'], exampleWord: 'Đak' },
    { letter: ['E', 'e'], exampleWord: 'Ekran' },
    { letter: ['F', 'f'], exampleWord: 'Fudbal' },
    { letter: ['G', 'g'], exampleWord: 'Gitara' },
    { letter: ['H', 'h'], exampleWord: 'Haljina' },
    { letter: ['I', 'i'], exampleWord: 'Igla' },
    { letter: ['J', 'j'], exampleWord: 'Jabuka' },
    { letter: ['K', 'k'], exampleWord: 'Knjiga' },
    { letter: ['L', 'l'], exampleWord: 'Lopta' },
    { letter: ['Lj', 'lj'], exampleWord: 'Ljubav' },
    { letter: ['M', 'm'], exampleWord: 'Mačka' },
    { letter: ['N', 'n'], exampleWord: 'Noga' },
    { letter: ['Nj', 'nj'], exampleWord: 'Njiva' },
    { letter: ['O', 'o'], exampleWord: 'Oblak' },
    { letter: ['P', 'p'], exampleWord: 'Pas' },
    { letter: ['R', 'r'], exampleWord: 'Riba' },
    { letter: ['S', 's'], exampleWord: 'Sunce' },
    { letter: ['Š', 'š'], exampleWord: 'Šuma' },
    { letter: ['T', 't'], exampleWord: 'Trava' },
    { letter: ['U', 'u'], exampleWord: 'Uho' },
    { letter: ['V', 'v'], exampleWord: 'Voda' },
    { letter: ['Z', 'z'], exampleWord: 'Zebra' },
    { letter: ['Ž', 'ž'], exampleWord: 'Žaba' },
];

const croatianAlphabet = [
    { letter: ['A', 'a'], exampleWord: 'Auto' },
    { letter: ['B', 'b'], exampleWord: 'Brod' },
    { letter: ['C', 'c'], exampleWord: 'Cesta' },
    { letter: ['Č', 'č'], exampleWord: 'Čamac' },
    { letter: ['Ć', 'ć'], exampleWord: 'Ćuk' },
    { letter: ['D', 'd'], exampleWord: 'Daska' },
    { letter: ['Dž', 'dž'], exampleWord: 'Džungla' },
    { letter: ['Đ', 'đ'], exampleWord: 'Đak' },
    { letter: ['E', 'e'], exampleWord: 'Europa' },
    { letter: ['F', 'f'], exampleWord: 'Fotografija' },
    { letter: ['G', 'g'], exampleWord: 'Glazba' },
    { letter: ['H', 'h'], exampleWord: 'Hlače' },
    { letter: ['I', 'i'], exampleWord: 'Igračka' },
    { letter: ['J', 'j'], exampleWord: 'Jastuk' },
    { letter: ['K', 'k'], exampleWord: 'Kruh' },
    { letter: ['L', 'l'], exampleWord: 'Ljeto' },
    { letter: ['Lj', 'lj'], exampleWord: 'Ljubav' },
    { letter: ['M', 'm'], exampleWord: 'More' },
    { letter: ['N', 'n'], exampleWord: 'Nogomet' },
    { letter: ['Nj', 'nj'], exampleWord: 'Njuh' },
    { letter: ['O', 'o'], exampleWord: 'Otok' },
    { letter: ['P', 'p'], exampleWord: 'Povijest' },
    { letter: ['R', 'r'], exampleWord: 'Ruka' },
    { letter: ['S', 's'], exampleWord: 'Stol' },
    { letter: ['Š', 'š'], exampleWord: 'Šešir' },
    { letter: ['T', 't'], exampleWord: 'Tisuća' },
    { letter: ['U', 'u'], exampleWord: 'Učenik' },
    { letter: ['V', 'v'], exampleWord: 'Vlak' },
    { letter: ['Z', 'z'], exampleWord: 'Zima' },
    { letter: ['Ž', 'ž'], exampleWord: 'Žlica' },
];

const serbianAlphabet = [
    { letter: ['A', 'a'], exampleWord: 'Avion' },
    { letter: ['B', 'b'], exampleWord: 'Bicikl' },
    { letter: ['V', 'v'], exampleWord: 'Voz' },
    { letter: ['G', 'g'], exampleWord: 'Grad' },
    { letter: ['D', 'd'], exampleWord: 'Drvo' },
    { letter: ['Đ', 'đ'], exampleWord: 'Đak' },
    { letter: ['E', 'e'], exampleWord: 'Evropa' },
    { letter: ['Ž', 'ž'], exampleWord: 'Žaba' },
    { letter: ['Z', 'z'], exampleWord: 'Zebra' },
    { letter: ['I', 'i'], exampleWord: 'Istorija' },
    { letter: ['J', 'j'], exampleWord: 'Jabuka' },
    { letter: ['K', 'k'], exampleWord: 'Knjiga' },
    { letter: ['L', 'l'], exampleWord: 'Lopta' },
    { letter: ['Lj', 'lj'], exampleWord: 'Ljubav' },
    { letter: ['M', 'm'], exampleWord: 'Mačka' },
    { letter: ['N', 'n'], exampleWord: 'Noga' },
    { letter: ['Nj', 'nj'], exampleWord: 'Njiva' },
    { letter: ['O', 'o'], exampleWord: 'Oblak' },
    { letter: ['P', 'p'], exampleWord: 'Pas' },
    { letter: ['R', 'r'], exampleWord: 'Riba' },
    { letter: ['S', 's'], exampleWord: 'Sunce' },
    { letter: ['T', 't'], exampleWord: 'Trava' },
    { letter: ['Ć', 'ć'], exampleWord: 'Ćuran' },
    { letter: ['U', 'u'], exampleWord: 'Uvo' },
    { letter: ['F', 'f'], exampleWord: 'Fudbal' },
    { letter: ['H', 'h'], exampleWord: 'Hleb' },
    { letter: ['C', 'c'], exampleWord: 'Cipele' },
    { letter: ['Č', 'č'], exampleWord: 'Čaša' },
    { letter: ['Dž', 'dž'], exampleWord: 'Džak' },
    { letter: ['Š', 'š'], exampleWord: 'Škola' },
];

const numbers = [
    { number: 0, word: "nula", ordinal: "nulti" },
    { number: 1, word: "jedan", ordinal: "prvi" },
    { number: 2, word: "dva", ordinal: "drugi" },
    { number: 3, word: "tri", ordinal: "treći" },
    { number: 4, word: "četiri", ordinal: "četvrti" },
    { number: 5, word: "pet", ordinal: "peti" },
    { number: 6, word: "šest", ordinal: "šesti" },
    { number: 7, word: "sedam", ordinal: "sedmi" },
    { number: 8, word: "osam", ordinal: "osmi" },
    { number: 9, word: "devet", ordinal: "deveti" },
    { number: 10, word: "deset", ordinal: "deseti" },
    { number: 11, word: "jedanaest", ordinal: "jedanaesti" },
    { number: 12, word: "dvanaest", ordinal: "dvanaesti" },
    { number: 13, word: "trinaest", ordinal: "trinaesti" },
    { number: 14, word: "četrnaest", ordinal: "četrnaesti" },
    { number: 15, word: "petnaest", ordinal: "petnaesti" },
    { number: 16, word: "šesnaest", ordinal: "šesnaesti" },
    { number: 17, word: "sedamnaest", ordinal: "sedamnaesti" },
    { number: 18, word: "osamnaest", ordinal: "osamnaesti" },
    { number: 19, word: "devetnaest", ordinal: "devetnaesti" },
    { number: 20, word: "dvadeset", ordinal: "dvadeseti" },
    { number: 21, word: "dvadeset jedan", ordinal: "dvadeset prvi" },
    { number: 30, word: "trideset", ordinal: "trideseti" },
    { number: 40, word: "četrdeset", ordinal: "četrdeseti" },
    { number: 50, word: "pedeset", ordinal: "pedeseti" },
    { number: 60, word: "šezdeset", ordinal: "šezdeseti" },
    { number: 70, word: "sedamdeset", ordinal: "sedamdeseti" },
    { number: 80, word: "osamdeset", ordinal: "osamdeseti" },
    { number: 90, word: "devedeset", ordinal: "devedeseti" },
    { number: 100, word: "sto", ordinal: "stoti" },
    { number: 1000, word: "hiljada", ordinal: "hiljaditi" },
];

const croatianNumbers = numbers.map(n => {
    if (n.word === "hiljada") return {...n, word: "tisuća", ordinal: "tisućiti" };
    return n;
});

const serbianNumbers = numbers.map(n => {
    if (n.word === "hiljada") return {...n, word: "hiljada", ordinal: "hiljaditi" };
    return n;
});

const alphabetWordsBosnian = [
  { letter: "A", words: ["auto", "avion", "apoteka", "ananas", "april", "adresa", "alat", "arhitekta", "Afrika", "Amerika"] },
  { letter: "B", words: ["brod", "banana", "beba", "bicikl", "bijela", "balon", "bombon", "brat", "baka", "bazen"] },
  { letter: "C", words: ["cipela", "cesta", "crvena", "cvijet", "cirkus", "car", "crtani", "cijena", "centar", "cimet"] },
  { letter: "Č", words: ["čaša", "čekić", "čokolada", "čarapa", "četka", "čamac", "čovjek", "čelo", "čitati", "četvrtak"] },
  { letter: "Ć", words: ["ćevap", "ćilim", "ćup", "ćelija", "ćumez", "ćud", "ćošak", "ćerka", "ćirilica", "ćuskija"] },
  { letter: "D", words: ["dan", "drvo", "dijete", "djed", "doručak", "delfin", "dugme", "daska", "deset", "dimnjak"] },
  { letter: "Dž", words: ["džezva", "džungla", "džemper", "džudo", "džip", "džamija", "džak", "džumbir", "džin", "džep"] },
  { letter: "Đ", words: ["đak", "đon", "đubrivo", "đevrek", "đumbir", "đerdan", "đubre", "đurina", "đuveč", "đurđica"] },
  { letter: "E", words: ["ekran", "efekat", "energija", "Evropa", "e-mail", "ekonomija", "element", "ekser", "etiketa", "epizoda"] },
  { letter: "F", words: ["film", "fudbal", "fabrika", "flomaster", "fenjer", "fotelja", "fotografija", "farmerke", "februar", "frižider"] },
  { letter: "G", words: ["grad", "gitara", "glava", "golub", "godina", "gumica", "grožđe", "grah", "gost", "gljiva"] },
  { letter: "H", words: ["hlače", "haljina", "historija", "heroj", "hobi", "hotel", "hrana", "hodnik", "hemija", "hljeb"] },
  { letter: "I", words: ["igra", "igla", "ideja", "istorija", "ime", "internet", "inžinjer", "istina", "izvor", "ikona"] },
  { letter: "J", words: ["jabuka", "jaje", "jakna", "jastuk", "jezik", "jezero", "jug", "juni", "juli", "jastreb"] },
  { letter: "K", words: ["knjiga", "kuća", "kapa", "kolač", "krava", "krevet", "kino", "kuhinja", "krompir", "krov"] },
  { letter: "L", words: ["lopta", "lampa", "lice", "limun", "lijek", "livada", "list", "leptir", "lonac", "lasta"] },
  { letter: "Lj", words: ["ljudi", "ljiljan", "ljuljačka", "ljubičica", "ljut", "ljestve", "ljuska", "ljepota", "ljekovit", "ljubomora"] },
  { letter: "M", words: ["majka", "mačka", "miš", "more", "most", "mjesec", "muzika", "med", "mlijeko", "mrkva"] },
  { letter: "N", words: ["noga", "nos", "nebo", "noć", "novac", "naočale", "narandža", "nana", "notes", "novine"] },
  { letter: "Nj", words: ["njiva", "njegov", "njuška", "njegovati", "mišljenje", "putovanje", "pitanje", "sanjati", "gunđati", "njorka"] },
  { letter: "O", words: ["oko", "oblak", "olovka", "otac", "odmor", "orao", "ogledalo", "oktobar", "osam", "orah"] },
  { letter: "P", words: ["pas", "ptica", "prozor", "prst", "pismo", "poklon", "pita", "prijatelj", "ponedjeljak", "petak"] },
  { letter: "R", words: ["ruka", "riba", "rijeka", "robot", "ruža", "raketa", "ručak", "radost", "rep", "rat"] },
  { letter: "S", words: ["sunce", "stolica", "soba", "selo", "sestra", "sat", "sir", "sok", "san", "snijeg"] },
  { letter: "Š", words: ["škola", "šešir", "šator", "šljiva", "šal", "šporet", "šaka", "šah", "šapat", "šuma"] },
  { letter: "T", words: ["trava", "tanjir", "telefon", "tigar", "toplo", "tuš", "torba", "tata", "tramvaj", "torta"] },
  { letter: "U", words: ["uho", "ulica", "učitelj", "učenik", "ulje", "unuk", "ujak", "utorak", "usta", "umjetnik"] },
  { letter: "V", words: ["voda", "voz", "vjetar", "voće", "vuk", "večera", "vatra", "vrata", "visibaba", "vaza"] },
  { letter: "Z", words: ["zec", "zub", "zvijezda", "zgrada", "zima", "zlato", "zelena", "zemlja", "zastava", "zadatak"] },
  { letter: "Ž", words: ["žaba", "žirafa", "žito", "žuta", "žena", "život", "želja", "životinja", "žalost", "žurba"] }
];

const alphabetWordsCroatian = [
  { letter: "A", words: ["auto", "avion", "apoteka", "ananas", "apartman", "adresa", "alat", "arhitekt", "Azija", "Amerika"] },
  { letter: "B", words: ["brod", "banana", "beba", "bicikl", "bijela", "balon", "bombon", "brat", "baka", "bazen"] },
  { letter: "C", words: ["cipela", "cesta", "crvena", "cvijet", "cirkus", "car", "crtić", "cijena", "centar", "cimet"] },
  { letter: "Č", words: ["čaša", "čekić", "čokolada", "čarapa", "četka", "čamac", "čovjek", "čelo", "čitati", "četvrtak"] },
  { letter: "Ć", words: ["ćuk", "ćilim", "ćup", "ćelav", "ćumez", "ćud", "ćošak", "kći", "kuća", "noć"] },
  { letter: "D", words: ["dan", "drvo", "dijete", "djed", "doručak", "dupin", "dugme", "daska", "deset", "dimnjak"] },
  { letter: "Dž", words: ["džep", "džungla", "džemper", "džudo", "džip", "džez", "džak", "džumbir", "džin", "džentlmen"] },
  { letter: "Đ", words: ["đak", "đon", "gnojivo", "đevrek", "đumbir", "đerdan", "anđeo", "grožđe", "lađa", "međa"] },
  { letter: "E", words: ["ekran", "efekt", "energija", "Europa", "e-mail", "ekonomija", "element", "ekser", "etiketa", "epizoda"] },
  { letter: "F", words: ["film", "fotelja", "tvornica", "flomaster", "fenjer", "fotografija", "hlače", "veljača", "frižider", "nogomet"] },
  { letter: "G", words: ["grad", "gitara", "glava", "golub", "godina", "gumica", "grožđe", "grah", "gost", "gljiva"] },
  { letter: "H", words: ["kruh", "hlače", "haljina", "povijest", "heroj", "hobi", "hotel", "hrana", "hodnik", "kemija"] },
  { letter: "I", words: ["igra", "igla", "ideja", "povijest", "ime", "internet", "inženjer", "istina", "izvor", "ikona"] },
  { letter: "J", words: ["jabuka", "jaje", "jakna", "jastuk", "jezik", "jezero", "jug", "lipanj", "srpanj", "jastreb"] },
  { letter: "K", words: ["knjiga", "kuća", "kapa", "kolač", "krava", "krevet", "kino", "kuhinja", "krumpir", "krov"] },
  { letter: "L", words: ["lopta", "lampa", "lice", "limun", "lijek", "livada", "list", "leptir", "lonac", "lasta"] },
  { letter: "Lj", words: ["ljudi", "ljiljan", "ljuljačka", "ljubičica", "ljut", "ljestve", "ljuska", "ljepota", "ljekovit", "ljubomora"] },
  { letter: "M", words: ["majka", "mačka", "miš", "more", "most", "mjesec", "glazba", "med", "mlijeko", "mrkva"] },
  { letter: "N", words: ["noga", "nos", "nebo", "noć", "novac", "naočale", "naranča", "nana", "bilježnica", "novine"] },
  { letter: "Nj", words: ["njiva", "njegov", "njuška", "njegovati", "mišljenje", "putovanje", "pitanje", "sanjati", "gunđati", "knjiga"] },
  { letter: "O", words: ["oko", "oblak", "olovka", "otac", "odmor", "orao", "ogledalo", "listopad", "osam", "orah"] },
  { letter: "P", words: ["pas", "ptica", "prozor", "prst", "pismo", "poklon", "pita", "prijatelj", "ponedjeljak", "petak"] },
  { letter: "R", words: ["ruka", "riba", "rijeka", "robot", "ruža", "raketa", "ručak", "radost", "rep", "rat"] },
  { letter: "S", words: ["sunce", "stolica", "soba", "selo", "sestra", "sat", "sir", "sok", "san", "snijeg"] },
  { letter: "Š", words: ["škola", "šešir", "šator", "šljiva", "šal", "štednjak", "šaka", "šah", "šapat", "šuma"] },
  { letter: "T", words: ["trava", "tanjur", "telefon", "tigar", "toplo", "tuš", "torba", "tata", "tramvaj", "torta"] },
  { letter: "U", words: ["uho", "ulica", "učitelj", "učenik", "ulje", "unuk", "ujak", "utorak", "usta", "umjetnik"] },
  { letter: "V", words: ["voda", "vlak", "vjetar", "voće", "vuk", "večera", "vatra", "vrata", "visibaba", "vaza"] },
  { letter: "Z", words: ["zec", "zub", "zvijezda", "zgrada", "zima", "zlato", "zelena", "zemlja", "zastava", "zadaća"] },
  { letter: "Ž", words: ["žaba", "žirafa", "žito", "žuta", "žena", "život", "želja", "životinja", "žalost", "žurba"] }
];

const alphabetWordsSerbian = [
  { letter: "A", words: ["auto", "avion", "apoteka", "ananas", "april", "adresa", "alat", "arhitekta", "Afrika", "Amerika"] },
  { letter: "B", words: ["brod", "banana", "beba", "bicikl", "bela", "balon", "bombona", "brat", "baka", "bazen"] },
  { letter: "V", words: ["voda", "voz", "vetar", "voće", "vuk", "večera", "vatra", "vrata", "visibaba", "vaza"] },
  { letter: "G", words: ["grad", "gitara", "glava", "golub", "godina", "gumica", "grožđe", "pasulj", "gost", "gljiva"] },
  { letter: "D", words: ["dan", "drvo", "dete", "deda", "doručak", "delfin", "dugme", "daska", "deset", "dimnjak"] },
  { letter: "Đ", words: ["đak", "đon", "đubrivo", "đevrek", "đumbir", "đerdan", "đubre", "anđeo", "grožđe", "međa"] },
  { letter: "E", words: ["ekran", "efekat", "energija", "Evropa", "imejl", "ekonomija", "element", "ekser", "etiketa", "epizoda"] },
  { letter: "Ž", words: ["žaba", "žirafa", "žito", "žuta", "žena", "život", "želja", "životinja", "žalost", "žurba"] },
  { letter: "Z", words: ["zec", "zub", "zvezda", "zgrada", "zima", "zlato", "zelena", "zemlja", "zastava", "zadatak"] },
  { letter: "I", words: ["igra", "igla", "ideja", "istorija", "ime", "internet", "inženjer", "istina", "izvor", "ikona"] },
  { letter: "J", words: ["jabuka", "jaje", "jakna", "jastuk", "jezik", "jezero", "jug", "jun", "jul", "jastreb"] },
  { letter: "K", words: ["knjiga", "kuća", "kapa", "kolač", "krava", "krevet", "bioskop", "kuhinja", "krompir", "krov"] },
  { letter: "L", words: ["lopta", "lampa", "lice", "limun", "lek", "livada", "list", "leptir", "lonac", "lasta"] },
  { letter: "Lj", words: ["ljudi", "ljiljan", "ljuljaška", "ljubičica", "ljut", "lestve", "ljuska", "lepota", "lekovit", "ljubomora"] },
  { letter: "M", words: ["majka", "mačka", "miš", "more", "most", "mesec", "muzika", "med", "mleko", "šargarepa"] },
  { letter: "N", words: ["noga", "nos", "nebo", "noć", "novac", "naočare", "narandža", "nana", "sveska", "novine"] },
  { letter: "Nj", words: ["njiva", "njegov", "njuška", "negovati", "mišljenje", "putovanje", "pitanje", "sanjati", "gunđati", "knjiga"] },
  { letter: "O", words: ["oko", "oblak", "olovka", "otac", "odmor", "orao", "ogledalo", "oktobar", "osam", "orah"] },
  { letter: "P", words: ["pas", "ptica", "prozor", "prst", "pismo", "poklon", "pita", "prijatelj", "ponedeljak", "petak"] },
  { letter: "R", words: ["ruka", "riba", "reka", "robot", "ruža", "raketa", "ručak", "radost", "rep", "rat"] },
  { letter: "S", words: ["sunce", "stolica", "soba", "selo", "sestra", "sat", "sir", "sok", "san", "sneg"] },
  { letter: "T", words: ["trava", "tanjir", "telefon", "tigar", "toplo", "tuš", "torba", "tata", "tramvaj", "torta"] },
  { letter: "Ć", words: ["ćevap", "ćilim", "ćup", "ćelija", "ćumez", "ćud", "ćošak", "ćerka", "ćirilica", "ćuskija"] },
  { letter: "U", words: ["uvo", "ulica", "učitelj", "učenik", "ulje", "unuk", "ujak", "utorak", "usta", "umetnik"] },
  { letter: "F", words: ["film", "fudbal", "fabrika", "flomaster", "fenjer", "fotelja", "fotografija", "farmerke", "februar", "frižider"] },
  { letter: "H", words: ["hleb", "pantalone", "haljina", "istorija", "heroj", "hobi", "hotel", "hrana", "hodnik", "hemija"] },
  { letter: "C", words: ["cipela", "put", "crvena", "cvet", "cirkus", "car", "crtani", "cena", "centar", "cimet"] },
  { letter: "Č", words: ["čaša", "čekić", "čokolada", "čarapa", "četka", "čamac", "čovek", "čelo", "čitati", "četvrtak"] },
  { letter: "Dž", words: ["džezva", "džungla", "džemper", "džudo", "džip", "džamija", "džak", "đumbir", "džin", "džep"] },
  { letter: "Š", words: ["škola", "šešir", "šator", "šljiva", "šal", "šporet", "šaka", "šah", "šapat", "šuma"] }
];


const bosnianData = {
    alphabet: bosnianAlphabet,
    numbers: numbers,
    alphabetWords: alphabetWordsBosnian,
    vocabulary: [],
    spelling: [
      { id: 1, sentence: 'Moja mama pije ___.', blank: 'kafu', options: ['stolicu', 'kafu', 'lopatom'] },
      { id: 2, sentence: 'Idem u ___.', blank: 'školu', options: ['školu', 'oblak', 'drvetom'] },
      { id: 3, sentence: 'Ovo je moja ___.', blank: 'kuća', options: ['nebo', 'sreća', 'kuća'] },
      { id: 4, sentence: 'Čitam ___.', blank: 'knjigu', options: ['knjigu', 'staklo', 'zidom'] },
      { id: 5, sentence: 'Jedem ___.', blank: 'jabuku', options: ['kamen', 'jabuku', 'cipelom'] },
      { id: 6, sentence: 'Učiteljica nosi ___.', blank: 'naočale', options: ['naočale', 'naočare', 'naoćale'] },
      { id: 7, sentence: 'Na tanjiru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
      { id: 8, sentence: 'Djed nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
      { id: 9, sentence: 'Idem u ___ spavati.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
      { id: 10, sentence: 'U bašči raste crveni ___.', blank: 'cvijet', options: ['cvijet', 'cvjet', 'cvit'] },
      { id: 11, sentence: 'To je moj najbolji ___.', blank: 'prijatelj', options: ['prijatelj', 'prijatel', 'priatelj'] },
      { id: 12, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lishche', 'Lisce'] },
      { id: 13, sentence: '___ se igra s loptom.', blank: 'Dječak', options: ['Dječak', 'Dečak', 'Djećak'] },
      { id: 14, sentence: 'U ___ ima puno knjiga.', blank: 'biblioteci', options: ['biblioteci', 'knjižnici', 'knjižnjici'] },
      { id: 15, sentence: 'Vidio sam ___ na nebu.', blank: 'zvijezde', options: ['zvjezde', 'zvijezde', 'zvezde'] },
    ],
    sentences: [
      { id: 1, sentence: 'Dječak čita knjigu.' },
      { id: 2, sentence: 'Djevojčica jede jabuku.' },
      { id: 3, sentence: 'Pas trči brzo.' },
      { id: 4, sentence: 'Mačka spava na suncu.' },
      { id: 5, sentence: 'Mi idemo u školu.' },
      { id: 6, sentence: 'Učiteljica piše na tabli.' },
      { id: 7, sentence: 'Djeca se igraju u parku.' },
      { id: 8, sentence: 'Sunce sija svaki dan.' },
      { id: 9, sentence: 'Ja volim jesti sladoled.' },
      { id: 10, sentence: 'Moj tata vozi auto.' },
    ],
    grammar: [
      { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
      { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
      { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamjenica mora biti u ženskom rodu (moja).' },
      { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (veliki).' },
      { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' },
    ],
    reading: [
      {
        id: 1,
        title: "Izlet u šumu",
        text: "Jednog sunčanog dana, Amina i njen brat Adnan su otišli na izlet u šumu sa roditeljima. Ponijeli su korpu punu hrane. U šumi su vidjeli mnogo drveća i čuli cvrkut ptica. Adnan je vidio vjevericu kako se penje uz drvo. Amina je brala šareno cvijeće. Nakon šetnje, sjeli su na deku i ručali. Bio je to divan dan.",
        questions: [
          { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Amina", "Amina i Adnan sa roditeljima", "Samo Adnan"], answer: "Amina i Adnan sa roditeljima" },
          { id: 2, question: "Šta je Adnan vidio u šumi?", options: ["Zeca", "Medvjeda", "Vjevericu"], answer: "Vjevericu" },
          { id: 3, question: "Šta je Amina radila?", options: ["Pela se na drvo", "Brala cvijeće", "Spavala"], answer: "Brala cvijeće" },
        ]
      },
      {
        id: 2,
        title: "Pas Medo",
        text: "Dječak po imenu Amar ima psa koji se zove Medo. Medo je veliki žuti pas sa dugim repom. Svaki dan, Amar i Medo idu u park. Amar baca lopticu, a Medo je donosi nazad. Medo voli da se igra i da laje na mačke. Navečer, Medo spava u svojoj kućici u dvorištu. Amar mnogo voli svog psa.",
        questions: [
          { id: 1, question: "Kako se zove Amarov pas?", options: ["Žućo", "Lajko", "Medo"], answer: "Medo" },
          { id: 2, question: "Gdje se Amar i Medo igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
          { id: 3, question: "Šta Amar baca Medi?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
        ]
      },
    ],
    translations: [
      { id: 1, type: 'word', source: 'kaffe', target: 'kafa' },
      { id: 2, type: 'word', source: 'skola', target: 'škola' },
      { id: 3, type: 'word', source: 'hus', target: 'kuća' },
      { id: 4, type: 'word', source: 'bok', target: 'knjiga' },
      { id: 5, type: 'word', source: 'äpple', target: 'jabuka' },
      { id: 6, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
      { id: 7, type: 'sentence', source: 'Flickan äter ett äpple.', target: 'Djevojčica jede jabuku.' },
    ]
};

const croatianData = {
    alphabet: croatianAlphabet,
    numbers: croatianNumbers,
    alphabetWords: alphabetWordsCroatian,
    vocabulary: [],
    spelling: [
      { id: 1, sentence: 'Moja mama pije ___.', blank: 'kavu', options: ['stolicu', 'kavu', 'lopatom'] },
      { id: 2, sentence: 'Idem u ___.', blank: 'školu', options: ['školu', 'oblak', 'stablom'] },
      { id: 3, sentence: 'Ovo je moja ___.', blank: 'kuća', options: ['nebo', 'sreća', 'kuća'] },
      { id: 4, sentence: 'Čitam ___.', blank: 'knjigu', options: ['knjigu', 'staklo', 'zidom'] },
      { id: 5, sentence: 'Jedem ___.', blank: 'jabuku', options: ['kamen', 'jabuku', 'cipelom'] },
      { id: 6, sentence: 'Učiteljica nosi ___.', blank: 'naočale', options: ['naočale', 'naočare', 'naoćale'] },
      { id: 7, sentence: 'Na tanjuru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
      { id: 8, sentence: 'Djed nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
      { id: 9, sentence: 'Idem u ___ spavati.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
      { id: 10, sentence: 'U vrtu raste crveni ___.', blank: 'cvijet', options: ['cvijet', 'cvjet', 'cvit'] },
      { id: 11, sentence: 'To je moj najbolji ___.', blank: 'prijatelj', options: ['prijatelj', 'prijatel', 'priatelj'] },
      { id: 12, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lisće', 'Lisce'] },
      { id: 13, sentence: '___ se igra s loptom.', blank: 'Dječak', options: ['Dječak', 'Dečak', 'Djećak'] },
      { id: 14, sentence: 'U ___ ima puno knjiga.', blank: 'knjižnici', options: ['biblioteci', 'knjižnici', 'knjižnjici'] },
      { id: 15, sentence: 'Vidio sam ___ na nebu.', blank: 'zvijezde', options: ['zvjezde', 'zvijezde', 'zvezde'] },
    ],
    sentences: [
      { id: 1, sentence: 'Dječak čita knjigu.' },
      { id: 2, sentence: 'Djevojčica jede jabuku.' },
      { id: 3, sentence: 'Pas trči brzo.' },
      { id: 4, sentence: 'Mačka spava na suncu.' },
      { id: 5, sentence: 'Mi idemo u školu.' },
      { id: 6, sentence: 'Učiteljica piše na ploči.' },
      { id: 7, sentence: 'Djeca se igraju u parku.' },
      { id: 8, sentence: 'Sunce sja svaki dan.' },
      { id: 9, sentence: 'Ja volim jesti sladoled.' },
      { id: 10, sentence: 'Moj tata vozi auto.' },
    ],
    grammar: [
        { id: 1, sentence: 'Dječak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekt u jednini (dječak) zahtijeva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Djevojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekt u množini (djevojčice) zahtijeva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa posvojna zamjenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'velik', options: ['velik', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridjev mora biti u muškom rodu (velik).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridjev "crven" ima oblik "crvenu".' },
    ],
    reading: [
      {
        id: 1,
        title: "Izlet u šumu",
        text: "Jednog sunčanog dana, Ana i njen brat Luka otišli su na izlet u šumu s roditeljima. Ponijeli su košaru punu hrane. U šumi su vidjeli mnogo drveća i čuli cvrkut ptica. Luka je vidio vjevericu kako se penje uz stablo. Ana je brala šareno cvijeće. Nakon šetnje, sjeli su na deku i ručali. Bio je to divan dan.",
        questions: [
          { id: 1, question: "Tko je otišao na izlet?", options: ["Samo Ana", "Ana i Luka s roditeljima", "Samo Luka"], answer: "Ana i Luka s roditeljima" },
          { id: 2, question: "Što je Luka vidio u šumi?", options: ["Zeca", "Medvjeda", "Vjevericu"], answer: "Vjevericu" },
          { id: 3, question: "Što je Ana radila?", options: ["Pela se na drvo", "Brala cvijeće", "Spavala"], answer: "Brala cvijeće" },
        ]
      },
      {
        id: 2,
        title: "Pas Rex",
        text: "Dječak po imenu Ivan ima psa koji se zove Rex. Rex je veliki žuti pas s dugim repom. Svaki dan, Ivan i Rex idu u park. Ivan baca lopticu, a Rex je donosi natrag. Rex se voli igrati i lajati na mačke. Navečer, Rex spava u svojoj kućici u dvorištu. Ivan mnogo voli svog psa.",
        questions: [
          { id: 1, question: "Kako se zove Ivanov pas?", options: ["Žućo", "Lajko", "Rex"], answer: "Rex" },
          { id: 2, question: "Gdje se Ivan i Rex igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
          { id: 3, question: "Što Ivan baca Rexu?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
        ]
      },
    ],
    translations: [
      { id: 1, type: 'word', source: 'kaffe', target: 'kava' },
      { id: 2, type: 'word', source: 'skola', target: 'škola' },
      { id: 3, type: 'word', source: 'hus', target: 'kuća' },
      { id: 4, type: 'word', source: 'bok', target: 'knjiga' },
      { id: 5, type: 'word', source: 'bröd', target: 'kruh' },
      { id: 6, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dječak čita knjigu.' },
      { id: 7, type: 'sentence', source: 'Jag bor i ett stort hus.', target: 'Živim u velikoj kući.' },
    ]
};

const serbianData = {
    alphabet: serbianAlphabet,
    numbers: serbianNumbers,
    alphabetWords: alphabetWordsSerbian,
    vocabulary: [],
    spelling: [
      { id: 1, sentence: 'Moja mama pije ___.', blank: 'kafu', options: ['stolicu', 'kafu', 'lopatom'] },
      { id: 2, sentence: 'Idem u ___.', blank: 'školu', options: ['školu', 'oblak', 'drvetom'] },
      { id: 3, sentence: 'Ovo je moja ___.', blank: 'kuća', options: ['nebo', 'sreća', 'kuća'] },
      { id: 4, sentence: 'Čitam ___.', blank: 'knjigu', options: ['knjigu', 'staklo', 'zidom'] },
      { id: 5, sentence: 'Jedem ___.', blank: 'jabuku', options: ['kamen', 'jabuku', 'cipelom'] },
      { id: 6, sentence: 'Učiteljica nosi ___.', blank: 'naočare', options: ['naočale', 'naočare', 'naoćale'] },
      { id: 7, sentence: 'Na tanjiru je ___.', blank: 'voće', options: ['voće', 'voče', 'voce'] },
      { id: 8, sentence: 'Deda nosi smeđi ___.', blank: 'šešir', options: ['šešir', 'šećir', 'šesir'] },
      { id: 9, sentence: 'Idem u ___ da spavam.', blank: 'krevet', options: ['krevet', 'krevit', 'krevat'] },
      { id: 10, sentence: 'U bašti raste crveni ___.', blank: 'cvet', options: ['cvijet', 'cvet', 'cvit'] },
      { id: 11, sentence: 'To je moj najbolji ___.', blank: 'drug', options: ['prijatelj', 'drugar', 'drug'] },
      { id: 12, sentence: '___ je zeleno.', blank: 'Lišće', options: ['Lišće', 'Lisće', 'Lisce'] },
      { id: 13, sentence: '___ se igra sa loptom.', blank: 'Dečak', options: ['Dječak', 'Dečak', 'Djećak'] },
      { id: 14, sentence: 'U ___ ima puno knjiga.', blank: 'biblioteci', options: ['biblioteci', 'knjižnici', 'biblioteki'] },
      { id: 15, sentence: 'Video sam ___ na nebu.', blank: 'zvezde', options: ['zvjezde', 'zvijezde', 'zvezde'] },
    ],
    sentences: [
      { id: 1, sentence: 'Dečak čita knjigu.' },
      { id: 2, sentence: 'Devojčica jede jabuku.' },
      { id: 3, sentence: 'Pas trči brzo.' },
      { id: 4, sentence: 'Mačka spava na suncu.' },
      { id: 5, sentence: 'Mi idemo u školu.' },
      { id: 6, sentence: 'Učiteljica piše na tabli.' },
      { id: 7, sentence: 'Deca se igraju u parku.' },
      { id: 8, sentence: 'Sunce sija svaki dan.' },
      { id: 9, sentence: 'Ja volim da jedem sladoled.' },
      { id: 10, sentence: 'Moj tata vozi auto.' },
    ],
    grammar: [
        { id: 1, sentence: 'Dečak ___ loptu.', blank: 'ima', options: ['ima', 'imaju', 'imamo'], explanation: 'Subjekat u jednini (dečak) zahteva glagol u trećem licu jednine (ima).' },
        { id: 2, sentence: 'Devojčice se ___.', blank: 'igraju', options: ['igra', 'igraš', 'igraju'], explanation: 'Subjekat u množini (devojčice) zahteva glagol u trećem licu množine (igraju).' },
        { id: 3, sentence: 'Ovo je ___ kuća.', blank: 'moja', options: ['moj', 'moja', 'moje'], explanation: 'Imenica "kuća" je ženskog roda, pa prisvojna zamenica mora biti u ženskom rodu (moja).' },
        { id: 4, sentence: 'Idem u ___ grad.', blank: 'veliki', options: ['veliki', 'velika', 'veliko'], explanation: 'Imenica "grad" je muškog roda, pa pridev mora biti u muškom rodu (veliki).' },
        { id: 5, sentence: 'Jedem ___ jabuku.', blank: 'crvenu', options: ['crveni', 'crvena', 'crvenu'], explanation: 'U akuzativu jednine ženskog roda, pridev "crven" ima oblik "crvenu".' },
    ],
    reading: [
      {
        id: 1,
        title: "Izlet u šumu",
        text: "Jednog sunčanog dana, Milica i njen brat Nemanja su otišli na izlet u šumu sa roditeljima. Poneli su korpu punu hrane. U šumi su videli mnogo drveća i čuli cvrkut ptica. Nemanja je video vevericu kako se penje uz drvo. Milica je brala šareno cveće. Posle šetnje, seli su na ćebe i ručali. Bio je to divan dan.",
        questions: [
          { id: 1, question: "Ko je otišao na izlet?", options: ["Samo Milica", "Milica i Nemanja sa roditeljima", "Samo Nemanja"], answer: "Milica i Nemanja sa roditeljima" },
          { id: 2, question: "Šta je Nemanja video u šumi?", options: ["Zeca", "Medveda", "Vevericu"], answer: "Vevericu" },
          { id: 3, question: "Šta je Milica radila?", options: ["Pela se na drvo", "Brala cveće", "Spavala"], answer: "Brala cveće" },
        ]
      },
      {
        id: 2,
        title: "Pas Žuća",
        text: "Dečak po imenu Stefan ima psa koji se zove Žuća. Žuća je veliki žuti pas sa dugačkim repom. Svaki dan, Stefan i Žuća idu u park. Stefan baca lopticu, a Žuća je donosi nazad. Žuća voli da se igra i da laje na mačke. Uveče, Žuća spava u svojoj kućici u dvorištu. Stefan mnogo voli svog psa.",
        questions: [
          { id: 1, question: "Kako se zove Stefanov pas?", options: ["Rex", "Lajko", "Žuća"], answer: "Žuća" },
          { id: 2, question: "Gde se Stefan i Žuća igraju?", options: ["U kući", "U parku", "U školi"], answer: "U parku" },
          { id: 3, question: "Šta Stefan baca Žući?", options: ["Kamen", "Granu", "Lopticu"], answer: "Lopticu" },
        ]
      },
    ],
    translations: [
      { id: 1, type: 'word', source: 'kaffe', target: 'kafa' },
      { id: 2, type: 'word', source: 'skola', target: 'škola' },
      { id: 3, type: 'word', source: 'hus', target: 'kuća' },
      { id: 4, type: 'word', source: 'bok', target: 'knjiga' },
      { id: 5, type: 'word', source: 'bröd', target: 'hleb' },
      { id: 6, type: 'sentence', source: 'Pojken läser en bok.', target: 'Dečak čita knjigu.' },
      { id: 7, type: 'sentence', source: 'Jag dricker kaffe.', target: 'Ja pijem kafu.' },
    ]
};

const createGradeData = (data) => {
    return {
        alphabet: data.alphabet,
        numbers: data.numbers,
        alphabetWords: data.alphabetWords,
        vocabulary: [],
        spelling: JSON.parse(JSON.stringify(data.spelling)),
        sentences: JSON.parse(JSON.stringify(data.sentences)),
        grammar: JSON.parse(JSON.stringify(data.grammar)),
        reading: JSON.parse(JSON.stringify(data.reading)),
        translations: JSON.parse(JSON.stringify(data.translations)),
    };
}

export const data: LanguageData = {
  bosnian: {
    '1-3': createGradeData(bosnianData),
    '4-6': createGradeData(bosnianData),
    '7-9': createGradeData(bosnianData),
  },
  croatian: {
    '1-3': createGradeData(croatianData),
    '4-6': createGradeData(croatianData),
    '7-9': createGradeData(croatianData),
  },
  serbian: {
    '1-3': createGradeData(serbianData),
    '4-6': createGradeData(serbianData),
    '7-9': createGradeData(serbianData),
  },
};
