
import type { VocabularyData } from './types';

// ========= BOSNIAN DATA =========
const bosnianVocabularyData = {
    '1-3': {
        family: {
            title: 'Porodica',
            description: 'Nauči riječi za članove porodice.',
            swedish: 'Familj',
            items: [
                { id: 1001, word: 'majka', translation: 'mamma' },
                { id: 1002, word: 'otac', translation: 'pappa' },
                { id: 1003, word: 'sestra', translation: 'syster' },
                { id: 1004, word: 'brat', translation: 'bror' },
                { id: 1005, word: 'nana', translation: 'farmor/mormor' },
                { id: 1006, word: 'djed', translation: 'farfar/morfar' },
                { id: 1013, word: 'tetka', translation: 'moster/faster' },
                { id: 1014, word: 'amidža', translation: 'farbror (paternal)' },
                { id: 1015, word: 'daidža', translation: 'morbror (maternal)' },
                { id: 1016, word: 'beba', translation: 'bebis' },
            ],
        },
        colors: {
            title: 'Boje',
            description: 'Otkrij nazive za različite boje.',
            swedish: 'Färger',
            items: [
                { id: 1007, word: 'crvena', translation: 'röd' },
                { id: 1008, word: 'plava', translation: 'blå' },
                { id: 1009, word: 'zelena', translation: 'grön' },
                { id: 1010, word: 'žuta', translation: 'gul' },
                { id: 1011, word: 'crna', translation: 'svart' },
                { id: 1012, word: 'bijela', translation: 'vit' },
                { id: 1017, word: 'narandžasta', translation: 'orange' },
                { id: 1018, word: 'ljubičasta', translation: 'lila' },
                { id: 1019, word: 'smeđa', translation: 'brun' },
                { id: 1020, word: 'siva', translation: 'grå' },
            ],
        },
        animals: {
            title: 'Životinje',
            description: 'Nauči nazive domaćih i divljih životinja.',
            swedish: 'Djur',
            items: [
                { id: 1021, word: 'pas', translation: 'hund' },
                { id: 1022, word: 'mačka', translation: 'katt' },
                { id: 1023, word: 'ptica', translation: 'fågel' },
                { id: 1024, word: 'riba', translation: 'fisk' },
                { id: 1025, word: 'konj', translation: 'häst' },
                { id: 1026, word: 'krava', translation: 'ko' },
                { id: 1027, word: 'lav', translation: 'lejon' },
                { id: 1028, word: 'tigar', translation: 'tiger' },
                { id: 1029, word: 'medvjed', translation: 'björn' },
                { id: 1030, word: 'zec', translation: 'kanin' },
            ]
        },
        toys: {
            title: 'Igračke',
            description: 'Nazivi za popularne dječije igračke.',
            swedish: 'Leksaker',
            items: [
                { id: 1031, word: 'lopta', translation: 'boll' },
                { id: 1032, word: 'lutka', translation: 'docka' },
                { id: 1033, word: 'auto', translation: 'bil' },
                { id: 1034, word: 'kocke', translation: 'klossar' },
                { id: 1035, word: 'medo', translation: 'nalle' },
                { id: 1036, word: 'robot', translation: 'robot' },
                { id: 1037, word: 'avion', translation: 'flygplan' },
                { id: 1038, word: 'vozić', translation: 'tåg' },
                { id: 1039, word: 'slagalica', translation: 'pussel' },
                { id: 1040, word: 'zmaj', translation: 'drake' },
            ]
        },
        nature: {
            title: 'Priroda',
            description: 'Osnovni pojmovi iz prirode.',
            swedish: 'Natur',
            items: [
                { id: 1041, word: 'sunce', translation: 'sol' },
                { id: 1042, word: 'mjesec', translation: 'måne' },
                { id: 1043, word: 'zvijezda', translation: 'stjärna' },
                { id: 1044, word: 'drvo', translation: 'träd' },
                { id: 1045, word: 'cvijet', translation: 'blomma' },
                { id: 1046, word: 'rijeka', translation: 'flod' },
                { id: 1047, word: 'planina', translation: 'berg' },
                { id: 1048, word: 'nebo', translation: 'himmel' },
                { id: 1049, word: 'kiša', translation: 'regn' },
                { id: 1050, word: 'snijeg', translation: 'snö' },
            ]
        },
        food_1_3: {
            title: 'Hrana',
            description: 'Osnovne vrste hrane.',
            swedish: 'Mat',
            items: [
                { id: 1051, word: 'hljeb', translation: 'bröd' },
                { id: 1052, word: 'mlijeko', translation: 'mjölk' },
                { id: 1053, word: 'jabuka', translation: 'äpple' },
                { id: 1054, word: 'banana', translation: 'banan' },
                { id: 1055, word: 'voda', translation: 'vatten' },
                { id: 1056, word: 'sir', translation: 'ost' },
                { id: 1057, word: 'jaje', translation: 'ägg' },
                { id: 1058, word: 'supa', translation: 'soppa' },
                { id: 1059, word: 'kolač', translation: 'kaka' },
                { id: 1060, word: 'piletina', translation: 'kyckling' },
            ]
        },
        school_1_3: {
            title: 'Škola',
            description: 'Osnovni školski pribor.',
            swedish: 'Skola',
            items: [
                { id: 1061, word: 'knjiga', translation: 'bok' },
                { id: 1062, word: 'olovka', translation: 'penna' },
                { id: 1063, word: 'gumica', translation: 'suddgummi' },
                { id: 1064, word: 'stolica', translation: 'stol' },
                { id: 1065, word: 'sto', translation: 'bord' },
                { id: 1066, word: 'učiteljica', translation: 'lärare' },
                { id: 1067, word: 'učenik', translation: 'elev' },
                { id: 1068, word: 'torba', translation: 'väska' },
                { id: 1069, word: 'makaze', translation: 'sax' },
                { id: 1070, word: 'papir', translation: 'papper' },
            ]
        },
        clothes_1_3: {
            title: 'Odjeća',
            description: 'Osnovni odjevni predmeti.',
            swedish: 'Kläder',
            items: [
                { id: 1071, word: 'majica', translation: 't-shirt' },
                { id: 1072, word: 'hlače', translation: 'byxor' },
                { id: 1073, word: 'haljina', translation: 'klänning' },
                { id: 1074, word: 'jakna', translation: 'jacka' },
                { id: 1075, word: 'cipele', translation: 'skor' },
                { id: 1076, word: 'čarape', translation: 'strumpor' },
                { id: 1077, word: 'kapa', translation: 'mössa' },
                { id: 1078, word: 'šal', translation: 'halsduk' },
                { id: 1079, word: 'rukavice', translation: 'handskar' },
                { id: 1080, word: 'suknja', translation: 'kjol' },
            ]
        },
    },
    '4-6': {
        school: {
            title: 'Škola',
            description: 'Riječi vezane za školu i pribor.',
            swedish: 'Skola',
            items: [
                { id: 1101, word: 'učionica', translation: 'klassrum' },
                { id: 1102, word: 'tabla', translation: 'tavla' },
                { id: 1103, word: 'sveska', translation: 'skrivbok' },
                { id: 1104, word: 'pernica', translation: 'pennskrin' },
                { id: 1105, word: 'odmor', translation: 'rast' },
                { id: 1106, word: 'domaća zadaća', translation: 'läxa' },
                { id: 1107, word: 'historija', translation: 'historia' },
                { id: 1108, word: 'geografija', translation: 'geografi' },
                { id: 1109, word: 'matematika', translation: 'matematik' },
                { id: 1110, word: 'lenjir', translation: 'linjal' },
            ]
        },
        food: {
            title: 'Hrana i piće',
            description: 'Nazivi za obroke, namirnice i pića.',
            swedish: 'Mat och dryck',
            items: [
                { id: 1111, word: 'doručak', translation: 'frukost' },
                { id: 1112, word: 'ručak', translation: 'lunch' },
                { id: 1113, word: 'večera', translation: 'middag' },
                { id: 1114, word: 'hljeb', translation: 'bröd' },
                { id: 1115, word: 'mlijeko', translation: 'mjölk' },
                { id: 1116, word: 'voda', translation: 'vatten' },
                { id: 1117, word: 'sok', translation: 'juice' },
                { id: 1118, word: 'meso', translation: 'kött' },
                { id: 1119, word: 'povrće', translation: 'grönsaker' },
                { id: 1120, word: 'voće', translation: 'frukt' },
            ]
        },
        hobbies: {
            title: 'Hobiji',
            description: 'Riječi za različite hobije i slobodne aktivnosti.',
            swedish: 'Fritidsintressen',
            items: [
                { id: 1121, word: 'čitanje', translation: 'läsning' },
                { id: 1122, word: 'pjevanje', translation: 'sång' },
                { id: 1123, word: 'plesanje', translation: 'dans' },
                { id: 1124, word: 'crtanje', translation: 'teckning' },
                { id: 1125, word: 'fudbal', translation: 'fotboll' },
                { id: 1126, word: 'košarka', translation: 'basket' },
                { id: 1127, word: 'sviranje gitare', translation: 'gitarrspel' },
                { id: 1128, word: 'gledanje filmova', translation: 'filmtittande' },
                { id: 1129, word: 'planinarenje', translation: 'vandring' },
                { id: 1130, word: 'igranje igrica', translation: 'dataspel' },
            ]
        },
        city: {
            title: 'Grad',
            description: 'Nazivi za mjesta i objekte u gradu.',
            swedish: 'Stad',
            items: [
                { id: 1131, word: 'ulica', translation: 'gata' },
                { id: 1132, word: 'trg', translation: 'torg' },
                { id: 1133, word: 'prodavnica', translation: 'affär' },
                { id: 1134, word: 'bolnica', translation: 'sjukhus' },
                { id: 1135, word: 'park', translation: 'park' },
                { id: 1136, word: 'most', translation: 'bro' },
                { id: 1137, word: 'semafor', translation: 'trafikljus' },
                { id: 1138, word: 'zgrada', translation: 'byggnad' },
                { id: 1139, word: 'kino', translation: 'bio' },
                { id: 1140, word: 'pošta', translation: 'postkontor' },
            ]
        },
        clothes: {
            title: 'Odjeća',
            description: 'Nazivi za različite odjevne predmete.',
            swedish: 'Kläder',
            items: [
                { id: 1141, word: 'majica', translation: 't-shirt' },
                { id: 1142, word: 'hlače', translation: 'byxor' },
                { id: 1143, word: 'haljina', translation: 'klänning' },
                { id: 1144, word: 'jakna', translation: 'jacka' },
                { id: 1145, word: 'cipele', translation: 'skor' },
                { id: 1146, word: 'čarape', translation: 'strumpor' },
                { id: 1147, word: 'šešir', translation: 'hatt' },
                { id: 1148, word: 'šal', translation: 'halsduk' },
                { id: 1149, word: 'rukavice', translation: 'handskar' },
                { id: 1150, word: 'džemper', translation: 'tröja' },
            ]
        },
        body_4_6: {
            title: 'Ljudsko tijelo',
            description: 'Osnovni dijelovi tijela.',
            swedish: 'Människokroppen',
            items: [
                { id: 1151, word: 'glava', translation: 'huvud' },
                { id: 1152, word: 'ruka', translation: 'arm/hand' },
                { id: 1153, word: 'noga', translation: 'ben/fot' },
                { id: 1154, word: 'stomak', translation: 'mage' },
                { id: 1155, word: 'leđa', translation: 'rygg' },
                { id: 1156, word: 'oko', translation: 'öga' },
                { id: 1157, word: 'uho', translation: 'öra' },
                { id: 1158, word: 'nos', translation: 'näsa' },
                { id: 1159, word: 'usta', translation: 'mun' },
                { id: 1160, word: 'kosa', translation: 'hår' },
            ]
        },
        sports: {
            title: 'Sport',
            description: 'Nazivi za popularne sportove.',
            swedish: 'Sport',
            items: [
                { id: 1161, word: 'fudbal', translation: 'fotboll' },
                { id: 1162, word: 'košarka', translation: 'basket' },
                { id: 1163, word: 'tenis', translation: 'tennis' },
                { id: 1164, word: 'plivanje', translation: 'simning' },
                { id: 1165, word: 'odbojka', translation: 'volleyboll' },
                { id: 1166, word: 'atletika', translation: 'friidrott' },
                { id: 1167, word: 'skijanje', translation: 'skidåkning' },
                { id: 1168, word: 'rukomet', translation: 'handboll' },
                { id: 1169, word: 'gimnastika', translation: 'gymnastik' },
                { id: 1170, word: 'biciklizam', translation: 'cykling' },
            ]
        },
        holidays: {
            title: 'Praznici',
            description: 'Nazivi za praznike i proslave.',
            swedish: 'Högtider',
            items: [
                { id: 1171, word: 'rođendan', translation: 'födelsedag' },
                { id: 1172, word: 'Nova godina', translation: 'nyår' },
                { id: 1173, word: 'Bajram', translation: 'Eid' },
                { id: 1174, word: 'Božić', translation: 'jul' },
                { id: 1175, 'word': 'Uskrs', 'translation': 'påsk' },
                { id: 1176, word: 'praznik', translation: 'helgdag/lov' },
                { id: 1177, word: 'poklon', translation: 'present' },
                { id: 1178, word: 'slavlje', translation: 'firande' },
                { id: 1179, word: 'godišnjica', translation: 'årsdag' },
                { id: 1180, word: 'vatromet', translation: 'fyrverkeri' },
            ]
        },
        calendar: {
            title: 'Mjeseci i dani',
            description: 'Nazivi za dane u sedmici i mjesece.',
            swedish: 'Månader och dagar',
            items: [
                { id: 1181, word: 'ponedjeljak', translation: 'måndag' },
                { id: 1182, word: 'utorak', translation: 'tisdag' },
                { id: 1183, word: 'srijeda', translation: 'onsdag' },
                { id: 1184, word: 'januar', translation: 'januari' },
                { id: 1185, word: 'februar', translation: 'februari' },
                { id: 1186, word: 'mart', translation: 'mars' },
                { id: 1187, word: 'sedmica', translation: 'vecka' },
                { id: 1188, word: 'mjesec', translation: 'månad' },
                { id: 1189, word: 'godina', translation: 'år' },
                { id: 1190, word: 'vikend', translation: 'helg' },
            ]
        },
    },
    '7-9': {
        body: {
            title: 'Ljudsko tijelo',
            description: 'Dijelovi ljudskog tijela.',
            swedish: 'Människokroppen',
            items: [
                { id: 1201, word: 'glava', translation: 'huvud' },
                { id: 1202, word: 'srce', translation: 'hjärta' },
                { id: 1203, word: 'pluća', translation: 'lungor' },
                { id: 1204, word: 'mozak', translation: 'hjärna' },
                { id: 1205, word: 'stomak', translation: 'mage' },
                { id: 1206, word: 'kosti', translation: 'ben (skelett)' },
                { id: 1207, word: 'mišić', translation: 'muskel' },
                { id: 1208, word: 'koža', translation: 'hud' },
                { id: 1209, word: 'krv', translation: 'blod' },
                { id: 1210, word: 'koljeno', translation: 'knä' },
            ]
        },
        technology: {
            title: 'Tehnologija',
            description: 'Riječi iz svijeta tehnologije.',
            swedish: 'Teknologi',
            items: [
                { id: 1211, word: 'računar', translation: 'dator' },
                { id: 1212, word: 'mobitel', translation: 'mobiltelefon' },
                { id: 1213, word: 'internet', translation: 'internet' },
                { id: 1214, word: 'aplikacija', translation: 'applikation' },
                { id: 1215, word: 'lozinka', translation: 'lösenord' },
                { id: 1216, word: 'ekran', translation: 'skärm' },
                { id: 1217, word: 'tastatura', translation: 'tangentbord' },
                { id: 1218, word: 'miš', translation: 'mus' },
                { id: 1219, word: 'poruka', translation: 'meddelande' },
                { id: 1220, word: 'punjač', translation: 'laddare' },
            ]
        },
        professions: {
            title: 'Zanimanja',
            description: 'Nazivi za različita zanimanja.',
            swedish: 'Yrken',
            items: [
                { id: 1221, word: 'liječnik', translation: 'läkare' },
                { id: 1222, word: 'učitelj', translation: 'lärare' },
                { id: 1223, word: 'inžinjer', translation: 'ingenjör' },
                { id: 1224, word: 'programer', translation: 'programmerare' },
                { id: 1225, word: 'umjetnik', translation: 'konstnär' },
                { id: 1226, word: 'policajac', translation: 'polis' },
                { id: 1227, word: 'vatrogasac', translation: 'brandman' },
                { id: 1228, word: 'kuhar', translation: 'kock' },
                { id: 1229, word: 'novinar', translation: 'journalist' },
                { id: 1230, word: 'advokat', translation: 'advokat' },
            ]
        },
        emotions: {
            title: 'Osjećaji',
            description: 'Riječi koje opisuju kako se osjećamo.',
            swedish: 'Känslor',
            items: [
                { id: 1231, word: 'sretan', translation: 'glad' },
                { id: 1232, word: 'tužan', translation: 'ledsen' },
                { id: 1233, word: 'ljut', translation: 'arg' },
                { id: 1234, word: 'uplašen', translation: 'rädd' },
                { id: 1235, word: 'iznenađen', translation: 'förvånad' },
                { id: 1236, word: 'uzbuđen', translation: 'exalterad' },
                { id: 1237, word: 'umoran', translation: 'trött' },
                { id: 1238, word: 'ponosan', translation: 'stolt' },
                { id: 1239, word: 'zabrinut', translation: 'orolig' },
                { id: 1240, word: 'usamljen', translation: 'ensam' },
            ]
        },
        travel: {
            title: 'Putovanje',
            description: 'Riječi vezane za putovanja i transport.',
            swedish: 'Resor',
            items: [
                { id: 1241, word: 'aerodrom', translation: 'flygplats' },
                { id: 1242, word: 'pasoš', translation: 'pass' },
                { id: 1243, word: 'karta', translation: 'biljett' },
                { id: 1244, word: 'hotel', translation: 'hotell' },
                { id: 1245, word: 'kofer', translation: 'resväska' },
                { id: 1246, word: 'plaža', translation: 'strand' },
                { id: 1247, word: 'turist', translation: 'turist' },
                { id: 1248, word: 'odmor', translation: 'semester' },
                { id: 1249, word: 'voz', translation: 'tåg' },
                { id: 1250, word: 'autobus', translation: 'buss' },
            ]
        },
        music: {
            title: 'Muzika',
            description: 'Riječi iz svijeta muzike.',
            swedish: 'Musik',
            items: [
                { id: 1251, word: 'gitara', translation: 'gitarr' },
                { id: 1252, word: 'klavir', translation: 'piano' },
                { id: 1253, word: 'bubnjevi', translation: 'trummor' },
                { id: 1254, word: 'pjesma', translation: 'låt' },
                { id: 1255, word: 'koncert', translation: 'konsert' },
                { id: 1256, word: 'bend', translation: 'band' },
                { id: 1257, word: 'melodija', translation: 'melodi' },
                { id: 1258, word: 'ritam', translation: 'rytm' },
                { id: 1259, word: 'pjevač', translation: 'sångare' },
                { id: 1260, word: 'nota', translation: 'not' },
            ]
        },
        social_media: {
            title: 'Društvene mreže',
            description: 'Pojmovi vezani za društvene mreže.',
            swedish: 'Sociala medier',
            items: [
                { id: 1261, word: 'profil', translation: 'profil' },
                { id: 1262, word: 'objava', translation: 'inlägg' },
                { id: 1263, word: 'pratilac', translation: 'följare' },
                { id: 1264, word: 'lajk', translation: 'gilla' },
                { id: 1265, word: 'komentar', translation: 'kommentar' },
                { id: 1266, word: 'hashtag', translation: 'hashtag' },
                { id: 1267, word: 'influenser', translation: 'influencer' },
                { id: 1268, word: 'šerovati', translation: 'dela' },
                { id: 1269, word: 'story', translation: 'händelse' },
                { id: 1270, word: 'notifikacija', translation: 'notis' },
            ]
        },
        environment: {
            title: 'Okoliš',
            description: 'Pojmovi o zaštiti okoliša.',
            swedish: 'Miljö',
            items: [
                { id: 1271, word: 'reciklaža', translation: 'återvinning' },
                { id: 1272, word: 'zagađenje', translation: 'förorening' },
                { id: 1273, word: 'planeta', translation: 'planet' },
                { id: 1274, word: 'energija', translation: 'energi' },
                { id: 1275, word: 'klimatske promjene', translation: 'klimatförändringar' },
                { id: 1276, word: 'smeće', translation: 'sopor' },
                { id: 1277, word: 'zaštita', translation: 'skydd' },
                { id: 1278, word: 'održivi razvoj', translation: 'hållbar utveckling' },
                { id: 1279, word: 'štedjeti', translation: 'spara' },
                { id: 1280, word: 'obnovljivi izvori', translation: 'förnybara källor' },
            ]
        },
        art_culture: {
            title: 'Umjetnost i kultura',
            description: 'Pojmovi iz umjetnosti i kulture.',
            swedish: 'Konst och kultur',
            items: [
                { id: 1281, word: 'slika', translation: 'målning' },
                { id: 1282, word: 'skulptura', translation: 'skulptur' },
                { id: 1283, word: 'muzej', translation: 'museum' },
                { id: 1284, word: 'pozorište', translation: 'teater' },
                { id: 1285, word: 'film', translation: 'film' },
                { id: 1286, word: 'književnost', translation: 'litteratur' },
                { id: 1287, word: 'tradicija', translation: 'tradition' },
                { id: 1288, word: 'izložba', translation: 'utställning' },
                { id: 1289, word: 'naslijeđe', translation: 'arv' },
                { id: 1290, word: 'ples', translation: 'dans' },
            ]
        },
        science: {
            title: 'Nauka',
            description: 'Osnovni naučni pojmovi.',
            swedish: 'Vetenskap',
            items: [
                { id: 1291, word: 'eksperiment', translation: 'experiment' },
                { id: 1292, word: 'hemija', translation: 'kemi' },
                { id: 1293, word: 'fizika', translation: 'fysik' },
                { id: 1294, word: 'biologija', translation: 'biologi' },
                { id: 1295, word: 'svemir', translation: 'universum' },
                { id: 1296, word: 'DNK', translation: 'DNA' },
                { id: 1297, word: 'gravitacija', translation: 'gravitation' },
                { id: 1298, word: 'atom', translation: 'atom' },
                { id: 1299, word: 'teleskop', translation: 'teleskop' },
                { id: 1300, word: 'mikroskop', translation: 'mikroskop' },
            ]
        },
    },
};

// ========= CROATIAN DATA =========
const croatianVocabularyData = {
    '1-3': {
        family: {
            title: 'Obitelj',
            description: 'Nauči riječi za članove obitelji.',
            swedish: 'Familj',
            items: [
                { id: 2001, word: 'majka', translation: 'mamma' },
                { id: 2002, word: 'otac', translation: 'pappa' },
                { id: 2003, word: 'sestra', translation: 'syster' },
                { id: 2004, word: 'brat', translation: 'bror' },
                { id: 2005, word: 'baka', translation: 'farmor/mormor' },
                { id: 2006, word: 'djed', translation: 'farfar/morfar' },
                { id: 2007, word: 'teta', translation: 'moster/faster' },
                { id: 2008, word: 'stric', translation: 'farbror' },
                { id: 2009, word: 'ujak', translation: 'morbror' },
                { id: 2010, word: 'beba', translation: 'bebis' },
            ],
        },
        colors: {
            title: 'Boje',
            description: 'Otkrij nazive za različite boje.',
            swedish: 'Färger',
            items: [
                { id: 2011, word: 'crvena', translation: 'röd' },
                { id: 2012, word: 'plava', translation: 'blå' },
                { id: 2013, word: 'zelena', translation: 'grön' },
                { id: 2014, word: 'žuta', translation: 'gul' },
                { id: 2015, word: 'crna', translation: 'svart' },
                { id: 2016, word: 'bijela', translation: 'vit' },
                { id: 2017, word: 'narančasta', translation: 'orange' },
                { id: 2018, word: 'ljubičasta', translation: 'lila' },
                { id: 2019, word: 'smeđa', translation: 'brun' },
                { id: 2020, word: 'siva', translation: 'grå' },
            ],
        },
        animals: {
            title: 'Životinje',
            description: 'Nauči nazive domaćih i divljih životinja.',
            swedish: 'Djur',
            items: [
                { id: 2021, word: 'pas', translation: 'hund' },
                { id: 2022, word: 'mačka', translation: 'katt' },
                { id: 2023, word: 'ptica', translation: 'fågel' },
                { id: 2024, word: 'riba', translation: 'fisk' },
                { id: 2025, word: 'konj', translation: 'häst' },
                { id: 2026, word: 'krava', translation: 'ko' },
                { id: 2027, word: 'lav', translation: 'lejon' },
                { id: 2028, word: 'tigar', translation: 'tiger' },
                { id: 2029, word: 'medvjed', translation: 'björn' },
                { id: 2030, word: 'zec', translation: 'kanin' },
            ]
        },
        toys: {
            title: 'Igračke',
            description: 'Nazivi za popularne dječje igračke.',
            swedish: 'Leksaker',
            items: [
                { id: 2031, word: 'lopta', translation: 'boll' },
                { id: 2032, word: 'lutka', translation: 'docka' },
                { id: 2033, word: 'autić', translation: 'bil' },
                { id: 2034, word: 'kocke', translation: 'klossar' },
                { id: 2035, word: 'medvjedić', translation: 'nalle' },
                { id: 2036, word: 'robot', translation: 'robot' },
                { id: 2037, word: 'zrakoplov', translation: 'flygplan' },
                { id: 2038, word: 'vlakić', translation: 'tåg' },
                { id: 2039, word: 'slagalica', translation: 'pussel' },
                { id: 2040, word: 'zmaj', translation: 'drake' },
            ]
        },
        nature: {
            title: 'Priroda',
            description: 'Osnovni pojmovi iz prirode.',
            swedish: 'Natur',
            items: [
                { id: 2041, word: 'sunce', translation: 'sol' },
                { id: 2042, word: 'mjesec', translation: 'måne' },
                { id: 2043, word: 'zvijezda', translation: 'stjärna' },
                { id: 2044, word: 'stablo', translation: 'träd' },
                { id: 2045, word: 'cvijet', translation: 'blomma' },
                { id: 2046, word: 'rijeka', translation: 'flod' },
                { id: 2047, word: 'planina', translation: 'berg' },
                { id: 2048, word: 'nebo', translation: 'himmel' },
                { id: 2049, word: 'kiša', translation: 'regn' },
                { id: 2050, word: 'snijeg', translation: 'snö' },
            ]
        },
         food_1_3: {
            title: 'Hrana',
            description: 'Osnovne vrste hrane.',
            swedish: 'Mat',
            items: [
                { id: 2051, word: 'kruh', translation: 'bröd' },
                { id: 2052, word: 'mlijeko', translation: 'mjölk' },
                { id: 2053, word: 'jabuka', translation: 'äpple' },
                { id: 2054, word: 'banana', translation: 'banan' },
                { id: 2055, word: 'voda', translation: 'vatten' },
                { id: 2056, word: 'sir', translation: 'ost' },
                { id: 2057, word: 'jaje', translation: 'ägg' },
                { id: 2058, word: 'juha', translation: 'soppa' },
                { id: 2059, word: 'kolač', translation: 'kaka' },
                { id: 2060, word: 'piletina', translation: 'kyckling' },
            ]
        },
        school_1_3: {
            title: 'Škola',
            description: 'Osnovni školski pribor.',
            swedish: 'Skola',
            items: [
                { id: 2061, word: 'knjiga', translation: 'bok' },
                { id: 2062, word: 'olovka', translation: 'penna' },
                { id: 2063, word: 'gumica', translation: 'suddgummi' },
                { id: 2064, word: 'stolica', translation: 'stol' },
                { id: 2065, word: 'stol', translation: 'bord' },
                { id: 2066, word: 'učiteljica', translation: 'lärare' },
                { id: 2067, word: 'učenik', translation: 'elev' },
                { id: 2068, word: 'torba', translation: 'väska' },
                { id: 2069, word: 'škarice', translation: 'sax' },
                { id: 2070, word: 'papir', translation: 'papper' },
            ]
        },
        clothes_1_3: {
            title: 'Odjeća',
            description: 'Osnovni odjevni predmeti.',
            swedish: 'Kläder',
            items: [
                { id: 2071, word: 'majica', translation: 't-shirt' },
                { id: 2072, word: 'hlače', translation: 'byxor' },
                { id: 2073, word: 'haljina', translation: 'klänning' },
                { id: 2074, word: 'jakna', translation: 'jacka' },
                { id: 2075, word: 'cipele', translation: 'skor' },
                { id: 2076, word: 'čarape', translation: 'strumpor' },
                { id: 2077, word: 'kapa', translation: 'mössa' },
                { id: 2078, word: 'šal', translation: 'halsduk' },
                { id: 2079, word: 'rukavice', translation: 'handskar' },
                { id: 2080, word: 'suknja', translation: 'kjol' },
            ]
        },
    },
    '4-6': {
        school: {
            title: 'Škola',
            description: 'Riječi vezane za školu i pribor.',
            swedish: 'Skola',
            items: [
                { id: 2101, word: 'učionica', translation: 'klassrum' },
                { id: 2102, word: 'ploča', translation: 'tavla' },
                { id: 2103, word: 'bilježnica', translation: 'skrivbok' },
                { id: 2104, word: 'pernica', translation: 'pennskrin' },
                { id: 2105, word: 'odmor', translation: 'rast' },
                { id: 2106, word: 'domaća zadaća', translation: 'läxa' },
                { id: 2107, word: 'povijest', translation: 'historia' },
                { id: 2108, word: 'zemljopis', translation: 'geografi' },
                { id: 2109, word: 'matematika', translation: 'matematik' },
                { id: 2110, word: 'ravnalo', translation: 'linjal' },
            ]
        },
        food: {
            title: 'Hrana i piće',
            description: 'Nazivi za obroke, namirnice i pića.',
            swedish: 'Mat och dryck',
            items: [
                { id: 2111, word: 'doručak', translation: 'frukost' },
                { id: 2112, word: 'ručak', translation: 'lunch' },
                { id: 2113, word: 'večera', translation: 'middag' },
                { id: 2114, word: 'kruh', translation: 'bröd' },
                { id: 2115, word: 'mlijeko', translation: 'mjölk' },
                { id: 2116, word: 'voda', translation: 'vatten' },
                { id: 2117, word: 'sok', translation: 'juice' },
                { id: 2118, word: 'meso', translation: 'kött' },
                { id: 2119, word: 'povrće', translation: 'grönsaker' },
                { id: 2120, word: 'voće', translation: 'frukt' },
            ]
        },
        hobbies: {
            title: 'Hobiji',
            description: 'Riječi za različite hobije i slobodne aktivnosti.',
            swedish: 'Fritidsintressen',
            items: [
                { id: 2121, word: 'čitanje', translation: 'läsning' },
                { id: 2122, word: 'pjevanje', translation: 'sång' },
                { id: 2123, word: 'ples', translation: 'dans' },
                { id: 2124, word: 'crtanje', translation: 'teckning' },
                { id: 2125, word: 'nogomet', translation: 'fotboll' },
                { id: 2126, word: 'košarka', translation: 'basket' },
                { id: 2127, word: 'sviranje gitare', translation: 'gitarrspel' },
                { id: 2128, word: 'gledanje filmova', translation: 'filmtittande' },
                { id: 2129, word: 'planinarenje', translation: 'vandring' },
                { id: 2130, word: 'igranje igara', translation: 'dataspel' },
            ]
        },
        city: {
            title: 'Grad',
            description: 'Nazivi za mjesta i objekte u gradu.',
            swedish: 'Stad',
            items: [
                { id: 2131, word: 'ulica', translation: 'gata' },
                { id: 2132, word: 'trg', translation: 'torg' },
                { id: 2133, word: 'trgovina', translation: 'affär' },
                { id: 2134, word: 'bolnica', translation: 'sjukhus' },
                { id: 2135, word: 'park', translation: 'park' },
                { id: 2136, word: 'most', translation: 'bro' },
                { id: 2137, word: 'semafor', translation: 'trafikljus' },
                { id: 2138, word: 'zgrada', translation: 'byggnad' },
                { id: 2139, word: 'kino', translation: 'bio' },
                { id: 2140, word: 'pošta', translation: 'postkontor' },
            ]
        },
        clothes: {
            title: 'Odjeća',
            description: 'Nazivi za različite odjevne predmete.',
            swedish: 'Kläder',
            items: [
                { id: 2141, word: 'majica', translation: 't-shirt' },
                { id: 2142, word: 'hlače', translation: 'byxor' },
                { id: 2143, word: 'haljina', translation: 'klänning' },
                { id: 2144, word: 'jakna', translation: 'jacka' },
                { id: 2145, word: 'cipele', translation: 'skor' },
                { id: 2146, word: 'čarape', translation: 'strumpor' },
                { id: 2147, word: 'šešir', translation: 'hatt' },
                { id: 2148, word: 'šal', translation: 'halsduk' },
                { id: 2149, word: 'rukavice', translation: 'handskar' },
                { id: 2150, word: 'pulover', translation: 'tröja' },
            ]
        },
        body_4_6: {
            title: 'Ljudsko tijelo',
            description: 'Osnovni dijelovi tijela.',
            swedish: 'Människokroppen',
            items: [
                { id: 2151, word: 'glava', translation: 'huvud' },
                { id: 2152, word: 'ruka', translation: 'arm/hand' },
                { id: 2153, word: 'noga', translation: 'ben/fot' },
                { id: 2154, word: 'trbuh', translation: 'mage' },
                { id: 2155, word: 'leđa', translation: 'rygg' },
                { id: 2156, word: 'oko', translation: 'öga' },
                { id: 2157, word: 'uho', translation: 'öra' },
                { id: 2158, word: 'nos', translation: 'näsa' },
                { id: 2159, word: 'usta', translation: 'mun' },
                { id: 2160, word: 'kosa', translation: 'hår' },
            ]
        },
        sports: {
            title: 'Sport',
            description: 'Nazivi za popularne sportove.',
            swedish: 'Sport',
            items: [
                { id: 2161, word: 'nogomet', translation: 'fotboll' },
                { id: 2162, word: 'košarka', translation: 'basket' },
                { id: 2163, word: 'tenis', translation: 'tennis' },
                { id: 2164, word: 'plivanje', translation: 'simning' },
                { id: 2165, word: 'odbojka', translation: 'volleyboll' },
                { id: 2166, word: 'atletika', translation: 'friidrott' },
                { id: 2167, word: 'skijanje', translation: 'skidåkning' },
                { id: 2168, word: 'rukomet', translation: 'handboll' },
                { id: 2169, word: 'gimnastika', translation: 'gymnastik' },
                { id: 2170, word: 'biciklizam', translation: 'cykling' },
            ]
        },
        holidays: {
            title: 'Blagdani',
            description: 'Nazivi za blagdane i proslave.',
            swedish: 'Högtider',
            items: [
                { id: 2171, word: 'rođendan', translation: 'födelsedag' },
                { id: 2172, word: 'Nova godina', translation: 'nyår' },
                { id: 2173, word: 'blagdan', translation: 'helgdag' },
                { id: 2174, word: 'Božić', translation: 'jul' },
                { id: 2175, word: 'Uskrs', translation: 'påsk' },
                { id: 2176, word: 'praznici', translation: 'lov' },
                { id: 2177, word: 'dar', translation: 'present' },
                { id: 2178, word: 'proslava', translation: 'firande' },
                { id: 2179, word: 'obljetnica', translation: 'årsdag' },
                { id: 2180, word: 'vatromet', translation: 'fyrverkeri' },
            ]
        },
        calendar: {
            title: 'Mjeseci i dani',
            description: 'Nazivi za dane u tjednu i mjesece.',
            swedish: 'Månader och dagar',
            items: [
                { id: 2181, word: 'ponedjeljak', translation: 'måndag' },
                { id: 2182, word: 'utorak', translation: 'tisdag' },
                { id: 2183, word: 'srijeda', translation: 'onsdag' },
                { id: 2184, word: 'siječanj', translation: 'januari' },
                { id: 2185, word: 'veljača', translation: 'februari' },
                { id: 2186, word: 'ožujak', translation: 'mars' },
                { id: 2187, word: 'tjedan', translation: 'vecka' },
                { id: 2188, word: 'mjesec', translation: 'månad' },
                { id: 2189, word: 'godina', translation: 'år' },
                { id: 2190, word: 'vikend', translation: 'helg' },
            ]
        },
    },
    '7-9': {
        body: {
            title: 'Ljudsko tijelo',
            description: 'Dijelovi ljudskog tijela.',
            swedish: 'Människokroppen',
            items: [
                { id: 2201, word: 'glava', translation: 'huvud' },
                { id: 2202, word: 'srce', translation: 'hjärta' },
                { id: 2203, word: 'pluća', translation: 'lungor' },
                { id: 2204, word: 'mozak', translation: 'hjärna' },
                { id: 2205, word: 'želudac', translation: 'mage' },
                { id: 2206, word: 'kost', translation: 'ben (skelett)' },
                { id: 2207, word: 'mišić', translation: 'muskel' },
                { id: 2208, word: 'koža', translation: 'hud' },
                { id: 2209, word: 'krv', translation: 'blod' },
                { id: 2210, word: 'koljeno', translation: 'knä' },
            ]
        },
        technology: {
            title: 'Tehnologija',
            description: 'Riječi iz svijeta tehnologije.',
            swedish: 'Teknologi',
            items: [
                { id: 2211, word: 'računalo', translation: 'dator' },
                { id: 2212, word: 'mobitel', translation: 'mobiltelefon' },
                { id: 2213, word: 'internet', translation: 'internet' },
                { id: 2214, word: 'aplikacija', translation: 'applikation' },
                { id: 2215, word: 'lozinka', translation: 'lösenord' },
                { id: 2216, word: 'zaslon', translation: 'skärm' },
                { id: 2217, word: 'tipkovnica', translation: 'tangentbord' },
                { id: 2218, word: 'miš', translation: 'mus' },
                { id: 2219, word: 'poruka', translation: 'meddelande' },
                { id: 2220, word: 'punjač', translation: 'laddare' },
            ]
        },
        professions: {
            title: 'Zanimanja',
            description: 'Nazivi za različita zanimanja.',
            swedish: 'Yrken',
            items: [
                { id: 2221, word: 'liječnik', translation: 'läkare' },
                { id: 2222, word: 'učitelj', translation: 'lärare' },
                { id: 2223, word: 'inženjer', translation: 'ingenjör' },
                { id: 2224, word: 'programer', translation: 'programmerare' },
                { id: 2225, word: 'umjetnik', translation: 'konstnär' },
                { id: 2226, word: 'policajac', translation: 'polis' },
                { id: 2227, word: 'vatrogasac', translation: 'brandman' },
                { id: 2228, word: 'kuhar', translation: 'kock' },
                { id: 2229, word: 'novinar', translation: 'journalist' },
                { id: 2230, word: 'odvjetnik', translation: 'advokat' },
            ]
        },
        emotions: {
            title: 'Osjećaji',
            description: 'Riječi koje opisuju kako se osjećamo.',
            swedish: 'Känslor',
            items: [
                { id: 2231, word: 'sretan', translation: 'glad' },
                { id: 2232, word: 'tužan', translation: 'ledsen' },
                { id: 2233, word: 'ljutit', translation: 'arg' },
                { id: 2234, word: 'uplašen', translation: 'rädd' },
                { id: 2235, word: 'iznenađen', translation: 'förvånad' },
                { id: 2236, word: 'uzbuđen', translation: 'exalterad' },
                { id: 2237, word: 'umoran', translation: 'trött' },
                { id: 2238, word: 'ponosan', translation: 'stolt' },
                { id: 2239, word: 'zabrinut', translation: 'orolig' },
                { id: 2240, word: 'usamljen', translation: 'ensam' },
            ]
        },
        travel: {
            title: 'Putovanje',
            description: 'Riječi vezane za putovanja i promet.',
            swedish: 'Resor',
            items: [
                { id: 2241, word: 'zračna luka', translation: 'flygplats' },
                { id: 2242, word: 'putovnica', translation: 'pass' },
                { id: 2243, word: 'karta', translation: 'biljett' },
                { id: 2244, word: 'hotel', translation: 'hotell' },
                { id: 2245, word: 'kovčeg', translation: 'resväska' },
                { id: 2246, word: 'plaža', translation: 'strand' },
                { id: 2247, word: 'turist', translation: 'turist' },
                { id: 2248, word: 'godišnji odmor', translation: 'semester' },
                { id: 2249, word: 'vlak', translation: 'tåg' },
                { id: 2250, word: 'autobus', translation: 'buss' },
            ]
        },
        music: {
            title: 'Glazba',
            description: 'Riječi iz svijeta glazbe.',
            swedish: 'Musik',
            items: [
                { id: 2251, word: 'gitara', translation: 'gitarr' },
                { id: 2252, word: 'glasovir', translation: 'piano' },
                { id: 2253, word: 'bubnjevi', translation: 'trummor' },
                { id: 2254, word: 'pjesma', translation: 'låt' },
                { id: 2255, word: 'koncert', translation: 'konsert' },
                { id: 2256, word: 'sastav', translation: 'band' },
                { id: 2257, word: 'melodija', translation: 'melodi' },
                { id: 2258, word: 'ritam', translation: 'rytm' },
                { id: 2259, word: 'pjevač', translation: 'sångare' },
                { id: 2260, word: 'nota', translation: 'not' },
            ]
        },
        social_media: {
            title: 'Društvene mreže',
            description: 'Pojmovi vezani za društvene mreže.',
            swedish: 'Sociala medier',
            items: [
                { id: 2261, word: 'profil', translation: 'profil' },
                { id: 2262, word: 'objava', translation: 'inlägg' },
                { id: 2263, word: 'pratitelj', translation: 'följare' },
                { id: 2264, word: 'sviđanje', translation: 'gilla' },
                { id: 2265, word: 'komentar', translation: 'kommentar' },
                { id: 2266, word: 'oznaka', translation: 'hashtag' },
                { id: 2267, word: 'influencer', translation: 'influencer' },
                { id: 2268, word: 'dijeliti', translation: 'dela' },
                { id: 2269, word: 'priča', translation: 'händelse' },
                { id: 2270, word: 'obavijest', translation: 'notis' },
            ]
        },
        environment: {
            title: 'Okoliš',
            description: 'Pojmovi o zaštiti okoliša.',
            swedish: 'Miljö',
            items: [
                { id: 2271, word: 'recikliranje', translation: 'återvinning' },
                { id: 2272, word: 'onečišćenje', translation: 'förorening' },
                { id: 2273, word: 'planet', translation: 'planet' },
                { id: 2274, word: 'energija', translation: 'energi' },
                { id: 2275, word: 'klimatske promjene', translation: 'klimatförändringar' },
                { id: 2276, word: 'otpad', translation: 'sopor' },
                { id: 2277, word: 'zaštita', translation: 'skydd' },
                { id: 2278, word: 'održivi razvoj', translation: 'hållbar utveckling' },
                { id: 2279, word: 'štedjeti', translation: 'spara' },
                { id: 2280, word: 'obnovljivi izvori', translation: 'förnybara källor' },
            ]
        },
        art_culture: {
            title: 'Umjetnost i kultura',
            description: 'Pojmovi iz umjetnosti i kulture.',
            swedish: 'Konst och kultur',
            items: [
                { id: 2281, word: 'slika', translation: 'målning' },
                { id: 2282, word: 'kip', translation: 'skulptur' },
                { id: 2283, word: 'muzej', translation: 'museum' },
                { id: 2284, word: 'kazalište', translation: 'teater' },
                { id: 2285, word: 'film', translation: 'film' },
                { id: 2286, word: 'književnost', translation: 'litteratur' },
                { id: 2287, word: 'tradicija', translation: 'tradition' },
                { id: 2288, word: 'izložba', translation: 'utställning' },
                { id: 2289, word: 'baština', translation: 'arv' },
                { id: 2290, word: 'ples', translation: 'dans' },
            ]
        },
        science: {
            title: 'Znanost',
            description: 'Osnovni znanstveni pojmovi.',
            swedish: 'Vetenskap',
            items: [
                { id: 2291, word: 'pokus', translation: 'experiment' },
                { id: 2292, word: 'kemija', translation: 'kemi' },
                { id: 2293, word: 'fizika', translation: 'fysik' },
                { id: 2294, word: 'biologija', translation: 'biologi' },
                { id: 2295, word: 'svemir', translation: 'universum' },
                { id: 2296, word: 'DNK', translation: 'DNA' },
                { id: 2297, word: 'gravitacija', translation: 'gravitation' },
                { id: 2298, word: 'atom', translation: 'atom' },
                { id: 2299, word: 'teleskop', translation: 'teleskop' },
                { id: 2300, word: 'mikroskop', translation: 'mikroskop' },
            ]
        },
    },
};

// ========= SERBIAN DATA =========
const serbianVocabularyData = {
    '1-3': {
        family: {
            title: 'Porodica',
            description: 'Nauči reči za članove porodice.',
            swedish: 'Familj',
            items: [
                { id: 3001, word: 'majka', translation: 'mamma' },
                { id: 3002, word: 'otac', translation: 'pappa' },
                { id: 3003, word: 'sestra', translation: 'syster' },
                { id: 3004, word: 'brat', translation: 'bror' },
                { id: 3005, word: 'baka', translation: 'farmor/mormor' },
                { id: 3006, word: 'deka', translation: 'farfar/morfar' },
                { id: 3007, word: 'tetka', translation: 'moster/faster' },
                { id: 3008, word: 'stric', translation: 'farbror' },
                { id: 3009, word: 'ujak', translation: 'morbror' },
                { id: 3010, word: 'beba', translation: 'bebis' },
            ],
        },
        colors: {
            title: 'Boje',
            description: 'Otkrij nazive za različite boje.',
            swedish: 'Färger',
            items: [
                { id: 3011, word: 'crvena', translation: 'röd' },
                { id: 3012, word: 'plava', translation: 'blå' },
                { id: 3013, word: 'zelena', translation: 'grön' },
                { id: 3014, word: 'žuta', translation: 'gul' },
                { id: 3015, word: 'crna', translation: 'svart' },
                { id: 3016, word: 'bela', translation: 'vit' },
                { id: 3017, word: 'narandžasta', translation: 'orange' },
                { id: 3018, word: 'ljubičasta', translation: 'lila' },
                { id: 3019, word: 'braon', translation: 'brun' },
                { id: 3020, word: 'siva', translation: 'grå' },
            ],
        },
        animals: {
            title: 'Životinje',
            description: 'Nauči nazive domaćih i divljih životinja.',
            swedish: 'Djur',
            items: [
                { id: 3021, word: 'pas', translation: 'hund' },
                { id: 3022, word: 'mačka', translation: 'katt' },
                { id: 3023, word: 'ptica', translation: 'fågel' },
                { id: 3024, word: 'riba', translation: 'fisk' },
                { id: 3025, word: 'konj', translation: 'häst' },
                { id: 3026, word: 'krava', translation: 'ko' },
                { id: 3027, word: 'lav', translation: 'lejon' },
                { id: 3028, word: 'tigar', translation: 'tiger' },
                { id: 3029, word: 'medved', translation: 'björn' },
                { id: 3030, word: 'zec', translation: 'kanin' },
            ]
        },
        toys: {
            title: 'Igračke',
            description: 'Nazivi za popularne dečije igračke.',
            swedish: 'Leksaker',
            items: [
                { id: 3031, word: 'lopta', translation: 'boll' },
                { id: 3032, word: 'lutka', translation: 'docka' },
                { id: 3033, word: 'auto', translation: 'bil' },
                { id: 3034, word: 'kocke', translation: 'klossar' },
                { id: 3035, word: 'meda', translation: 'nalle' },
                { id: 3036, word: 'robot', translation: 'robot' },
                { id: 3037, word: 'avion', translation: 'flygplan' },
                { id: 3038, word: 'vozić', translation: 'tåg' },
                { id: 3039, word: 'slagalica', translation: 'pussel' },
                { id: 3040, word: 'zmaj', translation: 'drake' },
            ]
        },
        nature: {
            title: 'Priroda',
            description: 'Osnovni pojmovi iz prirode.',
            swedish: 'Natur',
            items: [
                { id: 3041, word: 'sunce', translation: 'sol' },
                { id: 3042, word: 'mesec', translation: 'måne' },
                { id: 3043, word: 'zvezda', translation: 'stjärna' },
                { id: 3044, word: 'drvo', translation: 'träd' },
                { id: 3045, word: 'cvet', translation: 'blomma' },
                { id: 3046, word: 'reka', translation: 'flod' },
                { id: 3047, word: 'planina', translation: 'berg' },
                { id: 3048, word: 'nebo', translation: 'himmel' },
                { id: 3049, word: 'kiša', translation: 'regn' },
                { id: 3050, word: 'sneg', translation: 'snö' },
            ]
        },
        food_1_3: {
            title: 'Hrana',
            description: 'Osnovne vrste hrane.',
            swedish: 'Mat',
            items: [
                { id: 3051, word: 'hleb', translation: 'bröd' },
                { id: 3052, word: 'mleko', translation: 'mjölk' },
                { id: 3053, word: 'jabuka', translation: 'äpple' },
                { id: 3054, word: 'banana', translation: 'banan' },
                { id: 3055, word: 'voda', translation: 'vatten' },
                { id: 3056, word: 'sir', translation: 'ost' },
                { id: 3057, word: 'jaje', translation: 'ägg' },
                { id: 3058, word: 'supa', translation: 'soppa' },
                { id: 3059, word: 'kolač', translation: 'kaka' },
                { id: 3060, word: 'piletina', translation: 'kyckling' },
            ]
        },
        school_1_3: {
            title: 'Škola',
            description: 'Osnovni školski pribor.',
            swedish: 'Skola',
            items: [
                { id: 3061, word: 'knjiga', translation: 'bok' },
                { id: 3062, word: 'olovka', translation: 'penna' },
                { id: 3063, word: 'gumica', translation: 'suddgummi' },
                { id: 3064, word: 'stolica', translation: 'stol' },
                { id: 3065, word: 'sto', translation: 'bord' },
                { id: 3066, word: 'učiteljica', translation: 'lärare' },
                { id: 3067, word: 'učenik', translation: 'elev' },
                { id: 3068, word: 'torba', translation: 'väska' },
                { id: 3069, word: 'makaze', translation: 'sax' },
                { id: 3070, word: 'papir', translation: 'papper' },
            ]
        },
        clothes_1_3: {
            title: 'Odeća',
            description: 'Osnovni odevni predmeti.',
            swedish: 'Kläder',
            items: [
                { id: 3071, word: 'majica', translation: 't-shirt' },
                { id: 3072, word: 'pantalone', translation: 'byxor' },
                { id: 3073, word: 'haljina', translation: 'klänning' },
                { id: 3074, word: 'jakna', translation: 'jacka' },
                { id: 3075, word: 'cipele', translation: 'skor' },
                { id: 3076, word: 'čarape', translation: 'strumpor' },
                { id: 3077, word: 'kapa', translation: 'mössa' },
                { id: 3078, word: 'šal', translation: 'halsduk' },
                { id: 3079, word: 'rukavice', translation: 'handskar' },
                { id: 3080, word: 'suknja', translation: 'kjol' },
            ]
        },
    },
    '4-6': {
        school: {
            title: 'Škola',
            description: 'Reči vezane za školu i pribor.',
            swedish: 'Skola',
            items: [
                { id: 3101, word: 'učionica', translation: 'klassrum' },
                { id: 3102, word: 'tabla', translation: 'tavla' },
                { id: 3103, word: 'sveska', translation: 'skrivbok' },
                { id: 3104, word: 'pernica', translation: 'pennskrin' },
                { id: 3105, word: 'odmor', translation: 'rast' },
                { id: 3106, word: 'domaći zadatak', translation: 'läxa' },
                { id: 3107, word: 'istorija', translation: 'historia' },
                { id: 3108, word: 'geografija', translation: 'geografi' },
                { id: 3109, word: 'matematika', translation: 'matematik' },
                { id: 3110, word: 'lenjir', translation: 'linjal' },
            ]
        },
        food: {
            title: 'Hrana i piće',
            description: 'Nazivi za obroke, namirnice i pića.',
            swedish: 'Mat och dryck',
            items: [
                { id: 3111, word: 'doručak', translation: 'frukost' },
                { id: 3112, word: 'ručak', translation: 'lunch' },
                { id: 3113, word: 'večera', translation: 'middag' },
                { id: 3114, word: 'hleb', translation: 'bröd' },
                { id: 3115, word: 'mleko', translation: 'mjölk' },
                { id: 3116, word: 'voda', translation: 'vatten' },
                { id: 3117, word: 'sok', translation: 'juice' },
                { id: 3118, word: 'meso', translation: 'kött' },
                { id: 3119, word: 'povrće', translation: 'grönsaker' },
                { id: 3120, word: 'voće', translation: 'frukt' },
            ]
        },
        hobbies: {
            title: 'Hobiji',
            description: 'Reči za različite hobije i slobodne aktivnosti.',
            swedish: 'Fritidsintressen',
            items: [
                { id: 3121, word: 'čitanje', translation: 'läsning' },
                { id: 3122, word: 'pevanje', translation: 'sång' },
                { id: 3123, word: 'igranje', translation: 'dans' },
                { id: 3124, word: 'crtanje', translation: 'teckning' },
                { id: 3125, word: 'fudbal', translation: 'fotboll' },
                { id: 3126, word: 'košarka', translation: 'basket' },
                { id: 3127, word: 'sviranje gitare', translation: 'gitarrspel' },
                { id: 3128, word: 'gledanje filmova', translation: 'filmtittande' },
                { id: 3129, word: 'planinarenje', translation: 'vandring' },
                { id: 3130, word: 'igranje igrica', translation: 'dataspel' },
            ]
        },
        city: {
            title: 'Grad',
            description: 'Nazivi za mesta i objekte u gradu.',
            swedish: 'Stad',
            items: [
                { id: 3131, word: 'ulica', translation: 'gata' },
                { id: 3132, word: 'trg', translation: 'torg' },
                { id: 3133, word: 'prodavnica', translation: 'affär' },
                { id: 3134, word: 'bolnica', translation: 'sjukhus' },
                { id: 3135, word: 'park', translation: 'park' },
                { id: 3136, word: 'most', translation: 'bro' },
                { id: 3137, word: 'semafor', translation: 'trafikljus' },
                { id: 3138, word: 'zgrada', translation: 'byggnad' },
                { id: 3139, word: 'bioskop', translation: 'bio' },
                { id: 3140, word: 'pošta', translation: 'postkontor' },
            ]
        },
        clothes: {
            title: 'Odeća',
            description: 'Nazivi za različite odevne predmete.',
            swedish: 'Kläder',
            items: [
                { id: 3141, word: 'majica', translation: 't-shirt' },
                { id: 3142, word: 'pantalone', translation: 'byxor' },
                { id: 3143, word: 'haljina', translation: 'klänning' },
                { id: 3144, word: 'jakna', translation: 'jacka' },
                { id: 3145, word: 'cipele', translation: 'skor' },
                { id: 3146, word: 'čarape', translation: 'strumpor' },
                { id: 3147, word: 'šešir', translation: 'hatt' },
                { id: 3148, word: 'šal', translation: 'halsduk' },
                { id: 3149, word: 'rukavice', translation: 'handskar' },
                { id: 3150, word: 'džemper', translation: 'tröja' },
            ]
        },
        body_4_6: {
            title: 'Ljudsko telo',
            description: 'Osnovni delovi tela.',
            swedish: 'Människokroppen',
            items: [
                { id: 3151, word: 'glava', translation: 'huvud' },
                { id: 3152, word: 'ruka', translation: 'arm/hand' },
                { id: 3153, word: 'noga', translation: 'ben/fot' },
                { id: 3154, word: 'stomak', translation: 'mage' },
                { id: 3155, word: 'leđa', translation: 'rygg' },
                { id: 3156, word: 'oko', translation: 'öga' },
                { id: 3157, word: 'uvo', translation: 'öra' },
                { id: 3158, word: 'nos', translation: 'näsa' },
                { id: 3159, word: 'usta', translation: 'mun' },
                { id: 3160, word: 'kosa', translation: 'hår' },
            ]
        },
        sports: {
            title: 'Sport',
            description: 'Nazivi za popularne sportove.',
            swedish: 'Sport',
            items: [
                { id: 3161, word: 'fudbal', translation: 'fotboll' },
                { id: 3162, word: 'košarka', translation: 'basket' },
                { id: 3163, word: 'tenis', translation: 'tennis' },
                { id: 3164, word: 'plivanje', translation: 'simning' },
                { id: 3165, word: 'odbojka', translation: 'volleyboll' },
                { id: 3166, word: 'atletika', translation: 'friidrott' },
                { id: 3167, word: 'skijanje', translation: 'skidåkning' },
                { id: 3168, word: 'rukomet', translation: 'handboll' },
                { id: 3169, word: 'gimnastika', translation: 'gymnastik' },
                { id: 3170, word: 'biciklizam', translation: 'cykling' },
            ]
        },
        holidays: {
            title: 'Praznici',
            description: 'Nazivi za praznike i proslave.',
            swedish: 'Högtider',
            items: [
                { id: 3171, word: 'rođendan', translation: 'födelsedag' },
                { id: 3172, word: 'Nova godina', translation: 'nyår' },
                { id: 3173, word: 'Bajram', translation: 'Eid' },
                { id: 3174, word: 'Božić', translation: 'jul' },
                { id: 3175, word: 'Uskrs', translation: 'påsk' },
                { id: 3176, word: 'raspust', translation: 'lov' },
                { id: 3177, word: 'poklon', translation: 'present' },
                { id: 3178, word: 'proslava', translation: 'firande' },
                { id: 3179, word: 'godišnjica', translation: 'årsdag' },
                { id: 3180, word: 'vatromet', translation: 'fyrverkeri' },
            ]
        },
        calendar: {
            title: 'Meseci i dani',
            description: 'Nazivi za dane u nedelji i mesece.',
            swedish: 'Månader och dagar',
            items: [
                { id: 3181, word: 'ponedeljak', translation: 'måndag' },
                { id: 3182, word: 'utorak', translation: 'tisdag' },
                { id: 3183, word: 'sreda', translation: 'onsdag' },
                { id: 3184, word: 'januar', translation: 'januari' },
                { id: 3185, word: 'februar', translation: 'februari' },
                { id: 3186, word: 'mart', translation: 'mars' },
                { id: 3187, word: 'nedelja', translation: 'vecka' },
                { id: 3188, word: 'mesec', translation: 'månad' },
                { id: 3189, word: 'godina', translation: 'år' },
                { id: 3190, word: 'vikend', translation: 'helg' },
            ]
        },
    },
    '7-9': {
        body: {
            title: 'Ljudsko telo',
            description: 'Delovi ljudskog tela.',
            swedish: 'Människokroppen',
            items: [
                { id: 3201, word: 'glava', translation: 'huvud' },
                { id: 3202, word: 'srce', translation: 'hjärta' },
                { id: 3203, word: 'pluća', translation: 'lungor' },
                { id: 3204, word: 'mozak', translation: 'hjärna' },
                { id: 3205, word: 'stomak', translation: 'mage' },
                { id: 3206, word: 'kost', translation: 'ben (skelett)' },
                { id: 3207, word: 'mišić', translation: 'muskel' },
                { id: 3208, word: 'koža', translation: 'hud' },
                { id: 3209, word: 'krv', translation: 'blod' },
                { id: 3210, word: 'koleno', translation: 'knä' },
            ]
        },
        technology: {
            title: 'Tehnologija',
            description: 'Reči iz sveta tehnologije.',
            swedish: 'Teknologi',
            items: [
                { id: 3211, word: 'računar', translation: 'dator' },
                { id: 3212, word: 'mobilni telefon', translation: 'mobiltelefon' },
                { id: 3213, word: 'internet', translation: 'internet' },
                { id: 3214, word: 'aplikacija', translation: 'applikation' },
                { id: 3215, word: 'lozinka', translation: 'lösenord' },
                { id: 3216, word: 'ekran', translation: 'skärm' },
                { id: 3217, word: 'tastatura', translation: 'tangentbord' },
                { id: 3218, word: 'miš', translation: 'mus' },
                { id: 3219, word: 'poruka', translation: 'meddelande' },
                { id: 3220, word: 'punjač', translation: 'laddare' },
            ]
        },
        professions: {
            title: 'Zanimanja',
            description: 'Nazivi za različita zanimanja.',
            swedish: 'Yrken',
            items: [
                { id: 3221, word: 'lekar', translation: 'läkare' },
                { id: 3222, word: 'učitelj', translation: 'lärare' },
                { id: 3223, word: 'inženjer', translation: 'ingenjör' },
                { id: 3224, word: 'programer', translation: 'programmerare' },
                { id: 3225, word: 'umetnik', translation: 'konstnär' },
                { id: 3226, word: 'policajac', translation: 'polis' },
                { id: 3227, word: 'vatrogasac', translation: 'brandman' },
                { id: 3228, word: 'kuvar', translation: 'kock' },
                { id: 3229, word: 'novinar', translation: 'journalist' },
                { id: 3230, word: 'advokat', translation: 'advokat' },
            ]
        },
        emotions: {
            title: 'Osećanja',
            description: 'Reči koje opisuju kako se osećamo.',
            swedish: 'Känslor',
            items: [
                { id: 3231, word: 'srećan', translation: 'glad' },
                { id: 3232, word: 'tužan', translation: 'ledsen' },
                { id: 3233, word: 'ljut', translation: 'arg' },
                { id: 3234, word: 'uplašen', translation: 'rädd' },
                { id: 3235, word: 'iznenađen', translation: 'förvånad' },
                { id: 3236, word: 'uzbuđen', translation: 'exalterad' },
                { id: 3237, word: 'umoran', translation: 'trött' },
                { id: 3238, word: 'ponosan', translation: 'stolt' },
                { id: 3239, word: 'zabrinut', translation: 'orolig' },
                { id: 3240, word: 'usamljen', translation: 'ensam' },
            ]
        },
        travel: {
            title: 'Putovanje',
            description: 'Reči vezane za putovanja i transport.',
            swedish: 'Resor',
            items: [
                { id: 3241, word: 'aerodrom', translation: 'flygplats' },
                { id: 3242, word: 'pasoš', translation: 'pass' },
                { id: 3243, word: 'karta', translation: 'biljett' },
                { id: 3244, word: 'hotel', translation: 'hotell' },
                { id: 3245, word: 'kofer', translation: 'resväska' },
                { id: 3246, word: 'plaža', translation: 'strand' },
                { id: 3247, word: 'turista', translation: 'turist' },
                { id: 3248, word: 'odmor', translation: 'semester' },
                { id: 3249, word: 'voz', translation: 'tåg' },
                { id: 3250, word: 'autobus', translation: 'buss' },
            ]
        },
        music: {
            title: 'Muzika',
            description: 'Reči iz sveta muzike.',
            swedish: 'Musik',
            items: [
                { id: 3251, word: 'gitara', translation: 'gitarr' },
                { id: 3252, word: 'klavir', translation: 'piano' },
                { id: 3253, word: 'bubnjevi', translation: 'trummor' },
                { id: 3254, word: 'pesma', translation: 'låt' },
                { id: 3255, word: 'koncert', translation: 'konsert' },
                { id: 3256, word: 'bend', translation: 'band' },
                { id: 3257, word: 'melodija', translation: 'melodi' },
                { id: 3258, word: 'ritam', translation: 'rytm' },
                { id: 3259, word: 'pevač', translation: 'sångare' },
                { id: 3260, word: 'nota', translation: 'not' },
            ]
        },
        social_media: {
            title: 'Društvene mreže',
            description: 'Pojmovi vezani za društvene mreže.',
            swedish: 'Sociala medier',
            items: [
                { id: 3261, word: 'profil', translation: 'profil' },
                { id: 3262, word: 'objava', translation: 'inlägg' },
                { id: 3263, word: 'pratilac', translation: 'följare' },
                { id: 3264, word: 'sviđanje', translation: 'gilla' },
                { id: 3265, word: 'komentar', translation: 'kommentar' },
                { id: 3266, word: 'haštag', translation: 'hashtag' },
                { id: 3267, word: 'influenser', translation: 'influencer' },
                { id: 3268, word: 'deliti', translation: 'dela' },
                { id: 3269, word: 'stori', translation: 'händelse' },
                { id: 3270, word: 'obaveštenje', translation: 'notis' },
            ]
        },
        environment: {
            title: 'Životna sredina',
            description: 'Pojmovi o zaštiti životne sredine.',
            swedish: 'Miljö',
            items: [
                { id: 3271, word: 'reciklaža', translation: 'återvinning' },
                { id: 3272, word: 'zagađenje', translation: 'förorening' },
                { id: 3273, word: 'planeta', translation: 'planet' },
                { id: 3274, word: 'energija', translation: 'energi' },
                { id: 3275, word: 'klimatske promene', translation: 'klimatförändringar' },
                { id: 3276, word: 'smeće', translation: 'sopor' },
                { id: 3277, word: 'zaštita', translation: 'skydd' },
                { id: 3278, word: 'održivi razvoj', translation: 'hållbar utveckling' },
                { id: 3279, word: 'štedeti', translation: 'spara' },
                { id: 3280, word: 'obnovljivi izvori', translation: 'förnybara källor' },
            ]
        },
        art_culture: {
            title: 'Umetnost i kultura',
            description: 'Pojmovi iz umetnosti i kulture.',
            swedish: 'Konst och kultur',
            items: [
                { id: 3281, word: 'slika', translation: 'målning' },
                { id: 3282, word: 'skulptura', translation: 'skulptur' },
                { id: 3283, word: 'muzej', translation: 'museum' },
                { id: 3284, word: 'pozorište', translation: 'teater' },
                { id: 3285, word: 'film', translation: 'film' },
                { id: 3286, word: 'književnost', translation: 'litteratur' },
                { id: 3287, word: 'tradicija', translation: 'tradition' },
                { id: 3288, word: 'izložba', translation: 'utställning' },
                { id: 3289, word: 'nasleđe', translation: 'arv' },
                { id: 3290, word: 'ples', translation: 'dans' },
            ]
        },
        science: {
            title: 'Nauka',
            description: 'Osnovni naučni pojmovi.',
            swedish: 'Vetenskap',
            items: [
                { id: 3291, word: 'eksperiment', translation: 'experiment' },
                { id: 3292, word: 'hemija', translation: 'kemi' },
                { id: 3293, word: 'fizika', translation: 'fysik' },
                { id: 3294, word: 'biologija', translation: 'biologi' },
                { id: 3295, word: 'svemir', translation: 'universum' },
                { id: 3296, word: 'DNK', translation: 'DNA' },
                { id: 3297, word: 'gravitacija', translation: 'gravitation' },
                { id: 3298, word: 'atom', translation: 'atom' },
                { id: 3299, word: 'teleskop', translation: 'teleskop' },
                { id: 3300, word: 'mikroskop', translation: 'mikroskop' },
            ]
        },
    },
};


export const vocabularyData: VocabularyData = {
  bosnian: bosnianVocabularyData,
  croatian: croatianVocabularyData,
  serbian: serbianVocabularyData
};

    