import type { VocabularyData } from './types';

export const vocabularyData: VocabularyData = {
  bosnian: {
    '1-3': {
      family: {
        title: 'Porodica',
        description: 'Nauči riječi za članove porodice.',
        swedish: 'Familj',
        items: [
          { id: 1001, word: 'majka', translation: 'mamma' },
          { id: 1002, word: 'otac', translation: 'pappa' },
          { id: 1003, word: 'sestra', translation: 'syster' },
          { id: 1004, word: 'brat', translation: 'bror' },
          { id: 1005, word: 'nana', translation: 'farmor/mormor' },
          { id: 1006, word: 'djed', translation: 'farfar/morfar' },
          { id: 1013, word: 'tetka', translation: 'moster/faster' },
          { id: 1014, word: 'amidža', translation: 'farbror (paternal)' },
          { id: 1015, word: 'daidža', translation: 'morbror (maternal)' },
          { id: 1016, word: 'beba', translation: 'bebis' },
        ],
      },
      colors: {
        title: 'Boje',
        description: 'Otkrij nazive za različite boje.',
        swedish: 'Färger',
        items: [
          { id: 1007, word: 'crvena', translation: 'röd' },
          { id: 1008, word: 'plava', translation: 'blå' },
          { id: 1009, word: 'zelena', translation: 'grön' },
          { id: 1010, word: 'žuta', translation: 'gul' },
          { id: 1011, word: 'crna', translation: 'svart' },
          { id: 1012, word: 'bijela', translation: 'vit' },
          { id: 1017, word: 'narandžasta', translation: 'orange' },
          { id: 1018, word: 'ljubičasta', translation: 'lila' },
          { id: 1019, word: 'smeđa', translation: 'brun' },
          { id: 1020, word: 'siva', translation: 'grå' },
        ],
      },
      food: {
        title: 'Hrana i piće',
        description: 'Istraži riječi vezane za hranu i piće.',
        swedish: 'Mat och dryck',
        items: [
          { id: 21, word: 'kruh/hljeb', translation: 'bröd' },
          { id: 22, word: 'mlijeko', translation: 'mjölk' },
          { id: 1021, word: 'sok', translation: 'juice' },
          { id: 1022, word: 'sir', translation: 'ost' },
          { id: 1023, word: 'meso', translation: 'kött' },
          { id: 1024, word: 'supa', translation: 'soppa' },
          { id: 1025, word: 'kolač', translation: 'kaka' },
          { id: 1026, word: 'pita', translation: 'paj' },
          { id: 1027, word: 'ćevapi', translation: 'ćevapi' },
          { id: 11, word: 'voda', translation: 'vatten' },
          { id: 1033, word: 'riba', translation: 'fisk' },
          { id: 1034, word: 'piletina', translation: 'kyckling' },
          { id: 1035, word: 'salata', translation: 'sallad' },
          { id: 1036, word: 'jaje', translation: 'ägg' },
          { id: 1037, word: 'med', translation: 'honung' },
          { id: 1038, word: 'džem', translation: 'sylt' },
          { id: 1039, word: 'maslac', translation: 'smör' },
          { id: 1040, word: 'šećer', translation: 'socker' },
          { id: 1041, word: 'so', translation: 'salt' },
          { id: 1042, word: 'kafa', translation: 'kaffe' },
          { id: 1043, word: 'čaj', translation: 'te' },
          { id: 1044, word: 'sladoled', translation: 'glass' },
          { id: 1045, word: 'čokolada', translation: 'choklad' },
          { id: 1046, word: 'sendvič', translation: 'smörgås' },
          { id: 1047, word: 'jogurt', translation: 'yoghurt' },
        ],
      },
      animals: {
        title: 'Životinje',
        description: 'Upoznaj se sa nazivima domaćih i divljih životinja.',
        swedish: 'Djur',
        items: [
          { id: 7, word: 'mačka', translation: 'katt' },
          { id: 8, word: 'pas', translation: 'hund' },
          { id: 62, word: 'riba', translation: 'fisk' },
          { id: 1029, word: 'ptica', translation: 'fågel' },
          { id: 1030, word: 'konj', translation: 'häst' },
          { id: 1031, word: 'krava', translation: 'ko' },
          { id: 1032, word: 'ovca', translation: 'får' },
          { id: 34, word: 'medvjed', translation: 'björn' },
          { id: 1028, word: 'lav', translation: 'lejon' },
          { id: 1701, word: 'zec', translation: 'kanin' },
          { id: 1702, word: 'kokoška', translation: 'höna' },
          { id: 1703, word: 'svinja', translation: 'gris' },
          { id: 1704, word: 'vuk', translation: 'varg' },
          { id: 1705, word: 'lisica', translation: 'räv' },
          { id: 1706, word: 'žaba', translation: 'groda' },
          { id: 1707, word: 'zmija', translation: 'orm' },
          { id: 1708, word: 'slon', translation: 'elefant' },
          { id: 1709, word: 'žirafa', translation: 'giraff' },
          { id: 1710, word: 'majmun', translation: 'apa' },
          { id: 1711, word: 'tigar', translation: 'tiger' },
        ],
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 1101, word: 'stolica', translation: 'stol' },
          { id: 1102, word: 'sto', translation: 'bord' },
          { id: 1103, word: 'krevet', translation: 'säng' },
          { id: 1104, word: 'čaša', translation: 'glas' },
          { id: 1105, word: 'tanjir', translation: 'tallrik' },
          { id: 1106, word: 'kašika', translation: 'sked' },
          { id: 1107, word: 'viljuška', translation: 'gaffel' },
          { id: 1119, word: 'prozor', translation: 'fönster' },
          { id: 1120, word: 'vrata', translation: 'dörr' },
          { id: 1712, word: 'sat', translation: 'klocka' },
          { id: 1713, word: 'lampa', translation: 'lampa' },
          { id: 1714, word: 'ormar', translation: 'garderob' },
          { id: 1715, word: 'kauč', translation: 'soffa' },
          { id: 1716, word: 'tepih', translation: 'matta' },
          { id: 1717, word: 'ogledalo', translation: 'spegel' },
          { id: 1718, word: 'ključ', translation: 'nyckel' },
          { id: 1719, word: 'telefon', translation: 'telefon' },
          { id: 1720, word: 'televizor', translation: 'TV' },
          { id: 1721, word: 'računar', translation: 'dator' },
          { id: 1722, word: 'novčanik', translation: 'plånbok' },
          { id: 1723, word: 'naočale', translation: 'glasögon' },
          { id: 1724, word: 'kišobran', translation: 'paraply' },
          { id: 1725, word: 'torba', translation: 'väska' },
          { id: 1726, word: 'sapun', translation: 'tvål' },
          { id: 1727, word: 'peškir', translation: 'handduk' },
          { id: 1728, word: 'jastuk', translation: 'kudde' },
          { id: 1729, word: 'deka', translation: 'filt' },
          { id: 1730, word: 'makaze', translation: 'sax' },
          { id: 1731, word: 'lonac', translation: 'kastrull' },
          { id: 1732, word: 'tava', translation: 'stekpanna' },
          { id: 1733, word: 'nož', translation: 'kniv' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
            { id: 1110, word: 'grad', translation: 'stad' },
            { id: 1111, word: 'selo', translation: 'by' },
            { id: 1112, word: 'ulica', translation: 'gata' },
            { id: 1113, word: 'zgrada', translation: 'byggnad' },
            { id: 1114, word: 'kuća', translation: 'hus' },
            { id: 1115, word: 'park', translation: 'park' },
            { id: 1116, word: 'rijeka', translation: 'flod' },
            { id: 1117, word: 'most', translation: 'bro' },
            { id: 1118, word: 'čaršija', translation: 'basar/marknad' },
            { id: 1121, word: 'igralište', translation: 'lekplats' },
            { id: 1122, word: 'trgovina', translation: 'affär' },
            { id: 1126, word: 'bolnica', translation: 'sjukhus' },
            { id: 1127, word: 'pošta', translation: 'postkontor' },
            { id: 1143, word: 'crkva', translation: 'kyrka' },
            { id: 1174, word: 'džamija', translation: 'moské' },
            { id: 1175, word: 'biblioteka', translation: 'bibliotek' },
            { id: 1176, word: 'aerodrom', translation: 'flygplats' },
            { id: 1177, word: 'stanica', translation: 'station' },
            { id: 1178, word: 'trg', translation: 'torg' },
            { id: 1179, word: 'semafor', translation: 'trafikljus' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Riječi koje koristimo u školi.',
        swedish: 'Skola',
        items: [
          { id: 1123, word: 'učiteljica', translation: 'lärare (kvinnlig)' },
          { id: 1124, word: 'učenik', translation: 'elev' },
          { id: 1125, word: 'tabla', translation: 'tavla' },
          { id: 1128, word: 'knjiga', translation: 'bok' },
          { id: 1129, word: 'odmor', translation: 'rast' },
          { id: 1130, word: 'čas', translation: 'lektion' },
          { id: 1131, word: 'zadaća', translation: 'läxa' },
          { id: 1132, word: 'učionica', translation: 'klassrum' },
          { id: 1108, word: 'sveska', translation: 'anteckningsbok' },
          { id: 1109, word: 'olovka', translation: 'penna' },
          { id: 1180, word: 'gumica', translation: 'suddgummi' },
          { id: 1181, word: 'šiljilo', translation: 'pennvässare' },
          { id: 1182, word: 'pernica', translation: 'pennskrin' },
          { id: 1183, word: 'ruksak', translation: 'ryggsäck' },
          { id: 1184, word: 'matematika', translation: 'matematik' },
          { id: 1185, word: 'jezik', translation: 'språk' },
          { id: 1186, word: 'historija', translation: 'historia' },
          { id: 1187, word: 'geografija', translation: 'geografi' },
          { id: 1188, word: 'sport', translation: 'idrott' },
          { id: 1189, word: 'muzika', translation: 'musik' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Riječi za stvari koje vidimo u prirodi.',
        swedish: 'Natur',
        items: [
          { id: 1133, word: 'sunce', translation: 'sol' },
          { id: 1134, word: 'mjesec', translation: 'måne' },
          { id: 1135, word: 'zvijezda', translation: 'stjärna' },
          { id: 1136, word: 'drvo', translation: 'träd' },
          { id: 1137, word: 'cvijet', translation: 'blomma' },
          { id: 1138, word: 'trava', translation: 'gräs' },
          { id: 1139, word: 'kamen', translation: 'sten' },
          { id: 1140, word: 'planina', translation: 'berg' },
          { id: 1141, word: 'more', translation: 'hav' },
          { id: 1142, word: 'kiša', translation: 'regn' },
          { id: 1190, word: 'snijeg', translation: 'snö' },
          { id: 1191, word: 'vjetar', translation: 'vind' },
          { id: 1192, word: 'oblak', translation: 'moln' },
          { id: 1193, word: 'šuma', translation: 'skog' },
          { id: 1194, word: 'livada', translation: 'äng' },
          { id: 1195, word: 'pijesak', translation: 'sand' },
          { id: 1196, word: 'vatra', translation: 'eld' },
          { id: 1197, word: 'led', translation: 'is' },
          { id: 1198, word: 'jezero', translation: 'sjö' },
          { id: 1199, word: 'potok', translation: 'bäck' },
          { id: 1200, word: 'brdo', translation: 'kulle' },
          { id: 1201, word: 'polje', translation: 'fält' },
          { id: 1202, word: 'ostrvo', translation: 'ö' },
          { id: 1203, word: 'plaža', translation: 'strand' },
          { id: 1204, word: 'nebo', translation: 'himmel' },
        ]
      },
      seasons: {
        title: 'Godišnja doba',
        description: 'Nauči nazive za godišnja doba.',
        swedish: 'Årstider',
        items: [
          { id: 5001, word: 'proljeće', translation: 'vår' },
          { id: 5002, word: 'ljeto', translation: 'sommar' },
          { id: 5003, word: 'jesen', translation: 'höst' },
          { id: 5004, word: 'zima', translation: 'vinter' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Nauči dijelove ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 1144, word: 'glava', translation: 'huvud' },
          { id: 1145, word: 'kosa', translation: 'hår' },
          { id: 1146, word: 'oko', translation: 'öga' },
          { id: 1147, word: 'uho', translation: 'öra' },
          { id: 1148, word: 'nos', translation: 'näsa' },
          { id: 1149, word: 'usta', translation: 'mun' },
          { id: 1150, word: 'zub', translation: 'tand' },
          { id: 1151, word: 'ruka', translation: 'hand/arm' },
          { id: 1152, word: 'noga', translation: 'ben/fot' },
          { id: 1153, word: 'prst', translation: 'finger' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Nazivi za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 1154, word: 'majica', translation: 't-shirt' },
          { id: 1155, word: 'hlače', translation: 'byxor' },
          { id: 1156, word: 'džemper', translation: 'tröja' },
          { id: 1157, word: 'jakna', translation: 'jacka' },
          { id: 1158, word: 'haljina', translation: 'klänning' },
          { id: 1159, word: 'cipele', translation: 'skor' },
          { id: 1160, word: 'patike', translation: 'sneakers' },
          { id: 1161, word: 'čarape', translation: 'strumpor' },
          { id: 1162, word: 'kapa', translation: 'mössa' },
          { id: 1163, word: 'šal', translation: 'halsduk' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Nauči osnovne radnje.',
        swedish: 'Verb',
        items: [
          { id: 1164, word: 'jesti', translation: 'äta' },
          { id: 1165, word: 'piti', translation: 'dricka' },
          { id: 1166, word: 'spavati', translation: 'sova' },
          { id: 1167, word: 'trčati', translation: 'springa' },
          { id: 1168, word: 'hodati', translation: 'gå' },
          { id: 1169, word: 'čitati', translation: 'läsa' },
          { id: 1170, word: 'pisati', translation: 'skriva' },
          { id: 1171, word: 'gledati', translation: 'titta' },
          { id: 1172, word: 'igrati se', translation: 'leka' },
          { id: 1173, word: 'pjevati', translation: 'sjunga' },
          { id: 1210, word: 'crtati', translation: 'rita' },
          { id: 1211, word: 'plivati', translation: 'simma' },
          { id: 1212, word: 'voziti', translation: 'köra' },
          { id: 1213, word: 'sjediti', translation: 'sitta' },
          { id: 1214, word: 'stajati', translation: 'stå' },
          { id: 1215, word: 'skakati', translation: 'hoppa' },
          { id: 1216, word: 'letjeti', translation: 'flyga' },
          { id: 1217, word: 'slušati', translation: 'lyssna' },
          { id: 1218, word: 'govoriti', translation: 'tala' },
          { id: 1219, word: 'raditi', translation: 'arbeta' },
          { id: 1220, word: 'učiti', translation: 'lära sig' },
          { id: 1221, word: 'pitati', translation: 'fråga' },
          { id: 1222, word: 'odgovoriti', translation: 'svara' },
          { id: 1223, word: 'pomoći', translation: 'hjälpa' },
          { id: 1224, word: 'otvoriti', translation: 'öppna' },
          { id: 1225, word: 'zatvoriti', translation: 'stänga' },
          { id: 1226, word: 'kupiti', translation: 'köpa' },
          { id: 1227, word: 'prodati', translation: 'sälja' },
          { id: 1228, word: 'dati', translation: 'ge' },
          { id: 1229, word: 'uzeti', translation: 'ta' },
        ]
      },
      feelingsAndAdjectives: {
        title: 'Osjećaji i pridjevi',
        description: 'Riječi za opisivanje osjećaja i stvari.',
        swedish: 'Känslor och adjektiv',
        items: [
          { id: 1401, word: 'sretan', translation: 'glad' },
          { id: 1402, word: 'tužan', translation: 'ledsen' },
          { id: 1403, word: 'ljut', translation: 'arg' },
          { id: 1404, word: 'velik', translation: 'stor' },
          { id: 1405, word: 'mali', translation: 'liten' },
          { id: 1406, word: 'lijep', translation: 'vacker/fin' },
          { id: 1407, word: 'ružan', translation: 'ful' },
          { id: 1408, word: 'dobar', translation: 'bra/god' },
          { id: 1409, word: 'loš', translation: 'dålig' },
          { id: 1410, word: 'brz', translation: 'snabb' },
          { id: 1411, word: 'spor', translation: 'långsam' },
          { id: 1422, word: 'jak', translation: 'stark' },
          { id: 1423, word: 'slab', translation: 'svag' },
          { id: 1424, word: 'topao', translation: 'varm' },
          { id: 1425, word: 'hladan', translation: 'kall' },
          { id: 1426, word: 'umoran', translation: 'trött' },
          { id: 1427, word: 'gladan', translation: 'hungrig' },
          { id: 1428, word: 'žedan', translation: 'törstig' },
          { id: 1429, word: 'star', translation: 'gammal' },
          { id: 1430, word: 'mlad', translation: 'ung' },
          { id: 1431, word: 'nov', translation: 'ny' },
          { id: 1432, word: 'čist', translation: 'ren' },
          { id: 1433, word: 'prljav', translation: 'smutsig' },
          { id: 1434, word: 'smiješan', translation: 'rolig' },
        ],
      },
      professions: {
        title: 'Zanimanja',
        description: 'Nazivi za različita zanimanja.',
        swedish: 'Yrken',
        items: [
          { id: 1412, word: 'učitelj/učiteljica', translation: 'lärare' },
          { id: 1413, word: 'ljekar/ljekarica', translation: 'läkare' },
          { id: 1414, word: 'policajac/policajka', translation: 'polis' },
          { id: 1415, word: 'vatrogasac', translation: 'brandman' },
          { id: 1416, word: 'kuhar/kuharica', translation: 'kock' },
          { id: 1417, word: 'frizer/frizerka', translation: 'frisör' },
          { id: 1418, word: 'vozač', translation: 'förare/chaufför' },
          { id: 1419, word: 'prodavač/prodavačica', translation: 'försäljare' },
          { id: 1420, word: 'pjevač/pjevačica', translation: 'sångare' },
          { id: 1421, word: 'glumac/glumica', translation: 'skådespelare' },
          { id: 1435, word: 'pekar', translation: 'bagare' },
          { id: 1436, word: 'zubar', translation: 'tandläkare' },
          { id: 1437, word: 'poštar', translation: 'brevhörare' },
          { id: 1438, word: 'slikar', translation: 'målare' },
          { id: 1439, word: 'sportista', translation: 'idrottare' },
          { id: 1440, word: 'pilot', translation: 'pilot' },
          { id: 1441, word: 'inžinjer', translation: 'ingenjör' },
          { id: 1442, word: 'pravnik', translation: 'jurist' },
          { id: 1443, word: 'novinar', translation: 'journalist' },
          { id: 1444, word: 'programer', translation: 'programmerare' },
          { id: 1445, word: 'arhitekta', translation: 'arkitekt' },
          { id: 1446, word: 'naučnik', translation: 'forskare' },
          { id: 1447, word: 'fotograf', translation: 'fotograf' },
          { id: 1448, word: 'muzičar', translation: 'musiker' },
        ],
      },
      daysOfWeek: {
        title: 'Dani u sedmici',
        description: 'Nauči dane u sedmici.',
        swedish: 'Veckodagar',
        items: [
          { id: 1801, word: 'ponedjeljak', translation: 'måndag' },
          { id: 1802, word: 'utorak', translation: 'tisdag' },
          { id: 1803, word: 'srijeda', translation: 'onsdag' },
          { id: 1804, word: 'četvrtak', translation: 'torsdag' },
          { id: 1805, word: 'petak', translation: 'fredag' },
          { id: 1806, word: 'subota', translation: 'lördag' },
          { id: 1807, word: 'nedjelja', translation: 'söndag' },
        ],
      },
      monthsOfYear: {
        title: 'Mjeseci u godini',
        description: 'Nauči mjesece u godini.',
        swedish: 'Månader',
        items: [
          { id: 1808, word: 'januar', translation: 'januari' },
          { id: 1809, word: 'februar', translation: 'februari' },
          { id: 1810, word: 'mart', translation: 'mars' },
          { id: 3811, word: 'april', translation: 'april' },
          { id: 3812, word: 'maj', translation: 'maj' },
          { id: 3813, word: 'jun', translation: 'juni' },
          { id: 3814, word: 'jul', translation: 'juli' },
          { id: 3815, word: 'august', translation: 'augusti' },
          { id: 3816, word: 'septembar', translation: 'september' },
          { id: 3817, word: 'oktobar', translation: 'oktober' },
          { id: 3818, word: 'novembar', translation: 'november' },
          { id: 3819, word: 'decembar', translation: 'december' },
        ],
      },
      fruits: {
        title: 'Voće',
        description: 'Nazivi za različite vrste voća.',
        swedish: 'Frukt',
        items: [
          { id: 5, word: 'jabuka', translation: 'äpple' },
          { id: 1811, word: 'banana', translation: 'banan' },
          { id: 1812, word: 'kruška', translation: 'päron' },
          { id: 1813, word: 'jagoda', translation: 'jordgubbe' },
          { id: 1814, word: 'šljiva', translation: 'plommon' },
          { id: 2814, word: 'grožđe', translation: 'vindruvor' },
          { id: 2815, word: 'trešnja', translation: 'körsbär' },
          { id: 2816, word: 'lubenica', translation: 'vattenmelon' },
          { id: 3817, word: 'limun', translation: 'citron' },
          { id: 3818, word: 'narandža', translation: 'apelsin' },
          { id: 3819, word: 'višnja', translation: 'surkörsbär' },
          { id: 3820, word: 'breskva', translation: 'persika' },
          { id: 3823, word: 'borovnica', translation: 'blåbär' },
          { id: 3824, word: 'malina', translation: 'hallon' },
          { id: 3825, word: 'ananas', translation: 'ananas' },
          { id: 3826, word: 'smokva', translation: 'fikon' },
          { id: 3827, word: 'kajsija', translation: 'aprikos' },
        ],
      },
      vegetables: {
        title: 'Povrće',
        description: 'Nazivi za različite vrste povrća.',
        swedish: 'Grönsaker',
        items: [
          { id: 1815, word: 'krompir', translation: 'potatis' },
          { id: 1816, word: 'mrkva', translation: 'morot' },
          { id: 1817, word: 'paradajz', translation: 'tomat' },
          { id: 1818, word: 'krastavac', translation: 'gurka' },
          { id: 1819, word: 'luk', translation: 'lök' },
          { id: 2817, word: 'salata', translation: 'sallad' },
          { id: 2818, word: 'paprika', translation: 'paprika' },
          { id: 2819, word: 'kupus', translation: 'kål' },
          { id: 2820, word: 'grah', translation: 'bönor' },
          { id: 3821, word: 'bijeli luk', translation: 'vitlök' },
          { id: 3822, word: 'grašak', translation: 'ärtor' },
          { id: 3828, word: 'tikvica', translation: 'zucchini' },
          { id: 3829, word: 'patlidžan', translation: 'aubergine' },
          { id: 3830, word: 'karfiol', translation: 'blomkål' },
          { id: 3831, word: 'brokula', translation: 'broccoli' },
          { id: 3832, word: 'špinat', translation: 'spenat' },
        ],
      },
      transport: {
        title: 'Prijevozna sredstva',
        description: 'Nauči riječi za različita prijevozna sredstva.',
        swedish: 'Transportmedel',
        items: [
          { id: 6, word: 'auto', translation: 'bil' },
          { id: 27, word: 'bicikl', translation: 'cykel' },
          { id: 28, word: 'voz', translation: 'tåg' },
          { id: 29, word: 'brod', translation: 'båt' },
          { id: 26, word: 'avion', translation: 'flygplan' },
          { id: 1820, word: 'autobus', translation: 'buss' },
          { id: 1821, word: 'tramvaj', translation: 'spårvagn' },
          { id: 1822, word: 'motor', translation: 'motorcykel' },
          { id: 1823, word: 'kamion', translation: 'lastbil' },
          { id: 1824, word: 'čamac', translation: 'båt (liten)' },
        ],
      },
    },
    '4-6': {
      seasons: {
        title: 'Godišnja doba',
        description: 'Nauči nazive za godišnja doba.',
        swedish: 'Årstider',
        items: [
          { id: 5005, word: 'proljeće', translation: 'vår' },
          { id: 5006, word: 'ljeto', translation: 'sommar' },
          { id: 5007, word: 'jesen', translation: 'höst' },
          { id: 5008, word: 'zima', translation: 'vinter' },
        ]
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 2101, word: 'računar', translation: 'dator' },
          { id: 2102, word: 'telefon', translation: 'telefon' },
          { id: 2103, word: 'televizor', translation: 'TV' },
          { id: 2104, word: 'ključ', translation: 'nyckel' },
          { id: 2105, word: 'novčanik', translation: 'plånbok' },
          { id: 2106, word: 'kišobran', translation: 'paraply' },
          { id: 2107, word: 'ruksak', translation: 'ryggsäck' },
          { id: 2108, word: 'lampa', translation: 'lampa' },
          { id: 2117, word: 'fotoaparat', translation: 'kamera' },
          { id: 2118, word: 'bicikl', translation: 'cykel' },
          { id: 1723, word: 'naočale', translation: 'glasögon' },
          { id: 1726, word: 'sapun', translation: 'tvål' },
          { id: 1727, word: 'peškir', translation: 'handduk' },
          { id: 1728, word: 'jastuk', translation: 'kudde' },
          { id: 1729, word: 'deka', translation: 'filt' },
          { id: 1730, word: 'makaze', translation: 'sax' },
          { id: 1731, word: 'lonac', translation: 'kastrull' },
          { id: 1732, word: 'tava', translation: 'stekpanna' },
          { id: 1733, word: 'nož', translation: 'kniv' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 2109, word: 'trg', translation: 'torg' },
          { id: 2110, word: 'općina', translation: 'kommun' },
          { id: 2111, word: 'bolnica', translation: 'sjukhus' },
          { id: 2112, word: 'biblioteka', translation: 'bibliotek' },
          { id: 2113, word: 'pozorište', translation: 'teater' },
          { id: 2114, word: 'prodavnica', translation: 'affär' },
          { id: 2115, word: 'njiva', translation: 'åker' },
          { id: 2116, word: 'livada', translation: 'äng' },
          { id: 2119, word: 'aerodrom', translation: 'flygplats' },
          { id: 2120, word: 'stanica', translation: 'station' },
          { id: 1113, word: 'zgrada', translation: 'byggnad' },
          { id: 1114, word: 'kuća', translation: 'hus' },
          { id: 1115, word: 'park', translation: 'park' },
          { id: 1116, word: 'rijeka', translation: 'flod' },
          { id: 1117, word: 'most', translation: 'bro' },
          { id: 1178, word: 'semafor', translation: 'trafikljus' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Pojmovi vezani za školu i obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 2122, word: 'predmet', translation: 'ämne' },
          { id: 2123, word: 'ocjena', translation: 'betyg' },
          { id: 2124, word: 'test', translation: 'prov' },
          { id: 2125, word: 'historija', translation: 'historia' },
          { id: 2126, word: 'geografija', translation: 'geografi' },
          { id: 2127, word: 'matematika', translation: 'matematik' },
          { id: 2128, word: 'eksperiment', translation: 'experiment' },
          { id: 2129, word: 'gimnazija', translation: 'gymnasium' },
          { id: 2130, word: 'raspored', translation: 'schema' },
          { id: 2131, word: 'nastavnik', translation: 'lärare' },
          { id: 1123, word: 'učiteljica', translation: 'lärare (kvinnlig)' },
          { id: 1124, word: 'učenik', translation: 'elev' },
          { id: 1125, word: 'tabla', translation: 'tavla' },
          { id: 1128, word: 'knjiga', translation: 'bok' },
          { id: 1129, word: 'odmor', translation: 'rast' },
          { id: 1130, word: 'čas', translation: 'lektion' },
          { id: 1131, word: 'zadaća', translation: 'läxa' },
          { id: 1132, word: 'učionica', translation: 'klassrum' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Složenije riječi iz prirode.',
        swedish: 'Natur',
        items: [
          { id: 2132, word: 'okoliš', translation: 'miljö' },
          { id: 2133, word: 'klima', translation: 'klimat' },
          { id: 2134, word: 'atmosfera', translation: 'atmosfär' },
          { id: 2135, word: 'kontinent', translation: 'kontinent' },
          { id: 2136, word: 'okean', translation: 'ocean' },
          { id: 2137, word: 'glečer', translation: 'glaciär' },
          { id: 2138, word: 'pustinja', translation: 'öken' },
          { id: 2139, word: 'vulkan', translation: 'vulkan' },
          { id: 2140, word: 'zemljotres', translation: 'jordbävning' },
          { id: 2141, word: 'vrsta', translation: 'art (species)' },
          { id: 1133, word: 'sunce', translation: 'sol' },
          { id: 1134, word: 'mjesec', translation: 'måne' },
          { id: 1135, word: 'zvijezda', translation: 'stjärna' },
          { id: 1136, word: 'drvo', translation: 'träd' },
          { id: 1137, word: 'cvijet', translation: 'blomma' },
          { id: 1138, word: 'trava', translation: 'gräs' },
          { id: 1139, word: 'kamen', translation: 'sten' },
          { id: 1140, word: 'planina', translation: 'berg' },
          { id: 1141, word: 'more', translation: 'hav' },
          { id: 1142, word: 'kiša', translation: 'regn' },
          { id: 1190, word: 'snijeg', translation: 'snö' },
          { id: 1191, word: 'vjetar', translation: 'vind' },
          { id: 1192, word: 'oblak', translation: 'moln' },
          { id: 1193, word: 'šuma', translation: 'skog' },
          { id: 1197, word: 'led', translation: 'is' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Detaljniji dijelovi ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 2142, word: 'mozak', translation: 'hjärna' },
          { id: 2143, word: 'srce', translation: 'hjärta' },
          { id: 2144, word: 'pluća', translation: 'lungor' },
          { id: 2145, word: 'stomak', translation: 'mage' },
          { id: 2146, word: 'krv', translation: 'blod' },
          { id: 2147, word: 'mišić', translation: 'muskel' },
          { id: 2148, word: 'kost', translation: 'ben (skelett)' },
          { id: 2149, word: 'koža', translation: 'hud' },
          { id: 2150, word: 'organ', translation: 'organ' },
          { id: 2151, word: 'ćelija', translation: 'cell' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Više naziva za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 2152, word: 'košulja', translation: 'skjorta' },
          { id: 2153, word: 'suknja', translation: 'kjol' },
          { id: 2154, word: 'odijelo', translation: 'kostym' },
          { id: 2155, word: 'kaput', translation: 'kappa' },
          { id: 2156, word: 'rukavice', translation: 'handskar' },
          { id: 2157, word: 'čizme', translation: 'stövlar' },
          { id: 2158, word: 'sandale', translation: 'sandaler' },
          { id: 2159, word: 'kaiš', translation: 'bälte' },
          { id: 2160, word: 'šešir', translation: 'hatt' },
          { id: 2161, word: 'kravata', translation: 'slips' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Složenije radnje.',
        swedish: 'Verb',
        items: [
          { id: 2162, word: 'putovati', translation: 'resa' },
          { id: 2163, word: 'učiti', translation: 'lära sig/studera' },
          { id: 2164, word: 'razumjeti', translation: 'förstå' },
          { id: 2165, word: 'pitati', translation: 'fråga' },
          { id: 2166, word: 'odgovoriti', translation: 'svara' },
          { id: 2167, word: 'pomoći', translation: 'hjälpa' },
          { id: 2168, word: 'vjerovati', translation: 'tro' },
          { id: 2169, word: 'misliti', translation: 'tänka/tycka' },
          { id: 2170, word: 'graditi', translation: 'bygga' },
          { id: 2171, word: 'otkriti', translation: 'upptäcka' },
          { id: 1210, word: 'crtati', translation: 'rita' },
          { id: 1211, word: 'plivati', translation: 'simma' },
          { id: 1212, word: 'voziti', translation: 'köra' },
          { id: 1215, word: 'skakati', translation: 'hoppa' },
          { id: 1216, word: 'letjeti', translation: 'flyga' },
          { id: 1217, word: 'slušati', translation: 'lyssna' },
          { id: 1218, word: 'govoriti', translation: 'tala' },
          { id: 1226, word: 'kupiti', translation: 'köpa' },
          { id: 1227, word: 'prodati', translation: 'sälja' },
          { id: 1228, word: 'dati', translation: 'ge' },
          { id: 1229, word: 'uzeti', translation: 'ta' },
        ]
      },
      feelingsAndAdjectives: {
        title: 'Osjećaji i pridjevi',
        description: 'Riječi za opisivanje osjećaja i stvari.',
        swedish: 'Känslor och adjektiv',
        items: [
          { id: 2401, word: 'uzbuđen', translation: 'exalterad' },
          { id: 2402, word: 'zabrinut', translation: 'orolig' },
          { id: 2403, word: 'ponosan', translation: 'stolt' },
          { id: 2404, word: 'zanimljiv', translation: 'intressant' },
          { id: 2405, word: 'dosadan', translation: 'tråkig' },
          { id: 2406, word: 'ukusan', translation: 'smaklig/god' },
          { id: 2407, word: 'glasan', translation: 'högljudd' },
          { id: 2408, word: 'tih', translation: 'tyst' },
          { id: 2409, word: 'važan', translation: 'viktig' },
          { id: 2410, word: 'jednostavan', translation: 'enkel' },
          { id: 1401, word: 'sretan', translation: 'glad' },
          { id: 1402, word: 'tužan', translation: 'ledsen' },
          { id: 1403, word: 'ljut', translation: 'arg' },
          { id: 1408, word: 'dobar', translation: 'bra/god' },
          { id: 1409, word: 'loš', translation: 'dålig' },
          { id: 1426, word: 'umoran', translation: 'trött' },
          { id: 1427, word: 'gladan', translation: 'hungrig' },
          { id: 1428, word: 'žedan', translation: 'törstig' },
        ],
      },
      professions: {
        title: 'Zanimanja',
        description: 'Nazivi za različita zanimanja.',
        swedish: 'Yrken',
        items: [
          { id: 2412, word: 'inžinjer', translation: 'ingenjör' },
          { id: 2413, word: 'naučnik', translation: 'forskare/vetenskapsman' },
          { id: 2414, word: 'umjetnik', translation: 'konstnär' },
          { id: 2415, word: 'sportista', translation: 'idrottare' },
          { id: 2416, word: 'novinar', translation: 'journalist' },
          { id: 2417, word: 'programer', translation: 'programmerare' },
          { id: 2418, word: 'pravnik', translation: 'jurist' },
          { id: 2419, word: 'arhitekta', translation: 'arkitekt' },
          { id: 2420, word: 'zubar', translation: 'tandläkare' },
          { id: 2421, word: 'apotekar', translation: 'apotekare' },
          { id: 1412, word: 'učitelj/učiteljica', translation: 'lärare' },
          { id: 1413, word: 'ljekar/ljekarica', translation: 'läkare' },
          { id: 1414, word: 'policajac/policajka', translation: 'polis' },
          { id: 1415, word: 'vatrogasac', translation: 'brandman' },
          { id: 1416, word: 'kuhar/kuharica', translation: 'kock' },
          { id: 1417, word: 'frizer/frizerka', translation: 'frisör' },
          { id: 1418, word: 'vozač', translation: 'förare/chaufför' },
          { id: 1419, word: 'prodavač/prodavačica', translation: 'försäljare' },
          { id: 1420, word: 'pjevač/pjevačica', translation: 'sångare' },
          { id: 1421, word: 'glumac/glumica', translation: 'skådespelare' },
          { id: 1435, word: 'pekar', translation: 'bagare' },
          { id: 1438, word: 'slikar', translation: 'målare' },
          { id: 1440, word: 'pilot', translation: 'pilot' },
        ],
      },
      daysOfWeek: {
        title: 'Dani u sedmici',
        description: 'Nauči dane u sedmici.',
        swedish: 'Veckodagar',
        items: [
          { id: 2801, word: 'ponedjeljak', translation: 'måndag' },
          { id: 2802, word: 'utorak', translation: 'tisdag' },
          { id: 2803, word: 'srijeda', translation: 'onsdag' },
          { id: 2804, word: 'četvrtak', translation: 'torsdag' },
          { id: 2805, word: 'petak', translation: 'fredag' },
          { id: 2806, word: 'subota', translation: 'lördag' },
          { id: 2807, word: 'nedjelja', translation: 'söndag' },
        ],
      },
      monthsOfYear: {
        title: 'Mjeseci u godini',
        description: 'Nauči mjesece u godini.',
        swedish: 'Månader',
        items: [
          { id: 2808, word: 'januar', translation: 'januari' },
          { id: 2809, word: 'februar', translation: 'februari' },
          { id: 2810, word: 'mart', translation: 'mars' },
          { id: 2811, word: 'april', translation: 'april' },
          { id: 2812, word: 'maj', translation: 'maj' },
          { id: 2813, word: 'jun', translation: 'juni' },
          { id: 3814, word: 'jul', translation: 'juli' },
          { id: 3815, word: 'august', translation: 'augusti' },
          { id: 3816, word: 'septembar', translation: 'september' },
          { id: 3817, word: 'oktobar', translation: 'oktober' },
          { id: 3818, word: 'novembar', translation: 'november' },
          { id: 3819, word: 'decembar', translation: 'december' },
        ],
      },
      fruits: {
        title: 'Voće',
        description: 'Nazivi za različite vrste voća.',
        swedish: 'Frukt',
        items: [
          { id: 2814, word: 'grožđe', translation: 'vindruvor' },
          { id: 2815, word: 'trešnja', translation: 'körsbär' },
          { id: 2816, word: 'lubenica', translation: 'vattenmelon' },
          { id: 1811, word: 'banana', translation: 'banan' },
          { id: 1812, word: 'kruška', translation: 'päron' },
          { id: 1813, word: 'jagoda', translation: 'jordgubbe' },
          { id: 3817, word: 'limun', translation: 'citron' },
          { id: 3818, word: 'narandža', translation: 'apelsin' },
          { id: 3819, word: 'višnja', translation: 'surkörsbär' },
          { id: 3820, word: 'breskva', translation: 'persika' },
          { id: 3825, word: 'ananas', translation: 'ananas' },
          { id: 3826, word: 'smokva', translation: 'fikon' },
          { id: 3827, word: 'kajsija', translation: 'aprikos' },
        ],
      },
      vegetables: {
        title: 'Povrće',
        description: 'Nazivi za različite vrste povrća.',
        swedish: 'Grönsaker',
        items: [
          { id: 2817, word: 'salata', translation: 'sallad' },
          { id: 2818, word: 'paprika', translation: 'paprika' },
          { id: 2819, word: 'kupus', translation: 'kål' },
          { id: 2820, word: 'grah', translation: 'bönor' },
          { id: 1815, word: 'krompir', translation: 'potatis' },
          { id: 1816, word: 'mrkva', translation: 'morot' },
          { id: 1817, word: 'paradajz', translation: 'tomat' },
          { id: 1818, word: 'krastavac', translation: 'gurka' },
          { id: 1819, word: 'luk', translation: 'lök' },
          { id: 3821, word: 'bijeli luk', translation: 'vitlök' },
          { id: 3822, word: 'grašak', translation: 'ärtor' },
          { id: 3828, word: 'tikvica', translation: 'zucchini' },
          { id: 3829, word: 'patlidžan', translation: 'aubergine' },
          { id: 3830, word: 'karfiol', translation: 'blomkål' },
          { id: 3831, word: 'brokula', translation: 'broccoli' },
        ],
      },
      travel: {
        title: 'Putovanja',
        description: 'Riječi vezane za putovanja i odmor.',
        swedish: 'Resor',
        items: [
          { id: 2821, word: 'putovanje', translation: 'resa' },
          { id: 2822, word: 'odmor', translation: 'semester' },
          { id: 2823, word: 'hotel', translation: 'hotell' },
          { id: 2824, word: 'plaža', translation: 'strand' },
          { id: 2825, word: 'kofer', translation: 'resväska' },
          { id: 2826, word: 'karta', translation: 'biljett' },
          { id: 2827, word: 'pasoš', translation: 'pass' },
          { id: 2828, word: 'turist', translation: 'turist' },
          { id: 2829, word: 'vodič', translation: 'guide' },
          { id: 2830, word: 'destinacija', translation: 'destination' },
        ],
      },
      countries: {
        title: 'Države',
        description: 'Nazivi evropskih i drugih država.',
        swedish: 'Länder',
        items: [
          { id: 2831, word: 'Bosna i Hercegovina', translation: 'Bosnien och Hercegovina' },
          { id: 2832, word: 'Švedska', translation: 'Sverige' },
          { id: 2833, word: 'Njemačka', translation: 'Tyskland' },
          { id: 2834, word: 'Italija', translation: 'Italien' },
          { id: 2835, word: 'Francuska', translation: 'Frankrike' },
          { id: 2836, word: 'Španija', translation: 'Spanien' },
          { id: 2837, word: 'SAD', translation: 'USA' },
          { id: 2838, word: 'Kina', translation: 'Kina' },
          { id: 2839, word: 'Japan', translation: 'Japan' },
          { id: 2840, word: 'Brazil', translation: 'Brasilien' },
        ],
      },
    },
    '7-9': {
      seasons: {
        title: 'Godišnja doba',
        description: 'Nauči nazive za godišnja doba.',
        swedish: 'Årstider',
        items: [
          { id: 5009, word: 'proljeće', translation: 'vår' },
          { id: 5010, word: 'ljeto', translation: 'sommar' },
          { id: 5011, word: 'jesen', translation: 'höst' },
          { id: 5012, word: 'zima', translation: 'vinter' },
        ]
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 3101, word: 'punjač', translation: 'laddare' },
          { id: 3102, word: 'slušalice', translation: 'hörlurar' },
          { id: 3103, word: 'dokument', translation: 'dokument' },
          { id: 3104, word: 'ugovor', translation: 'avtal' },
          { id: 3105, word: 'račun', translation: 'faktura/kvitto' },
          { id: 3106, word: 'pernica', translation: 'pennskrin' },
          { id: 3107, word: 'kalendar', translation: 'kalender' },
          { id: 3115, word: 'pasoš', translation: 'pass' },
          { id: 3116, word: 'vozačka dozvola', translation: 'körkort' },
          { id: 3117, word: 'polica', translation: 'hylla' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 3108, word: 'saobraćaj', translation: 'trafik' },
          { id: 3109, word: 'industrija', translation: 'industri' },
          { id: 3110, word: 'stanovništvo', translation: 'befolkning' },
          { id: 3111, word: 'infrastruktura', translation: 'infrastruktur' },
          { id: 3112, word: 'poljoprivreda', translation: 'jordbruk' },
          { id: 3113, word: 'znamenitost', translation: 'sevärdhet' },
          { id: 3114, word: 'predgrađe', translation: 'förort' },
          { id: 3118, word: 'urbanizam', translation: 'urbanism' },
          { id: 3119, word: 'ruralno', translation: 'lantlig' },
          { id: 3120, word: 'metropola', translation: 'metropol' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Apstraktniji pojmovi vezani za obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 3121, word: 'obrazovanje', translation: 'utbildning' },
          { id: 3122, word: 'znanje', translation: 'kunskap' },
          { id: 3123, word: 'analiza', translation: 'analys' },
          { id: 3124, word: 'hipoteza', translation: 'hypotes' },
          { id: 3125, word: 'teorija', translation: 'teori' },
          { id: 3126, word: 'fakultet', translation: 'fakultet/universitet' },
          { id: 3127, word: 'diploma', translation: 'examensbevis' },
          { id: 3128, word: 'istraživanje', translation: 'forskning' },
          { id: 3129, word: 'perspektiva', translation: 'perspektiv' },
          { id: 3130, word: 'zaključak', translation: 'slutsats' },
          { id: 2122, word: 'predmet', translation: 'ämne' },
          { id: 2123, word: 'ocjena', translation: 'betyg' },
          { id: 2124, word: 'test', translation: 'prov' },
          { id: 2129, word: 'gimnazija', translation: 'gymnasium' },
          { id: 2130, word: 'raspored', translation: 'schema' },
          { id: 2131, word: 'nastavnik', translation: 'lärare' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Napredni pojmovi iz prirode i nauke.',
        swedish: 'Natur',
        items: [
          { id: 3131, word: 'ekosistem', translation: 'ekosystem' },
          { id: 3132, word: 'biodiverzitet', translation: 'biologisk mångfald' },
          { id: 3133, word: 'evolucija', translation: 'evolution' },
          { id: 3134, word: 'fotosinteza', translation: 'fotosyntes' },
          { id: 3135, word: 'gravitacija', translation: 'gravitation' },
          { id: 3136, word: 'svemir', translation: 'universum' },
          { id: 3137, word: 'galaksija', translation: 'galax' },
          { id: 3138, word: 'molekula', translation: 'molekyl' },
          { id: 3139, word: 'atom', translation: 'atom' },
          { id: 3140, word: 'energija', translation: 'energi' },
          { id: 2132, word: 'okoliš', translation: 'miljö' },
          { id: 2133, word: 'klima', translation: 'klimat' },
          { id: 2134, word: 'atmosfera', translation: 'atmosfär' },
          { id: 2135, word: 'kontinent', translation: 'kontinent' },
          { id: 2136, word: 'okean', translation: 'ocean' },
          { id: 2137, word: 'glečer', translation: 'glaciär' },
          { id: 2138, word: 'pustinja', translation: 'öken' },
          { id: 2139, word: 'vulkan', translation: 'vulkan' },
          { id: 2140, word: 'zemljotres', translation: 'jordbävning' },
          { id: 2141, word: 'vrsta', translation: 'art (species)' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Složeni pojmovi vezani za ljudsko tijelo.',
        swedish: 'Människokroppen',
        items: [
          { id: 3141, word: 'organizam', translation: 'organism' },
          { id: 3142, word: 'imunitet', translation: 'immunitet' },
          { id: 3143, word: 'metabolizam', translation: 'metabolism/ämnesomsättning' },
          { id: 3144, word: 'genetika', translation: 'genetik' },
          { id: 3145, word: 'cirkulacija', translation: 'cirkulation' },
          { id: 3146, word: 'respiracija', translation: 'andning' },
          { id: 3147, word: 'skelet', translation: 'skelett' },
          { id: 3148, word: 'svijest', translation: 'medvetande' },
          { id: 3149, word: 'emocija', translation: 'känsla' },
          { id: 3150, word: 'instinkt', translation: 'instinkt' },
          { id: 2142, word: 'mozak', translation: 'hjärna' },
          { id: 2143, word: 'srce', translation: 'hjärta' },
          { id: 2144, word: 'pluća', translation: 'lungor' },
          { id: 2145, word: 'stomak', translation: 'mage' },
          { id: 2146, word: 'krv', translation: 'blod' },
          { id: 2147, word: 'mišić', translation: 'muskel' },
          { id: 2148, word: 'kost', translation: 'ben (skelett)' },
          { id: 2149, word: 'koža', translation: 'hud' },
          { id: 2150, word: 'organ', translation: 'organ' },
          { id: 2151, word: 'ćelija', translation: 'cell' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Specifični nazivi za odjeću i materijale.',
        swedish: 'Kläder och skor',
        items: [
          { id: 3151, word: 'pamuk', translation: 'bomull' },
          { id: 3152, word: 'vuna', translation: 'ull' },
          { id: 3153, word: 'svila', translation: 'siden' },
          { id: 3154, word: 'koža', translation: 'läder' },
          { id: 3155, word: 'uniforma', translation: 'uniform' },
          { id: 3156, word: 'dres', translation: 'matchtröja' },
          { id: 3157, word: 'odijelo za kupanje', translation: 'badkläder' },
          { id: 3158, word: 'veš', translation: 'underkläder' },
          { id: 3159, word: 'aksesoar', translation: 'accessoar' },
          { id: 3160, word: 'brend', translation: 'märke' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Apstraktni glagoli.',
        swedish: 'Verb',
        items: [
          { id: 3161, word: 'analizirati', translation: 'analysera' },
          { id: 3162, word: 'kritikovati', translation: 'kritisera' },
          { id: 3163, word: 'argumentovati', translation: 'argumentera' },
          { id: 3164, word: 'pretpostaviti', translation: 'anta' },
          { id: 3165, word: 'zaključiti', translation: 'dra en slutsats' },
          { id: 3166, word: 'komunicirati', translation: 'kommunicera' },
          { id: 3167, word: 'interpretirati', translation: 'tolka' },
          { id: 3168, word: 'utjecati', translation: 'påverka' },
          { id: 3169, word: 'razviti', translation: 'utveckla' },
          { id: 3170, word: 'ostvariti', translation: 'förverkliga/uppnå' },
          { id: 2162, word: 'putovati', translation: 'resa' },
          { id: 2163, word: 'učiti', translation: 'lära sig/studera' },
          { id: 2164, word: 'razumjeti', translation: 'förstå' },
          { id: 2165, word: 'pitati', translation: 'fråga' },
          { id: 2166, word: 'odgovoriti', translation: 'svara' },
          { id: 2167, word: 'pomoći', translation: 'hjälpa' },
          { id: 2168, word: 'vjerovati', translation: 'tro' },
          { id: 2169, word: 'misliti', translation: 'tänka/tycka' },
          { id: 2170, word: 'graditi', translation: 'bygga' },
          { id: 2171, word: 'otkriti', translation: 'upptäcka' },
        ]
      },
      feelingsAndAdjectives: {
        title: 'Osjećaji i pridjevi',
        description: 'Riječi za opisivanje osjećaja i stvari.',
        swedish: 'Känslor och adjektiv',
        items: [
          { id: 3401, word: 'ravnodušan', translation: 'likgiltig' },
          { id: 3402, word: 'entuzijastičan', translation: 'entusiastisk' },
          { id: 3403, word: 'nostalgičan', translation: 'nostalgisk' },
          { id: 3404, word: 'objektivan', translation: 'objektiv' },
          { id: 3405, word: 'subjektivan', translation: 'subjektiv' },
          { id: 3406, word: 'apstraktan', translation: 'abstrakt' },
          { id: 3407, word: 'konkretan', translation: 'konkret' },
          { id: 3408, word: 'relevantan', translation: 'relevant' },
          { id: 3409, word: 'adekvatan', translation: 'adekvat' },
          { id: 3410, word: 'paradoksalan', translation: 'paradoxal' },
          { id: 2401, word: 'uzbuđen', translation: 'exalterad' },
          { id: 2402, word: 'zabrinut', translation: 'orolig' },
          { id: 2403, word: 'ponosan', translation: 'stolt' },
          { id: 2404, word: 'zanimljiv', translation: 'intressant' },
          { id: 2405, word: 'dosadan', translation: 'tråkig' },
          { id: 2406, word: 'ukusan', translation: 'smaklig/god' },
          { id: 2409, word: 'važan', translation: 'viktig' },
          { id: 2410, word: 'jednostavan', translation: 'enkel' },
        ],
      },
      professions: {
        title: 'Zanimanja',
        description: 'Nazivi za različita zanimanja.',
        swedish: 'Yrken',
        items: [
          { id: 3412, word: 'psiholog', translation: 'psykolog' },
          { id: 3413, word: 'sociolog', translation: 'sociolog' },
          { id: 3414, word: 'filozof', translation: 'filosof' },
          { id: 3415, word: 'političar', translation: 'politiker' },
          { id: 3416, word: 'ekonomista', translation: 'ekonom' },
          { id: 3417, word: 'prevodilac', translation: 'översättare' },
          { id: 3418, word: 'dizajner', translation: 'designer' },
          { id: 3419, word: 'poduzetnik', translation: 'entreprenör' },
          { id: 3420, word: 'istraživač', translation: 'forskare' },
          { id: 3421, word: 'savjetnik', translation: 'rådgivare' },
          { id: 2412, word: 'inžinjer', translation: 'ingenjör' },
          { id: 2413, word: 'naučnik', translation: 'forskare/vetenskapsman' },
          { id: 2414, word: 'umjetnik', translation: 'konstnär' },
          { id: 2415, word: 'sportista', translation: 'idrottare' },
          { id: 2416, word: 'novinar', translation: 'journalist' },
          { id: 2417, word: 'programer', translation: 'programmerare' },
          { id: 2418, word: 'pravnik', translation: 'jurist' },
          { id: 2419, word: 'arhitekta', translation: 'arkitekt' },
          { id: 2420, word: 'zubar', translation: 'tandläkare' },
          { id: 2421, word: 'apotekar', translation: 'apotekare' },
        ],
      },
      daysOfWeek: {
        title: 'Dani u sedmici',
        description: 'Nauči dane u sedmici.',
        swedish: 'Veckodagar',
        items: [
          { id: 3801, word: 'ponedjeljak', translation: 'måndag' },
          { id: 3802, word: 'utorak', translation: 'tisdag' },
          { id: 3803, word: 'srijeda', translation: 'onsdag' },
          { id: 3804, word: 'četvrtak', translation: 'torsdag' },
          { id: 3805, word: 'petak', translation: 'fredag' },
          { id: 3806, word: 'subota', translation: 'lördag' },
          { id: 3807, word: 'nedjelja', translation: 'söndag' },
        ],
      },
      monthsOfYear: {
        title: 'Mjeseci u godini',
        description: 'Nauči mjesece u godini.',
        swedish: 'Månader',
        items: [
          { id: 3808, word: 'januar', translation: 'januari' },
          { id: 3809, word: 'februar', translation: 'februari' },
          { id: 3810, word: 'mart', translation: 'mars' },
          { id: 3811, word: 'april', translation: 'april' },
          { id: 3812, word: 'maj', translation: 'maj' },
          { id: 3813, word: 'jun', translation: 'juni' },
          { id: 3814, word: 'jul', translation: 'juli' },
          { id: 3815, word: 'august', translation: 'augusti' },
          { id: 3816, word: 'septembar', translation: 'september' },
          { id: 3817, word: 'oktobar', translation: 'oktober' },
          { id: 3818, word: 'novembar', translation: 'november' },
          { id: 3819, word: 'decembar', translation: 'december' },
        ],
      },
      fruits: {
        title: 'Voće',
        description: 'Nazivi za različite vrste voća.',
        swedish: 'Frukt',
        items: [
          { id: 3817, word: 'limun', translation: 'citron' },
          { id: 3818, word: 'narandža', translation: 'apelsin' },
          { id: 3819, word: 'višnja', translation: 'surkörsbär' },
          { id: 3820, word: 'breskva', translation: 'persika' },
          { id: 3823, word: 'borovnica', translation: 'blåbär' },
          { id: 3824, word: 'malina', translation: 'hallon' },
          { id: 5, word: 'jabuka', translation: 'äpple' },
          { id: 1811, word: 'banana', translation: 'banan' },
          { id: 1812, word: 'kruška', translation: 'päron' },
          { id: 1813, word: 'jagoda', translation: 'jordgubbe' },
          { id: 3825, word: 'ananas', translation: 'ananas' },
          { id: 3826, word: 'smokva', translation: 'fikon' },
          { id: 3827, word: 'kajsija', translation: 'aprikos' },
        ],
      },
      vegetables: {
        title: 'Povrće',
        description: 'Nazivi za različite vrste povrća.',
        swedish: 'Grönsaker',
        items: [
          { id: 3821, word: 'bijeli luk', translation: 'vitlök' },
          { id: 3822, word: 'grašak', translation: 'ärtor' },
          { id: 3828, word: 'tikvica', translation: 'zucchini' },
          { id: 3829, word: 'patlidžan', translation: 'aubergine' },
          { id: 1815, word: 'krompir', translation: 'potatis' },
          { id: 1816, word: 'mrkva', translation: 'morot' },
          { id: 1817, word: 'paradajz', translation: 'tomat' },
          { id: 1818, word: 'krastavac', translation: 'gurka' },
          { id: 1819, word: 'luk', translation: 'lök' },
          { id: 2817, word: 'salata', translation: 'sallad' },
          { id: 3830, word: 'karfiol', translation: 'blomkål' },
          { id: 3831, word: 'brokula', translation: 'broccoli' },
          { id: 3832, word: 'špinat', translation: 'spenat' },
        ],
      },
      travel: {
        title: 'Putovanja',
        description: 'Riječi vezane za putovanja i odmor.',
        swedish: 'Resor',
        items: [
          { id: 3827, word: 'avantura', translation: 'äventyr' },
          { id: 3828, word: 'mapa', translation: 'karta' },
          { id: 3829, word: 'kompas', translation: 'kompass' },
          { id: 3830, word: 'smještaj', translation: 'boende' },
          { id: 3831, word: 'rezervacija', translation: 'bokning' },
          { id: 3832, word: 'let', translation: 'flyg' },
          { id: 3833, word: 'prtljag', translation: 'bagage' },
          { id: 3834, word: 'granica', translation: 'gräns' },
          { id: 3835, word: 'carina', translation: 'tull' },
          { id: 3836, word: 'valuta', translation: 'valuta' },
        ],
      },
      countries: {
        title: 'Države',
        description: 'Nazivi evropskih i drugih država.',
        swedish: 'Länder',
        items: [
          { id: 3837, word: 'Austrija', translation: 'Österrike' },
          { id: 3838, word: 'Švicarska', translation: 'Schweiz' },
          { id: 3839, word: 'Norveška', translation: 'Norge' },
          { id: 3840, word: 'Danska', translation: 'Danmark' },
          { id: 3841, word: 'Finska', translation: 'Finland' },
          { id: 3842, word: 'Turska', translation: 'Turkiet' },
          { id: 3843, word: 'Egipat', translation: 'Egypten' },
          { id: 3844, word: 'Australija', translation: 'Australien' },
          { id: 3845, word: 'Kanada', translation: 'Kanada' },
          { id: 3846, word: 'Rusija', translation: 'Ryssland' },
        ],
      },
    },
  },
  croatian: {
    '1-3': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['1-3'])),
    },
    '4-6': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['4-6'])),
    },
    '7-9': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['7-9'])),
    },
  },
  serbian: {
    '1-3': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['1-3'])),
    },
    '4-6': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['4-6'])),
    },
    '7-9': {
      ...JSON.parse(JSON.stringify(vocabularyData.bosnian['7-9'])),
    },
  }
};

// Croatian specific replacements
Object.keys(vocabularyData.croatian).forEach(grade => {
  Object.keys(vocabularyData.croatian[grade]).forEach(category => {
    vocabularyData.croatian[grade][category].items.forEach(item => {
      item.word = item.word.replace('hljeb', 'kruh').replace('kafa', 'kava').replace('mrkva', 'mrkva');
      item.translation = item.translation.replace('bröd', 'bröd').replace('kaffe', 'kaffe').replace('morot', 'morot');
    });
  });
});

// Serbian specific replacements
Object.keys(vocabularyData.serbian).forEach(grade => {
  Object.keys(vocabularyData.serbian[grade]).forEach(category => {
    vocabularyData.serbian[grade][category].items.forEach(item => {
      item.word = item.word.replace('hljeb', 'hleb').replace('mrkva', 'šargarepa');
      item.translation = item.translation.replace('bröd', 'bröd').replace('morot', 'morot');
    });
  });
});
