import type { VocabularyData } from './types';

export const vocabularyData: VocabularyData = {
  bosnian: {
    '1-3': {
      family: {
        title: 'Porodica',
        description: 'Nauči riječi za članove porodice.',
        swedish: 'Familj',
        items: [
          { id: 1001, word: 'majka', translation: 'mamma' },
          { id: 1002, word: 'otac', translation: 'pappa' },
          { id: 1003, word: 'sestra', translation: 'syster' },
          { id: 1004, word: 'brat', translation: 'bror' },
          { id: 1005, word: 'nana', translation: 'farmor/mormor' },
          { id: 1006, word: 'djed', translation: 'farfar/morfar' },
          { id: 1013, word: 'tetka', translation: 'moster/faster' },
          { id: 1014, word: 'amidža', translation: 'farbror (paternal)' },
          { id: 1015, word: 'daidža', translation: 'morbror (maternal)' },
          { id: 1016, word: 'beba', translation: 'bebis' },
        ],
      },
      colors: {
        title: 'Boje',
        description: 'Otkrij nazive za različite boje.',
        swedish: 'Färger',
        items: [
          { id: 1007, word: 'crvena', translation: 'röd' },
          { id: 1008, word: 'plava', translation: 'blå' },
          { id: 1009, word: 'zelena', translation: 'grön' },
          { id: 1010, word: 'žuta', translation: 'gul' },
          { id: 1011, word: 'crna', translation: 'svart' },
          { id: 1012, word: 'bijela', translation: 'vit' },
          { id: 1017, word: 'narandžasta', translation: 'orange' },
          { id: 1018, word: 'ljubičasta', translation: 'lila' },
          { id: 1019, word: 'smeđa', translation: 'brun' },
          { id: 1020, word: 'siva', translation: 'grå' },
        ],
      },
      food: {
        title: 'Hrana i Piće',
        description: 'Istraži riječi vezane za hranu i piće.',
        swedish: 'Mat och Dryck',
        items: [
          { id: 21, word: 'hljeb', translation: 'bröd' },
          { id: 22, word: 'mlijeko', translation: 'mjölk' },
          { id: 5, word: 'jabuka', translation: 'äpple' },
          { id: 11, word: 'voda', translation: 'vatten' },
          { id: 1, word: 'kafa', translation: 'kaffe' },
          { id: 1021, word: 'sok', translation: 'juice' },
          { id: 1022, word: 'sir', translation: 'ost' },
          { id: 1023, word: 'meso', translation: 'kött' },
          { id: 1024, word: 'supa', translation: 'soppa' },
          { id: 1025, word: 'kolač', translation: 'kaka' },
          { id: 1026, word: 'pita', translation: 'paj' },
          { id: 1027, word: 'ćevapi', translation: 'ćevapi' },
        ],
      },
      animals: {
        title: 'Životinje',
        description: 'Upoznaj se sa nazivima životinja.',
        swedish: 'Djur',
        items: [
          { id: 7, word: 'mačka', translation: 'katt' },
          { id: 8, word: 'pas', translation: 'hund' },
          { id: 62, word: 'riba', translation: 'fisk' },
          { id: 15, word: 'ptica', translation: 'fågel' },
          { id: 34, word: 'medvjed', translation: 'björn' },
          { id: 1028, word: 'lav', translation: 'lejon' },
          { id: 1029, word: 'tigar', translation: 'tiger' },
          { id: 1030, word: 'konj', translation: 'häst' },
          { id: 1031, word: 'krava', translation: 'ko' },
          { id: 1032, word: 'ovca', translation: 'får' },
        ],
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 1101, word: 'stolica', translation: 'stol' },
          { id: 1102, word: 'sto', translation: 'bord' },
          { id: 1103, word: 'krevet', translation: 'säng' },
          { id: 1104, word: 'čaša', translation: 'glas' },
          { id: 1105, word: 'tanjir', translation: 'tallrik' },
          { id: 1106, word: 'kašika', translation: 'sked' },
          { id: 1107, word: 'viljuška', translation: 'gaffel' },
          { id: 1108, word: 'sveska', translation: 'anteckningsbok' },
          { id: 1109, word: 'olovka', translation: 'penna' },
          { id: 1119, word: 'prozor', translation: 'fönster' },
          { id: 1120, word: 'vrata', translation: 'dörr' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
            { id: 1110, word: 'grad', translation: 'stad' },
            { id: 1111, word: 'selo', translation: 'by' },
            { id: 1112, word: 'ulica', translation: 'gata' },
            { id: 1113, word: 'zgrada', translation: 'byggnad' },
            { id: 1114, word: 'kuća', translation: 'hus' },
            { id: 1115, word: 'park', translation: 'park' },
            { id: 1116, word: 'rijeka', translation: 'flod' },
            { id: 1117, word: 'most', translation: 'bro' },
            { id: 1118, word: 'čaršija', translation: 'basar/marknad' },
            { id: 1121, word: 'igralište', translation: 'lekplats' },
            { id: 1122, word: 'prodavnica', translation: 'affär' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Riječi koje koristimo u školi.',
        swedish: 'Skola',
        items: [
          { id: 1123, word: 'učiteljica', translation: 'lärare (kvinnlig)' },
          { id: 1124, word: 'učenik', translation: 'elev' },
          { id: 1125, word: 'tabla', translation: 'tavla' },
          { id: 1126, word: 'kreda', translation: 'krita' },
          { id: 1127, word: 'spužva', translation: 'svamp' },
          { id: 1128, word: 'knjiga', translation: 'bok' },
          { id: 1129, word: 'odmor', translation: 'rast' },
          { id: 1130, word: 'čas', translation: 'lektion' },
          { id: 1131, word: 'zadaća', translation: 'läxa' },
          { id: 1132, word: 'učionica', translation: 'klassrum' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Riječi za stvari koje vidimo u prirodi.',
        swedish: 'Natur',
        items: [
          { id: 1133, word: 'sunce', translation: 'sol' },
          { id: 1134, word: 'mjesec', translation: 'måne' },
          { id: 1135, word: 'zvijezda', translation: 'stjärna' },
          { id: 1136, word: 'drvo', translation: 'träd' },
          { id: 1137, word: 'cvijet', translation: 'blomma' },
          { id: 1138, word: 'trava', translation: 'gräs' },
          { id: 1139, word: 'kamen', translation: 'sten' },
          { id: 1140, word: 'planina', translation: 'berg' },
          { id: 1141, word: 'more', translation: 'hav' },
          { id: 1142, word: 'kiša', translation: 'regn' },
          { id: 1143, word: 'snijeg', translation: 'snö' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Nauči dijelove ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 1144, word: 'glava', translation: 'huvud' },
          { id: 1145, word: 'kosa', translation: 'hår' },
          { id: 1146, word: 'oko', translation: 'öga' },
          { id: 1147, word: 'uho', translation: 'öra' },
          { id: 1148, word: 'nos', translation: 'näsa' },
          { id: 1149, word: 'usta', translation: 'mun' },
          { id: 1150, word: 'zub', translation: 'tand' },
          { id: 1151, word: 'ruka', translation: 'hand/arm' },
          { id: 1152, word: 'noga', translation: 'ben/fot' },
          { id: 1153, word: 'prst', translation: 'finger' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Nazivi za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 1154, word: 'majica', translation: 't-shirt' },
          { id: 1155, word: 'hlače', translation: 'byxor' },
          { id: 1156, word: 'džemper', translation: 'tröja' },
          { id: 1157, word: 'jakna', translation: 'jacka' },
          { id: 1158, word: 'haljina', translation: 'klänning' },
          { id: 1159, word: 'cipele', translation: 'skor' },
          { id: 1160, word: 'patike', translation: 'sneakers' },
          { id: 1161, word: 'čarape', translation: 'strumpor' },
          { id: 1162, word: 'kapa', translation: 'mössa' },
          { id: 1163, word: 'šal', translation: 'halsduk' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Nauči osnovne radnje.',
        swedish: 'Verb',
        items: [
          { id: 1164, word: 'jesti', translation: 'äta' },
          { id: 1165, word: 'piti', translation: 'dricka' },
          { id: 1166, word: 'spavati', translation: 'sova' },
          { id: 1167, word: 'trčati', translation: 'springa' },
          { id: 1168, word: 'hodati', translation: 'gå' },
          { id: 1169, word: 'čitati', translation: 'läsa' },
          { id: 1170, word: 'pisati', translation: 'skriva' },
          { id: 1171, word: 'gledati', translation: 'titta' },
          { id: 1172, word: 'igrati se', translation: 'leka' },
          { id: 1173, word: 'pjevati', translation: 'sjunga' },
          { id: 1174, word: 'crtati', translation: 'rita' },
        ]
      },
    },
    '4-6': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 2101, word: 'računar', translation: 'dator' },
          { id: 2102, word: 'telefon', translation: 'telefon' },
          { id: 2103, word: 'televizor', translation: 'TV' },
          { id: 2104, word: 'ključ', translation: 'nyckel' },
          { id: 2105, word: 'novčanik', translation: 'plånbok' },
          { id: 2106, word: 'kišobran', translation: 'paraply' },
          { id: 2107, word: 'ruksak', translation: 'ryggsäck' },
          { id: 2108, word: 'lampa', translation: 'lampa' },
          { id: 2117, word: 'fotoaparat', translation: 'kamera' },
          { id: 2118, word: 'bicikl', translation: 'cykel' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 2109, word: 'trg', translation: 'torg' },
          { id: 2110, word: 'općina', translation: 'kommun' },
          { id: 2111, word: 'bolnica', translation: 'sjukhus' },
          { id: 2112, word: 'biblioteka', translation: 'bibliotek' },
          { id: 2113, word: 'pozorište', translation: 'teater' },
          { id: 2114, word: 'prodavnica', translation: 'affär' },
          { id: 2115, word: 'njiva', translation: 'åker' },
          { id: 2116, word: 'livada', translation: 'äng' },
          { id: 2119, word: 'aerodrom', translation: 'flygplats' },
          { id: 2120, word: 'stanica', translation: 'station' },
          { id: 2121, word: 'semafor', translation: 'trafikljus' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Pojmovi vezani za školu i obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 2122, word: 'predmet', translation: 'ämne' },
          { id: 2123, word: 'ocjena', translation: 'betyg' },
          { id: 2124, word: 'test', translation: 'prov' },
          { id: 2125, word: 'historija', translation: 'historia' },
          { id: 2126, word: 'geografija', translation: 'geografi' },
          { id: 2127, word: 'matematika', translation: 'matematik' },
          { id: 2128, word: 'eksperiment', translation: 'experiment' },
          { id: 2129, word: 'gimnazija', translation: 'gymnasium' },
          { id: 2130, word: 'raspored', translation: 'schema' },
          { id: 2131, word: 'nastavnik', translation: 'lärare' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Složenije riječi iz prirode.',
        swedish: 'Natur',
        items: [
          { id: 2132, word: 'okoliš', translation: 'miljö' },
          { id: 2133, word: 'klima', translation: 'klimat' },
          { id: 2134, word: 'atmosfera', translation: 'atmosfär' },
          { id: 2135, word: 'kontinent', translation: 'kontinent' },
          { id: 2136, word: 'okean', translation: 'ocean' },
          { id: 2137, word: 'glečer', translation: 'glaciär' },
          { id: 2138, word: 'pustinja', translation: 'öken' },
          { id: 2139, word: 'vulkan', translation: 'vulkan' },
          { id: 2140, word: 'zemljotres', translation: 'jordbävning' },
          { id: 2141, word: 'vrsta', translation: 'art (species)' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Detaljniji dijelovi ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 2142, word: 'mozak', translation: 'hjärna' },
          { id: 2143, word: 'srce', translation: 'hjärta' },
          { id: 2144, word: 'pluća', translation: 'lungor' },
          { id: 2145, word: 'stomak', translation: 'mage' },
          { id: 2146, word: 'krv', translation: 'blod' },
          { id: 2147, word: 'mišić', translation: 'muskel' },
          { id: 2148, word: 'kost', translation: 'ben (skelett)' },
          { id: 2149, word: 'koža', translation: 'hud' },
          { id: 2150, word: 'organ', translation: 'organ' },
          { id: 2151, word: 'ćelija', translation: 'cell' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Više naziva za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 2152, word: 'košulja', translation: 'skjorta' },
          { id: 2153, word: 'suknja', translation: 'kjol' },
          { id: 2154, word: 'odijelo', translation: 'kostym' },
          { id: 2155, word: 'kaput', translation: 'kappa' },
          { id: 2156, word: 'rukavice', translation: 'handskar' },
          { id: 2157, word: 'čizme', translation: 'stövlar' },
          { id: 2158, word: 'sandale', translation: 'sandaler' },
          { id: 2159, word: 'kaiš', translation: 'bälte' },
          { id: 2160, word: 'šešir', translation: 'hatt' },
          { id: 2161, word: 'kravata', translation: 'slips' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Složenije radnje.',
        swedish: 'Verb',
        items: [
          { id: 2162, word: 'putovati', translation: 'resa' },
          { id: 2163, word: 'učiti', translation: 'lära sig/studera' },
          { id: 2164, word: 'razumjeti', translation: 'förstå' },
          { id: 2165, word: 'pitati', translation: 'fråga' },
          { id: 2166, word: 'odgovoriti', translation: 'svara' },
          { id: 2167, word: 'pomoći', translation: 'hjälpa' },
          { id: 2168, word: 'vjerovati', translation: 'tro' },
          { id: 2169, word: 'misliti', translation: 'tänka/tycka' },
          { id: 2170, word: 'graditi', translation: 'bygga' },
          { id: 2171, word: 'otkriti', translation: 'upptäcka' },
        ]
      },
    },
    '7-9': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 3101, word: 'punjač', translation: 'laddare' },
          { id: 3102, word: 'slušalice', translation: 'hörlurar' },
          { id: 3103, word: 'dokument', translation: 'dokument' },
          { id: 3104, word: 'ugovor', translation: 'avtal' },
          { id: 3105, word: 'račun', translation: 'faktura/kvitto' },
          { id: 3106, word: 'pernica', translation: 'pennskrin' },
          { id: 3107, word: 'kalendar', translation: 'kalender' },
          { id: 3115, word: 'pasoš', translation: 'pass' },
          { id: 3116, word: 'vozačka dozvola', translation: 'körkort' },
          { id: 3117, word: 'polica', translation: 'hylla' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 3108, word: 'saobraćaj', translation: 'trafik' },
          { id: 3109, word: 'industrija', translation: 'industri' },
          { id: 3110, word: 'stanovništvo', translation: 'befolkning' },
          { id: 3111, word: 'infrastruktura', translation: 'infrastruktur' },
          { id: 3112, word: 'poljoprivreda', translation: 'jordbruk' },
          { id: 3113, word: 'znamenitost', translation: 'sevärdhet' },
          { id: 3114, word: 'predgrađe', translation: 'förort' },
          { id: 3118, word: 'urbanizam', translation: 'urbanism' },
          { id: 3119, word: 'ruralno', translation: 'lantlig' },
          { id: 3120, word: 'metropola', translation: 'metropol' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Apstraktniji pojmovi vezani za obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 3121, word: 'obrazovanje', translation: 'utbildning' },
          { id: 3122, word: 'znanje', translation: 'kunskap' },
          { id: 3123, word: 'analiza', translation: 'analys' },
          { id: 3124, word: 'hipoteza', translation: 'hypotes' },
          { id: 3125, word: 'teorija', translation: 'teori' },
          { id: 3126, word: 'fakultet', translation: 'fakultet/universitet' },
          { id: 3127, word: 'diploma', translation: 'examensbevis' },
          { id: 3128, word: 'istraživanje', translation: 'forskning' },
          { id: 3129, word: 'perspektiva', translation: 'perspektiv' },
          { id: 3130, word: 'zaključak', translation: 'slutsats' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Napredni pojmovi iz prirode i nauke.',
        swedish: 'Natur',
        items: [
          { id: 3131, word: 'ekosistem', translation: 'ekosystem' },
          { id: 3132, word: 'biodiverzitet', translation: 'biologisk mångfald' },
          { id: 3133, word: 'evolucija', translation: 'evolution' },
          { id: 3134, word: 'fotosinteza', translation: 'fotosyntes' },
          { id: 3135, word: 'gravitacija', translation: 'gravitation' },
          { id: 3136, word: 'svemir', translation: 'universum' },
          { id: 3137, word: 'galaksija', translation: 'galax' },
          { id: 3138, word: 'molekula', translation: 'molekyl' },
          { id: 3139, word: 'atom', translation: 'atom' },
          { id: 3140, word: 'energija', translation: 'energi' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Složeni pojmovi vezani za ljudsko tijelo.',
        swedish: 'Människokroppen',
        items: [
          { id: 3141, word: 'organizam', translation: 'organism' },
          { id: 3142, word: 'imunitet', translation: 'immunitet' },
          { id: 3143, word: 'metabolizam', translation: 'metabolism/ämnesomsättning' },
          { id: 3144, word: 'genetika', translation: 'genetik' },
          { id: 3145, word: 'cirkulacija', translation: 'cirkulation' },
          { id: 3146, word: 'respiracija', translation: 'andning' },
          { id: 3147, word: 'skelet', translation: 'skelett' },
          { id: 3148, word: 'svijest', translation: 'medvetande' },
          { id: 3149, word: 'emocija', translation: 'känsla' },
          { id: 3150, word: 'instinkt', translation: 'instinkt' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Specifični nazivi za odjeću i materijale.',
        swedish: 'Kläder och skor',
        items: [
          { id: 3151, word: 'pamuk', translation: 'bomull' },
          { id: 3152, word: 'vuna', translation: 'ull' },
          { id: 3153, word: 'svila', translation: 'siden' },
          { id: 3154, word: 'koža', translation: 'läder' },
          { id: 3155, word: 'uniforma', translation: 'uniform' },
          { id: 3156, word: 'dres', translation: 'matchtröja' },
          { id: 3157, word: 'odijelo za kupanje', translation: 'badkläder' },
          { id: 3158, word: 'veš', translation: 'underkläder' },
          { id: 3159, word: 'aksesoar', translation: 'accessoar' },
          { id: 3160, word: 'brend', translation: 'märke' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Apstraktni glagoli.',
        swedish: 'Verb',
        items: [
          { id: 3161, word: 'analizirati', translation: 'analysera' },
          { id: 3162, word: 'kritikovati', translation: 'kritisera' },
          { id: 3163, word: 'argumentovati', translation: 'argumentera' },
          { id: 3164, word: 'pretpostaviti', translation: 'anta' },
          { id: 3165, word: 'zaključiti', translation: 'dra en slutsats' },
          { id: 3166, word: 'komunicirati', translation: 'kommunicera' },
          { id: 3167, word: 'interpretirati', translation: 'tolka' },
          { id: 3168, word: 'utjecati', translation: 'påverka' },
          { id: 3169, word: 'razviti', translation: 'utveckla' },
          { id: 3170, word: 'ostvariti', translation: 'förverkliga/uppnå' },
        ]
      },
    },
  },
  croatian: {
    '1-3': {
      family: {
        title: 'Obitelj',
        description: 'Nauči riječi za članove obitelji.',
        swedish: 'Familj',
        items: [
          { id: 1001, word: 'majka', translation: 'mamma' },
          { id: 1002, word: 'otac', translation: 'pappa' },
          { id: 1003, word: 'sestra', translation: 'syster' },
          { id: 1004, word: 'brat', translation: 'bror' },
          { id: 1005, word: 'baka', translation: 'farmor/mormor' },
          { id: 1006, word: 'djed', translation: 'farfar/morfar' },
          { id: 1219, word: 'teta', translation: 'moster/faster' },
          { id: 1220, word: 'stric', translation: 'farbror' },
          { id: 1221, word: 'ujak', translation: 'morbror' },
          { id: 1222, word: 'beba', translation: 'bebis' },
        ],
      },
      colors: {
        title: 'Boje',
        description: 'Otkrij nazive za različite boje.',
        swedish: 'Färger',
        items: [
          { id: 1007, word: 'crvena', translation: 'röd' },
          { id: 1008, word: 'plava', translation: 'blå' },
          { id: 1009, word: 'zelena', translation: 'grön' },
          { id: 1010, word: 'žuta', translation: 'gul' },
          { id: 1011, word: 'crna', translation: 'svart' },
          { id: 1012, word: 'bijela', translation: 'vit' },
          { id: 1223, word: 'narančasta', translation: 'orange' },
          { id: 1224, word: 'ljubičasta', translation: 'lila' },
          { id: 1225, word: 'smeđa', translation: 'brun' },
          { id: 1226, word: 'siva', translation: 'grå' },
        ],
      },
      food: {
        title: 'Hrana i Piće',
        description: 'Istraži riječi vezane za hranu i piće.',
        swedish: 'Mat och Dryck',
        items: [
          { id: 2, word: 'kruh', translation: 'bröd' },
          { id: 22, word: 'mlijeko', translation: 'mjölk' },
          { id: 6, word: 'jabuka', translation: 'äpple' },
          { id: 12, word: 'voda', translation: 'vatten' },
          { id: 1, word: 'kava', translation: 'kaffe' },
          { id: 1227, word: 'sok', translation: 'juice' },
          { id: 1228, word: 'sir', translation: 'ost' },
          { id: 1229, word: 'meso', translation: 'kött' },
          { id: 1230, word: 'juha', translation: 'soppa' },
          { id: 1231, word: 'kolač', translation: 'kaka' },
          { id: 1232, word: 'sladoled', translation: 'glass' },
        ],
      },
      animals: {
        title: 'Životinje',
        description: 'Upoznaj se s nazivima životinja.',
        swedish: 'Djur',
        items: [
          { id: 8, word: 'mačka', translation: 'katt' },
          { id: 9, word: 'pas', translation: 'hund' },
          { id: 51, word: 'riba', translation: 'fisk' },
          { id: 52, word: 'ptica', translation: 'fågel' },
          { id: 53, word: 'medvjed', translation: 'björn' },
          { id: 1233, word: 'lav', translation: 'lejon' },
          { id: 1234, word: 'tigar', translation: 'tiger' },
          { id: 1235, word: 'konj', translation: 'häst' },
          { id: 1236, word: 'krava', translation: 'ko' },
          { id: 1237, word: 'ovca', translation: 'får' },
        ],
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 1201, word: 'stolac', translation: 'stol' },
          { id: 1202, word: 'stol', translation: 'bord' },
          { id: 1203, word: 'krevet', translation: 'säng' },
          { id: 1204, word: 'čaša', translation: 'glas' },
          { id: 1205, word: 'tanjur', translation: 'tallrik' },
          { id: 1206, word: 'žlica', translation: 'sked' },
          { id: 1207, word: 'vilica', translation: 'gaffel' },
          { id: 1208, word: 'bilježnica', translation: 'anteckningsbok' },
          { id: 1209, word: 'olovka', translation: 'penna' },
          { id: 1238, word: 'prozor', translation: 'fönster' },
          { id: 1239, word: 'vrata', translation: 'dörr' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 1210, word: 'grad', translation: 'stad' },
          { id: 1211, word: 'selo', translation: 'by' },
          { id: 1212, word: 'ulica', translation: 'gata' },
          { id: 1213, word: 'zgrada', translation: 'byggnad' },
          { id: 1214, word: 'kuća', translation: 'hus' },
          { id: 1215, word: 'park', translation: 'park' },
          { id: 1216, word: 'rijeka', translation: 'flod' },
          { id: 1217, word: 'most', translation: 'bro' },
          { id: 1218, word: 'tržnica', translation: 'marknad' },
          { id: 1240, word: 'igralište', translation: 'lekplats' },
          { id: 1241, word: 'trgovina', translation: 'affär' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Riječi koje koristimo u školi.',
        swedish: 'Skola',
        items: [
          { id: 1242, word: 'učiteljica', translation: 'lärare (kvinnlig)' },
          { id: 1243, word: 'učenik', translation: 'elev' },
          { id: 1244, word: 'ploča', translation: 'tavla' },
          { id: 1245, word: 'kreda', translation: 'krita' },
          { id: 1246, word: 'spužva', translation: 'svamp' },
          { id: 1247, word: 'knjiga', translation: 'bok' },
          { id: 1248, word: 'odmor', translation: 'rast' },
          { id: 1249, word: 'sat', translation: 'lektion' },
          { id: 1250, word: 'zadaća', translation: 'läxa' },
          { id: 1251, word: 'učionica', translation: 'klassrum' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Riječi za stvari koje vidimo u prirodi.',
        swedish: 'Natur',
        items: [
          { id: 1252, word: 'sunce', translation: 'sol' },
          { id: 1253, word: 'mjesec', translation: 'måne' },
          { id: 1254, word: 'zvijezda', translation: 'stjärna' },
          { id: 1255, word: 'stablo', translation: 'träd' },
          { id: 1256, word: 'cvijet', translation: 'blomma' },
          { id: 1257, word: 'trava', translation: 'gräs' },
          { id: 1258, word: 'kamen', translation: 'sten' },
          { id: 1259, word: 'planina', translation: 'berg' },
          { id: 1260, word: 'more', translation: 'hav' },
          { id: 1261, word: 'kiša', translation: 'regn' },
          { id: 1262, word: 'snijeg', translation: 'snö' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Nauči dijelove ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 1263, word: 'glava', translation: 'huvud' },
          { id: 1264, word: 'kosa', translation: 'hår' },
          { id: 1265, word: 'oko', translation: 'öga' },
          { id: 1266, word: 'uho', translation: 'öra' },
          { id: 1267, word: 'nos', translation: 'näsa' },
          { id: 1268, word: 'usta', translation: 'mun' },
          { id: 1269, word: 'zub', translation: 'tand' },
          { id: 1270, word: 'ruka', translation: 'hand/arm' },
          { id: 1271, word: 'noga', translation: 'ben/fot' },
          { id: 1272, word: 'prst', translation: 'finger' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Nazivi za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 1273, word: 'majica', translation: 't-shirt' },
          { id: 1274, word: 'hlače', translation: 'byxor' },
          { id: 1275, word: 'vesta', translation: 'tröja/kofta' },
          { id: 1276, word: 'jakna', translation: 'jacka' },
          { id: 1277, word: 'haljina', translation: 'klänning' },
          { id: 1278, word: 'cipele', translation: 'skor' },
          { id: 1279, word: 'tenisice', translation: 'sneakers' },
          { id: 1280, word: 'čarape', translation: 'strumpor' },
          { id: 1281, word: 'kapa', translation: 'mössa' },
          { id: 1282, word: 'šal', translation: 'halsduk' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Nauči osnovne radnje.',
        swedish: 'Verb',
        items: [
          { id: 1283, word: 'jesti', translation: 'äta' },
          { id: 1284, word: 'piti', translation: 'dricka' },
          { id: 1285, word: 'spavati', translation: 'sova' },
          { id: 1286, word: 'trčati', translation: 'springa' },
          { id: 1287, word: 'hodati', translation: 'gå' },
          { id: 1288, word: 'čitati', translation: 'läsa' },
          { id: 1289, word: 'pisati', translation: 'skriva' },
          { id: 1290, word: 'gledati', translation: 'titta' },
          { id: 1291, word: 'igrati se', translation: 'leka' },
          { id: 1292, word: 'pjevati', translation: 'sjunga' },
          { id: 1293, word: 'crtati', translation: 'rita' },
        ]
      },
    },
    '4-6': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 2201, word: 'računalo', translation: 'dator' },
          { id: 2202, word: 'mobitel', translation: 'mobiltelefon' },
          { id: 2203, word: 'televizor', translation: 'TV' },
          { id: 2204, word: 'ključ', translation: 'nyckel' },
          { id: 2205, word: 'novčanik', translation: 'plånbok' },
          { id: 2206, word: 'kišobran', translation: 'paraply' },
          { id: 2207, word: 'ruksak', translation: 'ryggsäck' },
          { id: 2208, word: 'svjetiljka', translation: 'lampa' },
          { id: 2220, word: 'fotoaparat', translation: 'kamera' },
          { id: 2221, word: 'bicikl', translation: 'cykel' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 2209, word: 'trg', translation: 'torg' },
          { id: 2210, word: 'općina', translation: 'kommun' },
          { id: 2211, word: 'bolnica', translation: 'sjukhus' },
          { id: 2212, word: 'knjižnica', translation: 'bibliotek' },
          { id: 2213, word: 'kazalište', translation: 'teater' },
          { id: 2214, word: 'trgovina', translation: 'affär' },
          { id: 2215, word: 'polje', translation: 'fält' },
          { id: 2216, word: 'livada', translation: 'äng' },
          { id: 2222, word: 'zračna luka', translation: 'flygplats' },
          { id: 2223, word: 'kolodvor', translation: 'station' },
          { id: 2224, word: 'semafor', translation: 'trafikljus' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Pojmovi vezani za školu i obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 2225, word: 'predmet', translation: 'ämne' },
          { id: 2226, word: 'ocjena', translation: 'betyg' },
          { id: 2227, word: 'ispit', translation: 'prov' },
          { id: 2228, word: 'povijest', translation: 'historia' },
          { id: 2229, word: 'zemljopis', translation: 'geografi' },
          { id: 2230, word: 'matematika', translation: 'matematik' },
          { id: 2231, word: 'pokus', translation: 'experiment' },
          { id: 2232, word: 'gimnazija', translation: 'gymnasium' },
          { id: 2233, word: 'raspored', translation: 'schema' },
          { id: 2234, word: 'nastavnik', translation: 'lärare' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Složenije riječi iz prirode.',
        swedish: 'Natur',
        items: [
          { id: 2235, word: 'okoliš', translation: 'miljö' },
          { id: 2236, word: 'klima', translation: 'klimat' },
          { id: 2237, word: 'atmosfera', translation: 'atmosfär' },
          { id: 2238, word: 'kontinent', translation: 'kontinent' },
          { id: 2239, word: 'ocean', translation: 'ocean' },
          { id: 2240, word: 'ledenjak', translation: 'glaciär' },
          { id: 2241, word: 'pustinja', translation: 'öken' },
          { id: 2242, word: 'vulkan', translation: 'vulkan' },
          { id: 2243, word: 'potres', translation: 'jordbävning' },
          { id: 2244, word: 'vrsta', translation: 'art (species)' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Detaljniji dijelovi ljudskog tijela.',
        swedish: 'Människokroppen',
        items: [
          { id: 2245, word: 'mozak', translation: 'hjärna' },
          { id: 2246, word: 'srce', translation: 'hjärta' },
          { id: 2247, word: 'pluća', translation: 'lungor' },
          { id: 2248, word: 'želudac', translation: 'mage' },
          { id: 2249, word: 'krv', translation: 'blod' },
          { id: 2250, word: 'mišić', translation: 'muskel' },
          { id: 2251, word: 'kost', translation: 'ben (skelett)' },
          { id: 2252, word: 'koža', translation: 'hud' },
          { id: 2253, word: 'organ', translation: 'organ' },
          { id: 2254, word: 'stanica', translation: 'cell' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Više naziva za odjeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 2255, word: 'košulja', translation: 'skjorta' },
          { id: 2256, word: 'suknja', translation: 'kjol' },
          { id: 2257, word: 'odijelo', translation: 'kostym' },
          { id: 2258, word: 'kaput', translation: 'kappa' },
          { id: 2259, word: 'rukavice', translation: 'handskar' },
          { id: 2260, word: 'čizme', translation: 'stövlar' },
          { id: 2261, word: 'sandale', translation: 'sandaler' },
          { id: 2262, word: 'remen', translation: 'bälte' },
          { id: 2263, word: 'šešir', translation: 'hatt' },
          { id: 2264, word: 'kravata', translation: 'slips' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Složenije radnje.',
        swedish: 'Verb',
        items: [
          { id: 2265, word: 'putovati', translation: 'resa' },
          { id: 2266, word: 'učiti', translation: 'lära sig/studera' },
          { id: 2267, word: 'razumjeti', translation: 'förstå' },
          { id: 2268, word: 'pitati', translation: 'fråga' },
          { id: 2269, word: 'odgovoriti', translation: 'svara' },
          { id: 2270, word: 'pomoći', translation: 'hjälpa' },
          { id: 2271, word: 'vjerovati', translation: 'tro' },
          { id: 2272, word: 'misliti', translation: 'tänka/tycka' },
          { id: 2273, word: 'graditi', translation: 'bygga' },
          { id: 2274, word: 'otkriti', translation: 'upptäcka' },
        ]
      },
    },
    '7-9': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 3201, word: 'punjač', translation: 'laddare' },
          { id: 3202, word: 'slušalice', translation: 'hörlurar' },
          { id: 3203, word: 'dokument', translation: 'dokument' },
          { id: 3204, word: 'ugovor', translation: 'avtal' },
          { id: 3205, word: 'račun', translation: 'faktura/kvitto' },
          { id: 3206, word: 'pernica', translation: 'pennskrin' },
          { id: 3207, word: 'kalendar', translation: 'kalender' },
          { id: 3215, word: 'putovnica', translation: 'pass' },
          { id: 3216, word: 'vozačka dozvola', translation: 'körkort' },
          { id: 3217, word: 'polica', translation: 'hylla' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Riječi za opis urbanih i ruralnih mjesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 3208, word: 'promet', translation: 'trafik' },
          { id: 3209, word: 'industrija', translation: 'industri' },
          { id: 3210, word: 'stanovništvo', translation: 'befolkning' },
          { id: 3211, word: 'infrastruktura', translation: 'infrastruktur' },
          { id: 3212, word: 'poljoprivreda', translation: 'jordbruk' },
          { id: 3213, word: 'znamenitost', translation: 'sevärdhet' },
          { id: 3214, word: 'predgrađe', translation: 'förort' },
          { id: 3218, word: 'urbanizam', translation: 'urbanism' },
          { id: 3219, word: 'ruralno', translation: 'lantlig' },
          { id: 3220, word: 'metropola', translation: 'metropol' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Apstraktniji pojmovi vezani za obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 3221, word: 'obrazovanje', translation: 'utbildning' },
          { id: 3222, word: 'znanost', translation: 'vetenskap' },
          { id: 3223, word: 'analiza', translation: 'analys' },
          { id: 3224, word: 'hipoteza', translation: 'hypotes' },
          { id: 3225, word: 'teorija', translation: 'teori' },
          { id: 3226, word: 'sveučilište', translation: 'universitet' },
          { id: 3227, word: 'diploma', translation: 'examensbevis' },
          { id: 3228, word: 'istraživanje', translation: 'forskning' },
          { id: 3229, word: 'perspektiva', translation: 'perspektiv' },
          { id: 3230, word: 'zaključak', translation: 'slutsats' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Napredni pojmovi iz prirode i znanosti.',
        swedish: 'Natur',
        items: [
          { id: 3231, word: 'ekosustav', translation: 'ekosystem' },
          { id: 3232, word: 'bioraznolikost', translation: 'biologisk mångfald' },
          { id: 3233, word: 'evolucija', translation: 'evolution' },
          { id: 3234, word: 'fotosinteza', translation: 'fotosyntes' },
          { id: 3235, word: 'gravitacija', translation: 'gravitation' },
          { id: 3236, word: 'svemir', translation: 'universum' },
          { id: 3237, word: 'galaksija', translation: 'galax' },
          { id: 3238, word: 'molekula', translation: 'molekyl' },
          { id: 3239, word: 'atom', translation: 'atom' },
          { id: 3240, word: 'energija', translation: 'energi' },
        ]
      },
      body: {
        title: 'Ljudsko tijelo',
        description: 'Složeni pojmovi vezani za ljudsko tijelo.',
        swedish: 'Människokroppen',
        items: [
          { id: 3241, word: 'organizam', translation: 'organism' },
          { id: 3242, word: 'imunost', translation: 'immunitet' },
          { id: 3243, word: 'metabolizam', translation: 'metabolism/ämnesomsättning' },
          { id: 3244, word: 'genetika', translation: 'genetik' },
          { id: 3245, word: 'cirkulacija', translation: 'cirkulation' },
          { id: 3246, word: 'disanje', translation: 'andning' },
          { id: 3247, word: 'kostur', translation: 'skelett' },
          { id: 3248, word: 'svijest', translation: 'medvetande' },
          { id: 3249, word: 'osjećaj', translation: 'känsla' },
          { id: 3250, word: 'instinkt', translation: 'instinkt' },
        ]
      },
      clothing: {
        title: 'Odjeća i obuća',
        description: 'Specifični nazivi za odjeću i materijale.',
        swedish: 'Kläder och skor',
        items: [
          { id: 3251, word: 'pamuk', translation: 'bomull' },
          { id: 3252, word: 'vuna', translation: 'ull' },
          { id: 3253, word: 'svila', translation: 'siden' },
          { id: 3254, word: 'koža', translation: 'läder' },
          { id: 3255, word: 'uniforma', translation: 'uniform' },
          { id: 3256, word: 'dres', translation: 'matchtröja' },
          { id: 3257, word: 'kupaći kostim', translation: 'badkläder' },
          { id: 3258, word: 'donje rublje', translation: 'underkläder' },
          { id: 3259, word: 'modni dodatak', translation: 'accessoar' },
          { id: 3260, word: 'marka', translation: 'märke' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Apstraktni glagoli.',
        swedish: 'Verb',
        items: [
          { id: 3261, word: 'analizirati', translation: 'analysera' },
          { id: 3262, word: 'kritizirati', translation: 'kritisera' },
          { id: 3263, word: 'argumentirati', translation: 'argumentera' },
          { id: 3264, word: 'pretpostaviti', translation: 'anta' },
          { id: 3265, word: 'zaključiti', translation: 'dra en slutsats' },
          { id: 3266, word: 'komunicirati', translation: 'kommunicera' },
          { id: 3267, word: 'interpretirati', translation: 'tolka' },
          { id: 3268, word: 'utjecati', translation: 'påverka' },
          { id: 3269, word: 'razviti', translation: 'utveckla' },
          { id: 3270, word: 'ostvariti', translation: 'förverkliga/uppnå' },
        ]
      },
    },
  },
  serbian: {
    '1-3': {
      family: {
        title: 'Porodica',
        description: 'Nauči reči za članove porodice.',
        swedish: 'Familj',
        items: [
          { id: 1001, word: 'majka', translation: 'mamma' },
          { id: 1002, word: 'otac', translation: 'pappa' },
          { id: 1003, word: 'sestra', translation: 'syster' },
          { id: 1004, word: 'brat', translation: 'bror' },
          { id: 1005, word: 'baka', translation: 'farmor/mormor' },
          { id: 1006, word: 'deka', translation: 'farfar/morfar' },
          { id: 1319, word: 'tetka', translation: 'moster/faster' },
          { id: 1320, word: 'stric', translation: 'farbror' },
          { id: 1321, word: 'ujak', translation: 'morbror' },
          { id: 1322, word: 'beba', translation: 'bebis' },
        ],
      },
      colors: {
        title: 'Boje',
        description: 'Otkrij nazive za različite boje.',
        swedish: 'Färger',
        items: [
          { id: 1007, word: 'crvena', translation: 'röd' },
          { id: 1008, word: 'plava', translation: 'blå' },
          { id: 1009, word: 'zelena', translation: 'grön' },
          { id: 1010, word: 'žuta', translation: 'gul' },
          { id: 1011, word: 'crna', translation: 'svart' },
          { id: 1012, word: 'bela', translation: 'vit' },
          { id: 1323, word: 'narandžasta', translation: 'orange' },
          { id: 1324, word: 'ljubičasta', translation: 'lila' },
          { id: 1325, word: 'braon', translation: 'brun' },
          { id: 1326, word: 'siva', translation: 'grå' },
        ],
      },
      food: {
        title: 'Hrana i Piće',
        description: 'Istraži reči vezane za hranu i piće.',
        swedish: 'Mat och Dryck',
        items: [
          { id: 2, word: 'hleb', translation: 'bröd' },
          { id: 22, word: 'mleko', translation: 'mjölk' },
          { id: 6, word: 'jabuka', translation: 'äpple' },
          { id: 12, word: 'voda', translation: 'vatten' },
          { id: 1, word: 'kafa', translation: 'kaffe' },
          { id: 1327, word: 'sok', translation: 'juice' },
          { id: 1328, word: 'sir', translation: 'ost' },
          { id: 1329, word: 'meso', translation: 'kött' },
          { id: 1330, word: 'supa', translation: 'soppa' },
          { id: 1331, word: 'kolač', translation: 'kaka' },
          { id: 1332, word: 'pljeskavica', translation: 'hamburgare' },
        ],
      },
      animals: {
        title: 'Životinje',
        description: 'Upoznaj se sa nazivima životinja.',
        swedish: 'Djur',
        items: [
          { id: 8, word: 'mačka', translation: 'katt' },
          { id: 9, word: 'pas', translation: 'hund' },
          { id: 16, word: 'riba', translation: 'fisk' },
          { id: 15, word: 'ptica', translation: 'fågel' },
          { id: 30, word: 'medved', translation: 'björn' },
          { id: 1333, word: 'lav', translation: 'lejon' },
          { id: 1334, word: 'tigar', translation: 'tiger' },
          { id: 1335, word: 'konj', translation: 'häst' },
          { id: 1336, word: 'krava', translation: 'ko' },
          { id: 1337, word: 'ovca', translation: 'får' },
        ],
      },
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 1301, word: 'stolica', translation: 'stol' },
          { id: 1302, word: 'sto', translation: 'bord' },
          { id: 1303, word: 'krevet', translation: 'säng' },
          { id: 1304, word: 'čaša', translation: 'glas' },
          { id: 1305, word: 'tanjir', translation: 'tallrik' },
          { id: 1306, word: 'kašika', translation: 'sked' },
          { id: 1307, word: 'viljuška', translation: 'gaffel' },
          { id: 1308, word: 'sveska', translation: 'anteckningsbok' },
          { id: 1309, word: 'olovka', translation: 'penna' },
          { id: 1338, word: 'prozor', translation: 'fönster' },
          { id: 1339, word: 'vrata', translation: 'dörr' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Reči za opis urbanih i ruralnih mesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 1310, word: 'grad', translation: 'stad' },
          { id: 1311, word: 'selo', translation: 'by' },
          { id: 1312, word: 'ulica', translation: 'gata' },
          { id: 1313, word: 'zgrada', translation: 'byggnad' },
          { id: 1314, word: 'kuća', translation: 'hus' },
          { id: 1315, word: 'park', translation: 'park' },
          { id: 1316, word: 'reka', translation: 'flod' },
          { id: 1317, word: 'most', translation: 'bro' },
          { id: 1318, word: 'pijaca', translation: 'marknad' },
          { id: 1340, word: 'igralište', translation: 'lekplats' },
          { id: 1341, word: 'prodavnica', translation: 'affär' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Reči koje koristimo u školi.',
        swedish: 'Skola',
        items: [
          { id: 1342, word: 'učiteljica', translation: 'lärare (kvinnlig)' },
          { id: 1343, word: 'učenik', translation: 'elev' },
          { id: 1344, word: 'tabla', translation: 'tavla' },
          { id: 1345, word: 'kreda', translation: 'krita' },
          { id: 1346, word: 'sunđer', translation: 'svamp' },
          { id: 1347, word: 'knjiga', translation: 'bok' },
          { id: 1348, word: 'odmor', translation: 'rast' },
          { id: 1349, word: 'čas', translation: 'lektion' },
          { id: 1350, word: 'domaći zadatak', translation: 'läxa' },
          { id: 1351, word: 'učionica', translation: 'klassrum' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Reči za stvari koje vidimo u prirodi.',
        swedish: 'Natur',
        items: [
          { id: 1352, word: 'sunce', translation: 'sol' },
          { id: 1353, word: 'mesec', translation: 'måne' },
          { id: 1354, word: 'zvezda', translation: 'stjärna' },
          { id: 1355, word: 'drvo', translation: 'träd' },
          { id: 1356, word: 'cvet', translation: 'blomma' },
          { id: 1357, word: 'trava', translation: 'gräs' },
          { id: 1358, word: 'kamen', translation: 'sten' },
          { id: 1359, word: 'planina', translation: 'berg' },
          { id: 1360, word: 'more', translation: 'hav' },
          { id: 1361, word: 'kiša', translation: 'regn' },
          { id: 1362, word: 'sneg', translation: 'snö' },
        ]
      },
      body: {
        title: 'Ljudsko telo',
        description: 'Nauči delove ljudskog tela.',
        swedish: 'Människokroppen',
        items: [
          { id: 1363, word: 'glava', translation: 'huvud' },
          { id: 1364, word: 'kosa', translation: 'hår' },
          { id: 1365, word: 'oko', translation: 'öga' },
          { id: 1366, word: 'uvo', translation: 'öra' },
          { id: 1367, word: 'nos', translation: 'näsa' },
          { id: 1368, word: 'usta', translation: 'mun' },
          { id: 1369, word: 'zub', translation: 'tand' },
          { id: 1370, word: 'ruka', translation: 'hand/arm' },
          { id: 1371, word: 'noga', translation: 'ben/fot' },
          { id: 1372, word: 'prst', translation: 'finger' },
        ]
      },
      clothing: {
        title: 'Odeća i obuća',
        description: 'Nazivi za odeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 1373, word: 'majica', translation: 't-shirt' },
          { id: 1374, word: 'pantalone', translation: 'byxor' },
          { id: 1375, word: 'džemper', translation: 'tröja' },
          { id: 1376, word: 'jakna', translation: 'jacka' },
          { id: 1377, word: 'haljina', translation: 'klänning' },
          { id: 1378, word: 'cipele', translation: 'skor' },
          { id: 1379, word: 'patike', translation: 'sneakers' },
          { id: 1380, word: 'čarape', translation: 'strumpor' },
          { id: 1381, word: 'kapa', translation: 'mössa' },
          { id: 1382, word: 'šal', translation: 'halsduk' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Nauči osnovne radnje.',
        swedish: 'Verb',
        items: [
          { id: 1383, word: 'jesti', translation: 'äta' },
          { id: 1384, word: 'piti', translation: 'dricka' },
          { id: 1385, word: 'spavati', translation: 'sova' },
          { id: 1386, word: 'trčati', translation: 'springa' },
          { id: 1387, word: 'hodati', translation: 'gå' },
          { id: 1388, word: 'čitati', translation: 'läsa' },
          { id: 1389, word: 'pisati', translation: 'skriva' },
          { id: 1390, word: 'gledati', translation: 'titta' },
          { id: 1391, word: 'igrati se', translation: 'leka' },
          { id: 1392, word: 'pevati', translation: 'sjunga' },
          { id: 1393, word: 'crtati', translation: 'rita' },
        ]
      },
    },
    '4-6': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 2301, word: 'računar', translation: 'dator' },
          { id: 2302, word: 'mobilni telefon', translation: 'mobiltelefon' },
          { id: 2303, word: 'televizor', translation: 'TV' },
          { id: 2304, word: 'ključ', translation: 'nyckel' },
          { id: 2305, word: 'novčanik', translation: 'plånbok' },
          { id: 2306, word: 'kišobran', translation: 'paraply' },
          { id: 2307, word: 'ranac', translation: 'ryggsäck' },
          { id: 2308, word: 'lampa', translation: 'lampa' },
          { id: 2317, word: 'fotoaparat', translation: 'kamera' },
          { id: 2318, word: 'bicikl', translation: 'cykel' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Reči za opis urbanih i ruralnih mesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 2309, word: 'trg', translation: 'torg' },
          { id: 2310, word: 'opština', translation: 'kommun' },
          { id: 2311, word: 'bolnica', translation: 'sjukhus' },
          { id: 2312, word: 'biblioteka', translation: 'bibliotek' },
          { id: 2313, word: 'pozorište', translation: 'teater' },
          { id: 2314, word: 'prodavnica', translation: 'affär' },
          { id: 2315, word: 'njiva', translation: 'åker' },
          { id: 2316, word: 'livada', translation: 'äng' },
          { id: 2319, word: 'aerodrom', translation: 'flygplats' },
          { id: 2320, word: 'stanica', translation: 'station' },
          { id: 2321, word: 'semafor', translation: 'trafikljus' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Pojmovi vezani za školu i obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 2322, word: 'predmet', translation: 'ämne' },
          { id: 2323, word: 'ocena', translation: 'betyg' },
          { id: 2324, word: 'kontrolni', translation: 'prov' },
          { id: 2325, word: 'istorija', translation: 'historia' },
          { id: 2326, word: 'geografija', translation: 'geografi' },
          { id: 2327, word: 'matematika', translation: 'matematik' },
          { id: 2328, word: 'eksperiment', translation: 'experiment' },
          { id: 2329, word: 'gimnazija', translation: 'gymnasium' },
          { id: 2330, word: 'raspored', translation: 'schema' },
          { id: 2331, word: 'nastavnik', translation: 'lärare' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Složenije reči iz prirode.',
        swedish: 'Natur',
        items: [
          { id: 2332, word: 'životna sredina', translation: 'miljö' },
          { id: 2333, word: 'klima', translation: 'klimat' },
          { id: 2334, word: 'atmosfera', translation: 'atmosfär' },
          { id: 2335, word: 'kontinent', translation: 'kontinent' },
          { id: 2336, word: 'okean', translation: 'ocean' },
          { id: 2337, word: 'glečer', translation: 'glaciär' },
          { id: 2338, word: 'pustinja', translation: 'öken' },
          { id: 2339, word: 'vulkan', translation: 'vulkan' },
          { id: 2340, word: 'zemljotres', translation: 'jordbävning' },
          { id: 2341, word: 'vrsta', translation: 'art (species)' },
        ]
      },
      body: {
        title: 'Ljudsko telo',
        description: 'Detaljniji delovi ljudskog tela.',
        swedish: 'Människokroppen',
        items: [
          { id: 2342, word: 'mozak', translation: 'hjärna' },
          { id: 2343, word: 'srce', translation: 'hjärta' },
          { id: 2344, word: 'pluća', translation: 'lungor' },
          { id: 2345, word: 'stomak', translation: 'mage' },
          { id: 2346, word: 'krv', translation: 'blod' },
          { id: 2347, word: 'mišić', translation: 'muskel' },
          { id: 2348, word: 'kost', translation: 'ben (skelett)' },
          { id: 2349, word: 'koža', translation: 'hud' },
          { id: 2350, word: 'organ', translation: 'organ' },
          { id: 2351, word: 'ćelija', translation: 'cell' },
        ]
      },
      clothing: {
        title: 'Odeća i obuća',
        description: 'Više naziva za odeću i obuću.',
        swedish: 'Kläder och skor',
        items: [
          { id: 2352, word: 'košulja', translation: 'skjorta' },
          { id: 2353, word: 'suknja', translation: 'kjol' },
          { id: 2354, word: 'odelo', translation: 'kostym' },
          { id: 2355, word: 'kaput', translation: 'kappa' },
          { id: 2356, word: 'rukavice', translation: 'handskar' },
          { id: 2357, word: 'čizme', translation: 'stövlar' },
          { id: 2358, word: 'sandale', translation: 'sandaler' },
          { id: 2359, word: 'kaiš', translation: 'bälte' },
          { id: 2360, word: 'šešir', translation: 'hatt' },
          { id: 2361, word: 'kravata', translation: 'slips' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Složenije radnje.',
        swedish: 'Verb',
        items: [
          { id: 2362, word: 'putovati', translation: 'resa' },
          { id: 2363, word: 'učiti', translation: 'lära sig/studera' },
          { id: 2364, word: 'razumeti', translation: 'förstå' },
          { id: 2365, word: 'pitati', translation: 'fråga' },
          { id: 2366, word: 'odgovoriti', translation: 'svara' },
          { id: 2367, word: 'pomoći', translation: 'hjälpa' },
          { id: 2368, word: 'verovati', translation: 'tro' },
          { id: 2369, word: 'misliti', translation: 'tänka/tycka' },
          { id: 2370, word: 'graditi', translation: 'bygga' },
          { id: 2371, word: 'otkriti', translation: 'upptäcka' },
        ]
      },
    },
    '7-9': {
      everydayObjects: {
        title: 'Svakodnevni predmeti',
        description: 'Nazivi za stvari koje koristimo svaki dan.',
        swedish: 'Vardagliga föremål',
        items: [
          { id: 3301, word: 'punjač', translation: 'laddare' },
          { id: 3302, word: 'slušalice', translation: 'hörlurar' },
          { id: 3303, word: 'dokument', translation: 'dokument' },
          { id: 3304, word: 'ugovor', translation: 'avtal' },
          { id: 3305, word: 'račun', translation: 'faktura/kvitto' },
          { id: 3306, word: 'pernica', translation: 'pennskrin' },
          { id: 3307, word: 'kalendar', translation: 'kalender' },
          { id: 3315, word: 'pasoš', translation: 'pass' },
          { id: 3316, word: 'vozačka dozvola', translation: 'körkort' },
          { id: 3317, word: 'polica', translation: 'hylla' },
        ]
      },
      cityAndVillage: {
        title: 'Grad i selo',
        description: 'Reči za opis urbanih i ruralnih mesta.',
        swedish: 'Stad och landsbygd',
        items: [
          { id: 3308, word: 'saobraćaj', translation: 'trafik' },
          { id: 3309, word: 'industrija', translation: 'industri' },
          { id: 3310, word: 'stanovništvo', translation: 'befolkning' },
          { id: 3311, word: 'infrastruktura', translation: 'infrastruktur' },
          { id: 3312, word: 'poljoprivreda', translation: 'jordbruk' },
          { id: 3313, word: 'znamenitost', translation: 'sevärdhet' },
          { id: 3314, word: 'predgrađe', translation: 'förort' },
          { id: 3318, word: 'urbanizam', translation: 'urbanism' },
          { id: 3319, word: 'ruralno', translation: 'lantlig' },
          { id: 3320, word: 'metropola', translation: 'metropol' },
        ]
      },
      school: {
        title: 'Škola',
        description: 'Apstraktniji pojmovi vezani za obrazovanje.',
        swedish: 'Skola',
        items: [
          { id: 3321, word: 'obrazovanje', translation: 'utbildning' },
          { id: 3322, word: 'nauka', translation: 'vetenskap' },
          { id: 3323, word: 'analiza', translation: 'analys' },
          { id: 3324, word: 'hipoteza', translation: 'hypotes' },
          { id: 3325, word: 'teorija', translation: 'teori' },
          { id: 3326, word: 'fakultet', translation: 'fakultet/universitet' },
          { id: 3327, word: 'diploma', translation: 'examensbevis' },
          { id: 3328, word: 'istraživanje', translation: 'forskning' },
          { id: 3329, word: 'perspektiva', translation: 'perspektiv' },
          { id: 3330, word: 'zaključak', translation: 'slutsats' },
        ]
      },
      nature: {
        title: 'Priroda',
        description: 'Napredni pojmovi iz prirode i nauke.',
        swedish: 'Natur',
        items: [
          { id: 3331, word: 'ekosistem', translation: 'ekosystem' },
          { id: 3332, word: 'biodiverzitet', translation: 'biologisk mångfald' },
          { id: 3333, word: 'evolucija', translation: 'evolution' },
          { id: 3334, word: 'fotosinteza', translation: 'fotosyntes' },
          { id: 3335, word: 'gravitacija', translation: 'gravitation' },
          { id: 3336, word: 'vasiona', translation: 'universum' },
          { id: 3337, word: 'galaksija', translation: 'galax' },
          { id: 3338, word: 'molekul', translation: 'molekyl' },
          { id: 3339, word: 'atom', translation: 'atom' },
          { id: 3340, word: 'energija', translation: 'energi' },
        ]
      },
      body: {
        title: 'Ljudsko telo',
        description: 'Složeni pojmovi vezani za ljudsko telo.',
        swedish: 'Människokroppen',
        items: [
          { id: 3341, word: 'organizam', translation: 'organism' },
          { id: 3342, word: 'imunitet', translation: 'immunitet' },
          { id: 3343, word: 'metabolizam', translation: 'metabolism/ämnesomsättning' },
          { id: 3344, word: 'genetika', translation: 'genetik' },
          { id: 3345, word: 'cirkulacija', translation: 'cirkulation' },
          { id: 3346, word: 'disanje', translation: 'andning' },
          { id: 3347, word: 'skelet', translation: 'skelett' },
          { id: 3348, word: 'svest', translation: 'medvetande' },
          { id: 3349, word: 'emocija', translation: 'känsla' },
          { id: 3350, word: 'instinkt', translation: 'instinkt' },
        ]
      },
      clothing: {
        title: 'Odeća i obuća',
        description: 'Specifični nazivi za odeću i materijale.',
        swedish: 'Kläder och skor',
        items: [
          { id: 3351, word: 'pamuk', translation: 'bomull' },
          { id: 3352, word: 'vuna', translation: 'ull' },
          { id: 3353, word: 'svila', translation: 'siden' },
          { id: 3354, word: 'koža', translation: 'läder' },
          { id: 3355, word: 'uniforma', translation: 'uniform' },
          { id: 3356, word: 'dres', translation: 'matchtröja' },
          { id: 3357, word: 'kupaći kostim', translation: 'badkläder' },
          { id: 3358, word: 'donji veš', translation: 'underkläder' },
          { id: 3359, word: 'modni detalj', translation: 'accessoar' },
          { id: 3360, word: 'marka', translation: 'märke' },
        ]
      },
      verbs: {
        title: 'Glagoli',
        description: 'Apstraktni glagoli.',
        swedish: 'Verb',
        items: [
          { id: 3361, word: 'analizirati', translation: 'analysera' },
          { id: 3362, word: 'kritikovati', translation: 'kritisera' },
          { id: 3363, word: 'argumentovati', translation: 'argumentera' },
          { id: 3364, word: 'pretpostaviti', translation: 'anta' },
          { id: 3365, word: 'zaključiti', translation: 'dra en slutsats' },
          { id: 3366, word: 'komunicirati', translation: 'kommunicera' },
          { id: 3367, word: 'interpretirati', translation: 'tolka' },
          { id: 3368, word: 'uticati', translation: 'påverka' },
          { id: 3369, word: 'razviti', translation: 'utveckla' },
          { id: 3370, word: 'ostvariti', translation: 'förverkliga/uppnå' },
        ]
      },
    },
  },
};

    
